import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import test from 'node:test';
import {chromium} from 'playwright-core';
import {unzipSync,strFromU8} from '../apps/web/node_modules/fflate';
import {createNativeHwp} from '../apps/web/src/documents/editable-hwp-export';
import {readQaNativeEngine,exportNativeWithReport,matchReferenceSources,assertQaOutputOutsideSources} from './cf183-template-source-gate.mjs';

const hash=(value:Uint8Array|string)=>createHash('sha256').update(value).digest('hex');
const same=(actual:unknown,expected:unknown,message:string)=>assert.ok(hash(JSON.stringify(actual))===hash(JSON.stringify(expected)),message);
function canonicalCellClips(svg:string){
  // Cell clip names use render-node ordinals, which can change when a text run is added.
  // Preserve every definition/attribute and exact reference topology; rename only proved cell clips.
  const ids=[...svg.matchAll(/<clipPath\b[^>]*\bid="(cell-clip-\d+(?:-[a-z]+)?)"/gu)].map(match=>match[1]);assert.equal(new Set(ids).size,ids.length,'Duplicate cell clip definitions');
  const names=new Map(ids.map((id,index)=>[id,id.replace(/^cell-clip-\d+/u,`CF194-cell-${index}`)]));
  for(const id of ids){assert.equal(svg.split(`id="${id}"`).length-1,1,'Cell clip must have one definition');assert.ok(svg.includes(`url(#${id})`),'Cell clip must have a live reference');}
  return svg.replace(/\b(id|clip-path)="([^"]+)"/gu,(full,key,value)=>{if(key==='id')return names.has(value)?`id="${names.get(value)}"`:full;const ref=/^url\(#(cell-clip-\d+(?:-[a-z]+)?)\)$/u.exec(value);if(!ref)return full;assert.ok(names.has(ref[1]),'Dangling cell clip reference');return `clip-path="url(#${names.get(ref[1])})"`;});
}

test('CF194 clip comparison preserves geometry and reference topology while ignoring render-node ordinals',()=>{
  const first='<svg><clipPath id="cell-clip-2"><rect x="1" width="20"/></clipPath><clipPath id="cell-clip-8"><rect x="30" width="40"/></clipPath><g clip-path="url(#cell-clip-2)"/><g clip-path="url(#cell-clip-8)"/></svg>',renamed=first.replaceAll('cell-clip-2','cell-clip-3').replaceAll('cell-clip-8','cell-clip-10');
  assert.equal(canonicalCellClips(first),canonicalCellClips(renamed));assert.notEqual(canonicalCellClips(first),canonicalCellClips(renamed.replace('width="20"','width="21"')));assert.notEqual(canonicalCellClips(first),canonicalCellClips(renamed.replace(/clip-path="url\(#(cell-clip-(?:3|10))\)"/gu,(_,id)=>`clip-path="url(#${id==='cell-clip-3'?'cell-clip-10':'cell-clip-3'})"`)));assert.notEqual(canonicalCellClips(first),canonicalCellClips(first.replaceAll('cell-clip-2','cell-clip-2-fill')));
  assert.throws(()=>canonicalCellClips(first.replace('clip-path="url(#cell-clip-8)"','clip-path="url(#cell-clip-99)"')));assert.throws(()=>canonicalCellClips(first.replace('id="cell-clip-8"','id="cell-clip-2"')));
});

test('CF194 actual native table-cell click, keyboard Undo/Redo, whole apply and same-format reopening',async()=>{
  const output=process.env.CF194_OUTPUT_ROOT;if(output){assert.ok(existsSync(output),'Use a pre-created isolated QA output folder');assert.equal(existsSync(resolve(output,'native-table-result.json')),false,'Preserve previous QA results');if(process.env.CF194_SOURCE_ROOT)assertQaOutputOutsideSources(process.env.CF194_SOURCE_ROOT,output);}
  const results:unknown[]=[];
  const approved=readQaNativeEngine(),module=await import(pathToFileURL(resolve(approved.root,'rhwp.js')).href);
  await module.default({module_or_path:approved.wasm});const Engine=module.HwpDocument;
  const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5V8AAAAASUVORK5CYII=';
  const photo=Buffer.from(png,'base64');
  const contents=[
    {html:'<table><tr><td>Ⅰ.</td><td>자료 목록</td></tr></table><p>확정 금액 123,456원 · 보존 본문</p>',text:'Ⅰ.자료 목록확정 금액 123,456원 · 보존 본문',tables:1,tableCells:[[{row:0,col:0,rowSpan:1,colSpan:1,text:'Ⅰ.'},{row:0,col:1,rowSpan:1,colSpan:1,text:'자료 목록'}]],images:0},
    {html:`<table><tr><td rowspan="2">병합</td><td>120</td></tr><tr><td>145</td></tr></table><img src="data:image/png;base64,${png}" width="40" height="40">`,text:'병합120145',tables:1,tableCells:[[{row:0,col:0,rowSpan:2,colSpan:1,text:'병합'},{row:0,col:1,rowSpan:1,colSpan:1,text:'120'},{row:1,col:1,rowSpan:1,colSpan:1,text:'145'}]],images:1,pictures:[{bytes:photo,width:40,height:40}]},
  ].map(content=>({...content,width:794,height:1123,margins:{top:40,right:40,bottom:40,left:40}}));
  const fixture=new Engine(createNativeHwp(contents,Engine)),sources:Record<string,Uint8Array>={};
  try{for(const format of ['hwp','hwpx'] as const){const result=exportNativeWithReport(fixture,format);assert.equal(result.report.count,0);assert.equal(result.report.lossRecords,0);sources[format]=result.bytes;}}finally{fixture.free();}
  const cases=[{id:'hwp',format:'hwp' as const,page:0,pages:2},{id:'hwpx',format:'hwpx' as const,page:0,pages:2}];
  let actualSource:string|undefined;
  if(process.env.CF194_SOURCE_ROOT){const originals=matchReferenceSources(process.env.CF194_SOURCE_ROOT,JSON.parse(readFileSync('docs/templates/reference-inventory.json','utf8'))),file=originals.find((file:any)=>file.fileId==='TPL-REF-017');assert.ok(file&&file.extension==='.hwpx');actualSource=file.source;sources['017']=new Uint8Array(readFileSync(file.source));cases.push({id:'017',format:'hwpx',page:2,pages:47});}
  const runtime=resolve('pinned-runtime/rhwp'),manifest=JSON.parse(readFileSync(resolve(runtime,'build-manifest.json'),'utf8'));
  const files=new Set(['index.html','build-manifest.json',...manifest.files.map((file:{path:string})=>file.path)]);
  const savedFiles=new Map<string,Uint8Array>(),saveRequests=new Map<string,number>();let failNextSave=false,failedSaves=0;
  const {createServer}=await import('../apps/web/qa/vite-server.js');
  const server=await createServer({root:resolve('apps/web'),...(process.env.CF149_CACHE_ROOT?{cacheDir:process.env.CF149_CACHE_ROOT}:{}),server:{host:'127.0.0.1',port:0,hmr:false},logLevel:'error',plugins:[{
    name:'cf194-native-table',
    configureServer(server){server.middlewares.use(async(req,res,next)=>{
      const pathname=(req.url??'').split('?')[0];
      if(pathname.startsWith('/rhwp/')){const name=pathname.slice(6)||'index.html';if(!files.has(name)){res.statusCode=404;res.end();return;}const file=resolve(runtime,name);assert.ok(file.startsWith(runtime+sep));
        res.setHeader('Content-Type',name.endsWith('.html')?'text/html':name.endsWith('.json')?'application/json':name.endsWith('.js')?'text/javascript':name.endsWith('.wasm')?'application/wasm':name.endsWith('.css')?'text/css':name.endsWith('.woff2')?'font/woff2':'application/octet-stream');res.end(readFileSync(file));return;}
      if(pathname.startsWith('/original.')){const format=pathname.slice(10);if(sources[format]){res.end(sources[format]);return;}}
      if(pathname==='/saved-native'&&req.method==='POST'){const id=new URL(req.url!,'http://localhost').searchParams.get('source');assert.ok(id&&sources[id]);saveRequests.set(id,(saveRequests.get(id)??0)+1);const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;assert.ok(size<50_000_000,'Local QA file limit');chunks.push(Buffer.from(chunk));}if(failNextSave){failNextSave=false;failedSaves++;res.statusCode=503;res.end('Synthetic QA save unavailable');return;}savedFiles.set(id,new Uint8Array(Buffer.concat(chunks)));res.end('Saved in isolated memory');return;}
      if(pathname!=='/table-qa.html')return next();res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml(req.url!,'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module" src="/table-entry.js"></script></body></html>'));
    });},
    resolveId:id=>id==='/table-entry.js'?'\0table-entry':undefined,
    load:id=>id==='\0table-entry'?`
      import React,{useState,useEffect}from'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{RhwpEditorDialog}from'/src/documents/RhwpEditorDialog.tsx';import'/src/documents/RhwpEditorDialog.css';
      window.__CLAIM_CENTER_RHWP_STUDIO_URL__=location.origin+'/rhwp/';window.cf194={applies:[],saved:null,attempts:0};
      function App(){const[file,setFile]=useState(null);const[open,setOpen]=useState(true);const[disabled,setDisabled]=useState(false);const format=new URLSearchParams(location.search).get('format');window.cf194.setDisabled=value=>flushSync(()=>setDisabled(value));
        useEffect(()=>{fetch('/original.'+new URLSearchParams(location.search).get('source')).then(r=>r.arrayBuffer()).then(bytes=>setFile(new File([bytes],'비공개 표 검수.'+format)));},[]);
        const hash=async data=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data))).map(n=>n.toString(16).padStart(2,'0')).join('');
        return file?React.createElement(React.Fragment,null,React.createElement('button',{onClick:()=>{setFile(window.cf194.saved);setOpen(true);}},'저장한 표 작업본 재열기'),React.createElement(RhwpEditorDialog,{isOpen:open,sourceFile:file,suggestedName:'합성 표',documentLabel:'합성 표 검수',preserveAppliedSource:true,applyDisabled:disabled,onClose:()=>setOpen(false),applyLabel:'표 작업본 검수 적용',onApplyPages:async(pages,edited,original)=>{window.cf194.attempts++;const pageHashes=[];for(const svg of pages)pageHashes.push(await hash(new TextEncoder().encode(svg)));const response=await fetch('/saved-native?source='+new URLSearchParams(location.search).get('source'),{method:'POST',body:edited});if(!response.ok)throw Error('Local QA save failed');window.cf194.applies.push({pageHashes,name:edited.name,originalName:original.name,originalHash:await hash(await original.arrayBuffer()),editedHash:await hash(await edited.arrayBuffer())});window.cf194.saved=edited;setOpen(false);}})):null;
      }createRoot(document.getElementById('root')).render(React.createElement(App));
    `:undefined,
  }]});await server.listen();
  const origin='http://127.0.0.1:'+(server.httpServer!.address() as {port:number}).port,executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].find(existsSync);assert.ok(executablePath);
  const browser=await chromium.launch({executablePath,headless:true});
  const ready=()=>{const button=document.querySelector<HTMLButtonElement>('.rhwp-action-hwp');return Boolean(button&&!button.disabled);};
  try{for(const plan of cases){
    const {format}=plan,original=sources[plan.id],originalHash=hash(original),before=new Engine(original),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[];
    page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());
    try{
      assert.equal(before.pageCount(),plan.pages);const runs=JSON.parse(before.getPageTextLayout(plan.page)).runs,matches=runs.filter((run:any)=>plan.id==='017'?run.secIdx===0&&run.parentParaIdx===46&&run.controlIdx===0&&run.cellIdx===1&&run.cellParaIdx===0&&run.charStart===0:run.text==='자료 목록');assert.equal(matches.length,1);const glyph=matches[0];assert.equal(glyph.cellPath.length,1);
      console.log('CF194 '+plan.id+' baseline start');
      const readCells=(doc:any,baseline?:any[])=>JSON.parse(doc.getCursorModel()).lists.filter((list:any)=>list.isCell).map((cell:any)=>{assert.equal(cell.hostListId,0,'This explicit whole-cell probe excludes nested tables');const paths=Array.from({length:cell.paraCount},(_,cellParaIndex)=>JSON.stringify([{controlIndex:cell.controlIndex,cellIndex:cell.cellIndex,cellParaIndex}])),texts=paths.map(path=>doc.getTextInCellByPath(cell.sectionIndex,cell.hostPara,path,0,doc.getCellParagraphLengthByPath(cell.sectionIndex,cell.hostPara,path))),prior=baseline?.find(value=>value.sectionIndex===cell.sectionIndex&&value.hostPara===cell.hostPara&&value.controlIndex===cell.controlIndex&&value.cellIndex===cell.cellIndex);return{...cell,properties:JSON.parse(doc.getCellProperties(cell.sectionIndex,cell.hostPara,cell.controlIndex,cell.cellIndex)),paraProperties:paths.map((_,para)=>JSON.parse(doc.getCellParaPropertiesAt(cell.sectionIndex,cell.hostPara,cell.controlIndex,cell.cellIndex,para))),charShapes:paths.map((path,index)=>JSON.parse(doc.getCharShapeRunsInCellByPath(cell.sectionIndex,cell.hostPara,path,0,[...(prior?.texts[index]??texts[index])].length))),texts};});
      const originalCells=readCells(before),target=originalCells.findIndex((cell:any)=>cell.sectionIndex===glyph.secIdx&&cell.hostPara===glyph.parentParaIdx&&cell.controlIndex===glyph.controlIdx&&cell.cellIndex===glyph.cellIdx);assert.ok(target>=0);assert.equal(originalCells[target].paraCount,1);
      if(plan.id!=='017'){assert.equal(originalCells.length,5);assert.equal(originalCells.filter((cell:any)=>cell.rowSpan===2).length,1);assert.equal(originalCells[target].col,1);}
      const rootText=(doc:any)=>Array.from({length:doc.getSectionCount()},(_,section)=>Array.from({length:doc.getParagraphCount(section)},(_,para)=>doc.getTextRange(section,para,0,doc.getParagraphLength(section,para))));
      const originalRoot=rootText(before),nonText=(doc:any)=>hash(canonicalCellClips(doc.renderPageSvgWithProfile(plan.page,'print').replace(/<text\b[^>]*>[\s\S]*?<\/text>/gu,'').replace(/>\s+</gu,'><'))),originalDrawing=nonText(before);
      const originalLength=[...originalCells[target].texts[0]].length;
      const originalGlyphs=(doc:any)=>JSON.parse(doc.getPageTextLayout(plan.page)).runs.flatMap((run:any)=>{assert.ok(Array.isArray(run.charX)&&run.charX.length===[...run.text].length+1,'Glyph coordinates are required');const {text,charX,x,w,charStart,...style}=run;return[...text].flatMap((value,index)=>{const offset=charStart+index;if(run.secIdx===glyph.secIdx&&run.parentParaIdx===glyph.parentParaIdx&&run.controlIdx===glyph.controlIdx&&run.cellIdx===glyph.cellIdx&&run.cellParaIdx===glyph.cellParaIdx&&offset>=originalLength)return[];return[{value,offset,x:x+charX[index],style}];});}),originalGlyphHash=hash(JSON.stringify(originalGlyphs(before)));
      const originalPages=Array.from({length:plan.pages},(_,p)=>hash(before.renderPageSvgWithProfile(p,'print'))),originalArchive=unzipSync(before.exportHwpx());assert.ok(Object.keys(originalArchive).filter(name=>name.startsWith('BinData/')).length>0,'The source must actually contain a preserved image');
      const offset=[...glyph.text].length-1,cursor=JSON.parse(before.getCursorRectByPath(glyph.secIdx,glyph.parentParaIdx,JSON.stringify(glyph.cellPath),offset));assert.equal(cursor.pageIndex,plan.page);assert.ok(cursor.height>0&&Number.isFinite(cursor.x)&&Number.isFinite(cursor.y));assert.ok(Math.abs(cursor.x-(glyph.x+glyph.charX[offset]))<1);assert.ok(cursor.y<glyph.y+glyph.h&&glyph.y<cursor.y+cursor.height,'The glyph and caret must occupy the same visible line');
      const {width,height}=JSON.parse(before.getPageInfo(plan.page));assert.ok(width>0&&height>width);const size=/viewBox="0 0 ([\d.]+) ([\d.]+)"/u.exec(before.renderPageSvgWithProfile(plan.page,'print'));assert.ok(size&&Math.abs(width-Number(size[1]))<0.1&&Math.abs(height-Number(size[2]))<0.1,'Screen and print page sizes must agree');console.log('CF194 '+plan.id+' baseline ready');
      await page.goto(origin+'/table-qa.html?format='+format+'&source='+plan.id);await page.waitForFunction(ready);const frame=page.frameLocator('.rhwp-dialog iframe');
      if(plan.page){await frame.locator('#sb-page').click();const goto=frame.locator('.goto-dialog-body input[type="number"]');await goto.fill(String(plan.page+1));await goto.press('Enter');await goto.waitFor({state:'hidden'});}
      const canvases=frame.locator('#scroll-content .document-page-canvas');await canvases.first().waitFor();
      const selected=frame.locator(`#scroll-content .document-page-canvas[data-rhwp-surface-cache-lookup-key*="|page:${plan.page}|"]`);await selected.waitFor();assert.equal(await selected.count(),1);const box=await selected.boundingBox();assert.ok(box&&box.width>0&&box.height>0);
      // Only public DOM pointer/keyboard input. The point comes from the actual source glyph and page canvas.
      await selected.click({position:{x:(cursor.x+1)*box.width/width,y:(cursor.y+cursor.height/2)*box.height/height}});
      assert.equal(await frame.locator('textarea[aria-label="문서 편집 입력"]').evaluate(el=>el===document.activeElement),true,'A genuine glyph click must focus native editing');await frame.locator('.caret').waitFor({state:'visible'});await page.keyboard.press('End');await page.keyboard.type(' QA',{delay:30});
      const download=async(label:string)=>{const promise=page.waitForEvent('download');await page.getByRole('button',{name:format.toUpperCase()+' 다운로드만',exact:true}).click();const file=await promise,location=await file.path();assert.ok(location);const data=new Uint8Array(readFileSync(location));const doc=new Engine(data);try{same(rootText(doc),originalRoot,`The ${label} export changed root-body text`);return{cells:readCells(doc,originalCells),pages:Array.from({length:doc.pageCount()},(_,p)=>hash(doc.renderPageSvgWithProfile(p,'print')))};}finally{doc.free();}};
      const edited=await download('edited');same(edited.cells[target].texts,[originalCells[target].texts[0]+' QA'],'Only the selected title cell must acquire the keyboard text');assert.equal(await page.evaluate(()=>(window as any).cf194.applies.length),0);
      if(process.env.CF194_OUTPUT_ROOT&&plan.id==='hwp')await page.screenshot({path:resolve(process.env.CF194_OUTPUT_ROOT,'native-table-edited-1440.png')});
      await frame.locator('textarea[aria-label="문서 편집 입력"]').focus();await page.keyboard.press('Control+z');const undone=await download('undo');same(undone.cells,originalCells,'Undo must restore all cells');same(undone.pages,originalPages,'Undo must restore all print pages');
      await frame.locator('textarea[aria-label="문서 편집 입력"]').focus();await page.keyboard.press('Control+y');const redone=await download('redo');same(redone.cells,edited.cells,'Redo must restore the edited cells');same(redone.pages,edited.pages,'Redo must restore all edited pages');assert.equal(await page.evaluate(()=>(window as any).cf194.applies.length),0);
      if(plan.id==='hwp'){
        const apply=page.getByRole('button',{name:'표 작업본 검수 적용',exact:true});assert.equal(await apply.isDisabled(),false);assert.equal(await page.getByRole('alert').count(),0);
        await apply.evaluate(button=>{(button as HTMLButtonElement).click();(window as any).cf194.setDisabled(true);});await page.getByRole('alert').filter({hasText:/문서 또는 저장 권한·상태가 바뀌어/u}).waitFor();assert.equal(await apply.isDisabled(),true);assert.equal(saveRequests.get(plan.id)??0,0);same(await page.evaluate(()=>({applies:(window as any).cf194.applies.length,attempts:(window as any).cf194.attempts,saved:(window as any).cf194.saved})),{applies:0,attempts:0,saved:null},'Revoking permission must stop an actually started operation before any handoff');
        await page.evaluate(()=>(window as any).cf194.setDisabled(false));await page.waitForFunction(ready);failNextSave=true;await apply.click();await page.getByRole('alert').filter({hasText:'Local QA save failed'}).waitFor();assert.equal(saveRequests.get(plan.id),1);assert.equal(failedSaves,1);assert.equal(savedFiles.has(plan.id),false);same(await page.evaluate(()=>({applies:(window as any).cf194.applies.length,attempts:(window as any).cf194.attempts,saved:(window as any).cf194.saved})),{applies:0,attempts:1,saved:null},'A real 503 must leave the local draft unchanged');assert.equal(await page.getByRole('dialog').isVisible(),true);same((await download('failed-save')).cells,redone.cells,'A failed save must retain editable text');
      }
      await page.getByRole('button',{name:'표 작업본 검수 적용',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(saveRequests.get(plan.id),plan.id==='hwp'?2:1,'Double clicks must not duplicate the native save');
      const applies=await page.evaluate(()=>(window as any).cf194.applies);assert.equal(applies.length,1);const applied=applies[0];assert.equal(applied.originalHash,originalHash);assert.equal(applied.originalName,'비공개 표 검수.'+format);assert.ok(applied.name.endsWith('.'+format));assert.equal(applied.pageHashes.length,plan.pages);
      same(applied.pageHashes,redone.pages,'The whole callback must describe the actual edited source');const savedBytes=savedFiles.get(plan.id);assert.ok(savedBytes);assert.equal(hash(savedBytes),applied.editedHash);
      const saved=new Engine(savedBytes);try{
        assert.equal(saved.getSourceFormat(),format);const cells=readCells(saved,originalCells);same(cells[target].texts,[originalCells[target].texts[0]+' QA'],'The applied title cell must retain the keyboard text');same(cells.map((cell:any)=>({...cell,texts:undefined})),originalCells.map((cell:any)=>({...cell,texts:undefined})),'All original cell geometry and structure must remain');
        same(rootText(saved),originalRoot,'The applied source changed root-body text');assert.equal(nonText(saved),originalDrawing,'Table borders or target-page images changed');same(saved.getControls(),before.getControls(),'Original control chains changed');same(saved.getFieldList(),before.getFieldList(),'Original fields changed');
        assert.ok(hash(JSON.stringify(originalGlyphs(saved)))===originalGlyphHash,'An original target-page glyph moved or changed its format');
        for(let index=0;index<cells.length;index++)if(index!==target)same(cells[index].texts,originalCells[index].texts,'A non-target cell changed');
        if(plan.id!=='017')assert.match(saved.getTextFileText(),/123,456원/u);
        for(let p=0;p<plan.pages;p++){const current=hash(saved.renderPageSvgWithProfile(p,'print'));assert.ok(current===applied.pageHashes[p],`Callback/native page ${p+1} mismatch`);if(p!==plan.page)assert.ok(current===originalPages[p],`Unedited page ${p+1} changed`);}
        const savedArchive=unzipSync(saved.exportHwpx());assert.deepEqual(Object.keys(savedArchive).filter(name=>name.startsWith('BinData/')).sort(),Object.keys(originalArchive).filter(name=>name.startsWith('BinData/')).sort());for(const[name,value]of Object.entries(originalArchive)){if(name.startsWith('BinData/')||(/^Contents\/section\d+\.xml$/u.test(name)&&name!==`Contents/section${glyph.secIdx}.xml`)||name==='Contents/header.xml')assert.ok(hash(savedArchive[name])===hash(value),'Untouched native archive changed');}
        const exported=exportNativeWithReport(saved,format);assert.equal(exported.report.count,0);assert.equal(exported.report.lossRecords,0);const second=new Engine(exported.bytes);try{same(readCells(second,originalCells),cells,'A second native save changed the cells');for(let p=0;p<plan.pages;p++)assert.ok(hash(second.renderPageSvgWithProfile(p,'print'))===applied.pageHashes[p],`Second native reopen page ${p+1} mismatch`);}finally{second.free();}
      }finally{saved.free();}
      await page.getByRole('button',{name:'저장한 표 작업본 재열기',exact:true}).click();await page.waitForFunction(ready);const reopened=await download('reopened');same(reopened.cells,redone.cells,'The new SDK instance must retain the saved cells');same(reopened.pages,applied.pageHashes,'The new SDK instance must retain all print pages');assert.equal(await page.evaluate(()=>(window as any).cf194.applies.length),1);
      assert.equal(hash(original),originalHash);if(plan.id==='017')assert.equal(hash(readFileSync(actualSource!)),originalHash);assert.deepEqual(errors,[]);results.push({id:plan.id,provenance:plan.id==='017'?'Actual TPL-REF-017 private memory clone':'Synthetic native document',format,pages:plan.pages,sourceSha256:originalHash,savedSha256:applied.editedHash,cellCount:originalCells.length,binDataCount:Object.keys(originalArchive).filter(name=>name.startsWith('BinData/')).length,unmodifiedPagesExact:plan.pages-1,originalGlyphsAndCellPropertiesPreserved:true,undoOriginalPagesExact:true,redoAndCallbackPagesExact:true,newSdkReopenExact:true,originalUnchanged:true,successfulLocalSaves:1,permissionRevocation:plan.id==='hwp'?'ACTUAL_OPERATION_ABORTED_BEFORE_HANDOFF':'Covered by shared handler synthetic HWP',failedLocalSave:plan.id==='hwp'?'ACTUAL_POST_503_DRAFT_UNCHANGED':'Covered by shared handler synthetic HWP',firstSdkContentLossReport:'UNAVAILABLE; separate original structure/text/picture/page checks performed',secondNativeExportReport:{count:0,lossRecords:0}});console.log('CF194 '+plan.id+' actual table input/Undo/Redo/apply/reopen PASS');
    }finally{before.free();await page.close();}
  }if(output)writeFileSync(resolve(output,'native-table-result.json'),JSON.stringify({scope:'Local actual approved SDK plus same-parser native preservation; not PC Hancom, live D1/Drive save or A-Z acceptance',engineSha256:approved.engineSha256,bindingSha256:approved.bindingSha256,results},null,2),{flag:'wx'});}finally{await browser.close();await server.close();}
});
