import assert from 'node:assert/strict';
import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import test from 'node:test';
import {chromium,type Page} from 'playwright-core';
import {WORKFORCE_ALLOCATION_OPTIONS} from '../apps/web/src/workflow/workflow-model';

test('CF197 real allocation UI preserves PERSON batch, TEAM, retries, authority and current drafts',async t=>{
  const output=process.env.CF197_OUTPUT_ROOT,baseline=process.env.CF197_BASELINE_UI==='1',staleReadNegative=process.env.CF197_STALE_READ_NEGATIVE==='1',results:string[]=[];assert.equal(baseline&&staleReadNegative,false);if(output){mkdirSync(output,{recursive:true});assert.equal(existsSync(resolve(output,'allocation-ui-result.json')),false,'Preserve prior results');}
  const repo=process.cwd(),component=fileURLToPath(new URL('../apps/web/src/workflow/WorkflowOperations.tsx',import.meta.url)).replaceAll('\\','/');let old=baseline?execFileSync('git',['-c','safe.directory='+repo.replaceAll('\\','/'),'show','HEAD:apps/web/src/workflow/WorkflowOperations.tsx'],{encoding:'utf8'}):null;
  if(staleReadNegative){const source=readFileSync(component,'utf8'),epoch='const generation = ++routeLoadGeneration.current;';assert.equal(source.split(epoch).length,2);old=source.replace(epoch,'const generation = routeLoadGeneration.current;');}
  const indexStyle=readFileSync(resolve('apps/web/index.html'),'utf8').match(/<style>([\s\S]*?)<\/style>/)?.[1];assert.ok(indexStyle,'Use the actual production shell styles');
  const {createServer}=await import('../apps/web/qa/vite-server.js');
  const server=await createServer({root:resolve('apps/web'),...(process.env.CF149_CACHE_ROOT?{cacheDir:process.env.CF149_CACHE_ROOT}:{}),server:{host:'127.0.0.1',port:0,hmr:false},logLevel:'error',plugins:[{name:'cf197-allocation',enforce:'pre',
    configureServer(server){server.middlewares.use(async(req,res,next)=>{if(!req.url?.startsWith('/allocation-qa.html'))return next();res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml(req.url,'<!doctype html><html lang="ko" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+indexStyle+'</style><script>window.__CLAIM_API_ORIGIN__=location.origin</script></head><body><div id="root"></div><script type="module" src="/allocation-entry.js"></script></body></html>'));});},
    resolveId:id=>id==='/allocation-entry.js'?'\0allocation-entry':undefined,
    load:id=>old&&id.replaceAll('\\','/').split('?')[0].toLowerCase()===component.toLowerCase()?old:id==='\0allocation-entry'?`
      import React from'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{WorkflowOperations}from'/src/workflow/WorkflowOperations.tsx';import{WORKFORCE_ALLOCATION_OPTIONS as units}from'/src/workflow/workflow-model.ts';import{requestNavigation}from'/src/navigation-guard.ts';import'/src/workflow/WorkflowOperations.css';import'/src/preview-theme.css';import'/src/theme-system.css';
      const ids=['19700000-0000-4000-8000-000000000001','19700000-0000-4000-8000-000000000002'],cases=ids.map((id,i)=>({id,caseNumber:'CF197-'+i,title:'합성 투입 검수 '+i,claimType:'TYPE-01',status:'CONTRACT',version:1})),root=createRoot(document.getElementById('root'));
      const state={mode:'success',requests:[],schedulePuts:0,rows:[[],[]],batches:new Map(),roles:['admin'],key:0,current:0,holdSchedule:false,holdPost:false,releaseSchedule:null,releasePost:null,holdReads:false,pendingReads:[],completedReads:0,gets:0};window.cf197=state;
      const dates=ids.map(()=>({startDate:'2030-10-01',endDate:'2030-10-02',status:'PLANNED',noteText:'합성 일정',version:1}));
      state.changeDates=(i,startDate,endDate)=>Object.assign(dates[i],{startDate,endDate});
      const payload=i=>({case:cases[i],kickoff:null,siteSurveys:[],allocations:state.rows[i],events:[],googleDrive:{connected:true,deferredByUser:false,uploadEnabled:true}});
      const schedules=()=>({projects:ids.map((id,i)=>({id:'project-'+id,caseId:id,responsiblePm:{id:'pm-'+i,name:'합성 PM'},canManageSchedule:state.roles.includes('admin'),stages:[{stageCode:'TAKEOFF_COST',...dates[i],scheduleStatus:dates[i].status,scheduleNote:dates[i].noteText,scheduleVersion:dates[i].version,scheduleExplicit:true}]}))});
      const original=window.fetch.bind(window),json=(data,status=200)=>Response.json(data,{status});
      window.fetch=async(input,init={})=>{const url=new URL(typeof input==='string'?input:input.url,location.origin),path=url.pathname,method=init.method||'GET';if(!path.startsWith('/api/'))return original(input,init);
        if(path==='/api/cases')return json({cases});
        if(path==='/api/project-workflow/schedule'){const value=schedules();if(state.holdReads)return new Promise(resolve=>state.pendingReads.push(()=>{state.completedReads++;resolve(json(value));}));return json(value);}
        const i=path.includes(ids[1])?1:0;
        if(path.endsWith('/workflow')){state.gets++;const value=payload(i);if(state.holdReads)return new Promise(resolve=>state.pendingReads.push(()=>{state.completedReads++;resolve(json(value));}));return json(value);}
        if(method==='PUT'&&path.includes('/stages/')){state.schedulePuts++;const body=JSON.parse(init.body);if(state.holdSchedule)await new Promise(resolve=>state.releaseSchedule=resolve);if(state.mode==='schedule-failure')return json({error:'합성 일정 저장 실패'},503);dates[i]={...body,version:dates[i].version+1};return json({schedule:dates[i]});}
        if(method==='POST'&&(path.endsWith('/allocations-bulk')||path.endsWith('/allocations'))){const body=JSON.parse(init.body),key=new Headers(init.headers).get('Idempotency-Key');state.requests.push({caseId:ids[i],path,key,body});if(state.holdPost)await new Promise(resolve=>state.releasePost=resolve);if(state.mode==='post-failure')return json({error:'합성 투입 저장 실패'},503);if(state.mode==='invalid-json')return new Response('not json',{headers:{'Content-Type':'application/json'}});
          const unit=units.find(unit=>unit.key===body.unitKey),person=path.endsWith('/allocations-bulk'),members=person?unit.members.filter(member=>body.memberNames.includes(member)):[null],savedKey=ids[i]+':'+key,prior=state.batches.get(savedKey),rows=prior??members.map(member=>({id:crypto.randomUUID(),unitKey:body.unitKey,unitLabel:person?unit.unit+' · '+member:body.unitLabel,office:unit.organization,schedulingMode:unit.schedulingMode,discipline:unit.disciplineCode,scopeText:body.scopeText.trim(),basisText:body.basisText.trim(),startDate:body.startDate,endDate:body.endDate,leadMemberName:person?body.leadMemberName:null,createdAt:'2030-10-01',createdByName:'합성 관리자'})),value={...payload(i),allocations:[...state.rows[i],...(prior?[]:rows)],allocationBatch:{count:rows.length,ids:rows.map(row=>row.id),replayed:Boolean(prior),requestKey:key}};
          if(state.mode==='duplicate-member'){value.allocations=value.allocations.map(row=>({...row,unitLabel:rows[0].unitLabel}));return json(value);}if(state.mode==='wrong-fields'){value.allocations=value.allocations.map(row=>({...row,scopeText:'다른 원고',leadMemberName:'다른 PM'}));return json(value);}if(state.mode==='wrong-key'){value.allocationBatch.requestKey='wrong-request';return json(value);}if(state.mode==='empty-team')return json({...value,allocations:[]});
          if(!prior){state.rows[i].push(...rows);state.batches.set(savedKey,rows);}return json({...payload(i),allocationBatch:value.allocationBatch});}
        if(path.endsWith('/evidence'))return json({files:[],googleDriveConnected:true,storagePolicy:'GOOGLE_DRIVE_REQUIRED'});return json({});
      };
      state.mount=(i=0,roles=state.roles,fresh=true)=>{state.current=i;state.roles=roles;if(fresh)state.key++;history.replaceState({},'',location.pathname+'?caseId='+ids[i]);flushSync(()=>root.render(React.createElement(WorkflowOperations,{key:state.key,routeId:'WF-05',roles,onNavigate:()=>{}})));};state.navigate=()=>requestNavigation('/other',()=>{});state.mount();
    `:undefined}]});await server.listen();
  const origin='http://127.0.0.1:'+(server.httpServer!.address() as {port:number}).port,executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].find(existsSync);assert.ok(executablePath);const browser=await chromium.launch({executablePath,headless:true});
  const unit=WORKFORCE_ALLOCATION_OPTIONS[0],members=unit.members!.slice(0,2);
  const prepare=async(page:Page)=>{await page.goto(origin+'/allocation-qa.html');const editor=page.locator('.workflow-editor-card').filter({has:page.getByRole('heading',{name:'산출 범위·팀 투입 일정',exact:true})});await editor.getByLabel('산출 범위').waitFor();await editor.getByLabel('산출 범위').fill('  합성 일괄 산출 범위  ');await editor.getByLabel('산출 기준').fill(' 합성 기준 ');await editor.getByLabel('시작일',{exact:true}).fill('2030-10-01');await editor.getByLabel('종료일',{exact:true}).fill('2030-10-02');return editor;};
  const selectTwo=async(page:Page)=>{for(const member of members)await page.getByRole('checkbox',{name:member,exact:true}).check();};
  const scenario=async(name:string,work:(page:Page)=>Promise<void>)=>t.test(name,async()=>{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[];page.setDefaultTimeout(10000);page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());try{await work(page);assert.deepEqual(errors,[]);results.push(name);}finally{await page.close();}});
  try{
    await scenario('PERSON native checkbox/keyboard selects N, one POST, saved rows and remount preserve the exact batch',async page=>{
      const editor=await prepare(page);assert.equal(await page.getByRole('checkbox').count(),unit.members!.length);assert.equal(await editor.getByRole('button',{name:/투입.*저장/}).isDisabled(),true);
      const lead=unit.members![2];await editor.getByLabel('산출 및 내역 PM').selectOption(lead);const first=page.getByRole('checkbox',{name:members[0],exact:true});await first.focus();await page.keyboard.press('Space');await page.getByRole('checkbox',{name:members[1],exact:true}).check();assert.equal(await first.isChecked(),true);assert.equal(await editor.getByLabel('산출 및 내역 PM').inputValue(),lead);await page.getByRole('group',{name:'투입 인원 · 여러 명 선택',exact:true}).getByRole('status').filter({hasText:'2명 선택'}).waitFor();
      if(output&&!staleReadNegative)for(const width of [1440,390]){await page.setViewportSize({width,height:1000});const group=page.getByRole('group',{name:'투입 인원 · 여러 명 선택',exact:true});await group.scrollIntoViewIfNeeded();assert.equal(await group.evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);assert.ok(await group.locator('label').evaluateAll(labels=>labels.every(label=>label.getBoundingClientRect().height>=44)));await page.screenshot({path:resolve(output,'allocation-selected-'+width+'.png')});}await page.setViewportSize({width:1440,height:1000});
      await editor.getByRole('button',{name:'선택 2명 투입 일정 일괄 저장',exact:true}).click();await page.getByRole('status').filter({hasText:'2명 투입 기록 저장 완료'}).waitFor();assert.equal(await page.locator('.allocation-list > section').count(),2);const calls=await page.evaluate(()=>(window as any).cf197.requests);assert.equal(calls.length,1);assert.deepEqual(calls[0].body.memberNames,members);assert.equal(calls[0].body.leadMemberName,lead);assert.ok(calls[0].path.endsWith('/allocations-bulk'));
      await page.evaluate(()=>(window as any).cf197.mount());await page.locator('.allocation-list > section').last().waitFor();assert.equal(await page.locator('.allocation-list > section').count(),2);assert.ok((await page.locator('.allocation-list').innerText()).includes('합성 일괄 산출 범위'));assert.equal(await page.evaluate(()=>(window as any).cf197.requests.length),1);
    });
    if(!baseline){
      await scenario('TEAM needs no personal PM, stores one legacy row, and organization changes clear former selections',async page=>{const editor=await prepare(page);await selectTwo(page);await editor.getByLabel('투입 조직').selectOption(WORKFORCE_ALLOCATION_OPTIONS[1].key);assert.equal(await page.getByRole('checkbox').evaluateAll(items=>items.filter(item=>(item as HTMLInputElement).checked).length),0);const team=WORKFORCE_ALLOCATION_OPTIONS.find(unit=>unit.schedulingMode==='TEAM')!;await editor.getByLabel('투입 조직').selectOption(team.key);assert.equal(await page.getByRole('checkbox').count(),0);assert.equal(await editor.getByLabel('산출 및 내역 PM').count(),0);await editor.getByRole('button',{name:'팀 투입 일정 저장·프로젝트 일정표 반영',exact:true}).click();await page.getByRole('status').filter({hasText:'팀 투입 기록 1건 저장 완료'}).waitFor();assert.equal(await page.locator('.allocation-list > section').count(),1);const calls=await page.evaluate(()=>(window as any).cf197.requests);assert.equal(calls.length,1);assert.ok(calls[0].path.endsWith('/allocations'));assert.equal(calls[0].body.unitLabel,team.unit);});
      await scenario('same-turn clicks are locked; schedule failure posts nothing; POST failure preserves exact draft and retry key',async page=>{const editor=await prepare(page);await selectTwo(page);await page.evaluate(()=>{(window as any).cf197.mode='schedule-failure';});const button=editor.locator('button.workflow-form-save-button');await button.click();await page.getByRole('alert').filter({hasText:'합성 일정 저장 실패'}).waitFor();assert.equal(await page.evaluate(()=>(window as any).cf197.requests.length),0);const puts=await page.evaluate(()=>(window as any).cf197.schedulePuts);
        await page.evaluate(()=>{Object.assign((window as any).cf197,{mode:'post-failure',holdSchedule:true});});await button.evaluate(element=>{(element as HTMLButtonElement).click();(element as HTMLButtonElement).click();});await page.waitForFunction(()=>typeof (window as any).cf197.releaseSchedule==='function');assert.equal(await button.isDisabled(),true);assert.equal(await page.evaluate(()=>(window as any).cf197.schedulePuts),puts+1);await page.evaluate(()=>{(window as any).cf197.holdSchedule=false;(window as any).cf197.releaseSchedule();});await page.getByRole('alert').filter({hasText:'기준 일정은 저장됐지만 투입 기록 저장·확인은 완료되지 않았습니다'}).waitFor();assert.equal(await page.evaluate(()=>(window as any).cf197.requests.length),1);assert.equal(await editor.getByLabel('산출 범위').inputValue(),'  합성 일괄 산출 범위  ');for(const member of members)assert.equal(await page.getByRole('checkbox',{name:member,exact:true}).isChecked(),true);
        await page.evaluate(()=>(window as any).cf197.mode='success');await button.click();await page.getByRole('status').filter({hasText:'2명 투입 기록 저장 완료'}).waitFor();const calls=await page.evaluate(()=>(window as any).cf197.requests);assert.equal(calls.length,2);assert.equal(calls[0].key,calls[1].key);assert.deepEqual(calls[0].body,calls[1].body);assert.equal(await page.locator('.allocation-list > section').count(),2);
      });
      for(const mode of ['duplicate-member','wrong-fields','wrong-key','invalid-json'])await scenario('unconfirmed '+mode+' ACK never clears the draft or reports success',async page=>{const editor=await prepare(page);await selectTwo(page);await page.evaluate(mode=>(window as any).cf197.mode=mode,mode);await editor.getByRole('button',{name:'선택 2명 투입 일정 일괄 저장',exact:true}).click();await page.getByRole('alert').filter({hasText:'같은 요청'}).waitFor();assert.equal(await page.getByRole('status').filter({hasText:'투입 기록 저장 완료'}).count(),0);assert.equal(await page.locator('.allocation-list > section').count(),0);for(const member of members)assert.equal(await page.getByRole('checkbox',{name:member,exact:true}).isChecked(),true);page.once('dialog',dialog=>dialog.dismiss());const blocked=await page.evaluate(()=>(window as any).cf197.navigate());assert.equal(blocked,true);});
      await scenario('TEAM empty ACK cannot report one saved row',async page=>{const editor=await prepare(page);await editor.getByLabel('투입 조직').selectOption(WORKFORCE_ALLOCATION_OPTIONS.find(unit=>unit.schedulingMode==='TEAM')!.key);await page.evaluate(()=>(window as any).cf197.mode='empty-team');await editor.getByRole('button',{name:'팀 투입 일정 저장·프로젝트 일정표 반영',exact:true}).click();await page.getByRole('alert').filter({hasText:'저장 결과가 입력과 다릅니다'}).waitFor();assert.equal(await page.getByRole('status').filter({hasText:'1건 저장 완료'}).count(),0);});
      await scenario('authority revoked during schedule save aborts POST and staff cannot allocate',async page=>{const editor=await prepare(page);await selectTwo(page);await page.evaluate(()=>(window as any).cf197.holdSchedule=true);await editor.getByRole('button',{name:'선택 2명 투입 일정 일괄 저장',exact:true}).click();await page.waitForFunction(()=>typeof (window as any).cf197.releaseSchedule==='function');await page.evaluate(()=>{const state=(window as any).cf197;state.mount(0,['staff'],false);state.holdSchedule=false;state.releaseSchedule();});await page.getByRole('alert').filter({hasText:'저장 권한이 바뀌어'}).waitFor();assert.equal(await page.evaluate(()=>(window as any).cf197.requests.length),0);assert.equal(await editor.getByRole('button',{name:'선택 2명 투입 일정 일괄 저장',exact:true}).isDisabled(),true);});
      await scenario('accepted native case switch discards old selections and unsaved scope without a POST',async page=>{const editor=await prepare(page);await selectTwo(page);page.once('dialog',dialog=>dialog.accept());await page.locator('#workflow-case').selectOption('19700000-0000-4000-8000-000000000002');await page.waitForFunction(()=>document.querySelector<HTMLSelectElement>('#workflow-case')?.value==='19700000-0000-4000-8000-000000000002');await editor.getByLabel('산출 범위').waitFor();assert.equal(await editor.getByLabel('산출 범위').inputValue(),'');assert.equal(await page.getByRole('checkbox').evaluateAll(items=>items.filter(item=>(item as HTMLInputElement).checked).length),0);assert.equal(await page.evaluate(()=>(window as any).cf197.requests.length),0);});
      await scenario('discarded case draft and late previous response cannot enter the new case',async page=>{const editor=await prepare(page);await selectTwo(page);page.once('dialog',dialog=>dialog.dismiss());await page.locator('#workflow-case').selectOption('19700000-0000-4000-8000-000000000002');assert.equal(await page.locator('#workflow-case').inputValue(),'19700000-0000-4000-8000-000000000001');for(const member of members)assert.equal(await page.getByRole('checkbox',{name:member,exact:true}).isChecked(),true);
        await page.evaluate(()=>(window as any).cf197.holdPost=true);await editor.getByRole('button',{name:'선택 2명 투입 일정 일괄 저장',exact:true}).click();await page.waitForFunction(()=>typeof (window as any).cf197.releasePost==='function');await page.evaluate(()=>{const state=(window as any).cf197;state.mount(1);});await editor.getByLabel('산출 범위').waitFor();await page.waitForFunction(()=>document.querySelector<HTMLSelectElement>('#workflow-case')?.value==='19700000-0000-4000-8000-000000000002');await page.evaluate(()=>{const state=(window as any).cf197;state.holdPost=false;state.releasePost();});await page.waitForFunction(()=>(window as any).cf197.rows[0].length===2);assert.equal(await page.locator('.allocation-list > section').count(),0);assert.equal(await editor.getByLabel('산출 범위').inputValue(),'');assert.equal(await page.getByRole('status').filter({hasText:'2명 투입 기록 저장 완료'}).count(),0);
      });
    }
    await scenario('A to B to A late reads cannot replace the latest A dates, selections or draft',async page=>{
      await prepare(page);await page.evaluate(()=>{const state=(window as any).cf197;state.holdReads=true;state.mount(0);});await page.waitForFunction(()=>(window as any).cf197.pendingReads.length===2);
      await page.locator('#workflow-case').selectOption('19700000-0000-4000-8000-000000000002');await page.waitForFunction(()=>(window as any).cf197.pendingReads.length===4);await page.evaluate(()=>(window as any).cf197.changeDates(0,'2030-11-03','2030-11-04'));
      await page.locator('#workflow-case').selectOption('19700000-0000-4000-8000-000000000001');await page.waitForFunction(()=>(window as any).cf197.pendingReads.length===6);await page.evaluate(()=>{const state=(window as any).cf197;state.pendingReads[4]();state.pendingReads[5]();});
      const editor=page.locator('.workflow-editor-card').filter({has:page.getByRole('heading',{name:'산출 범위·팀 투입 일정',exact:true})});await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('.workflow-editor-card input[type="date"]')?.value==='2030-11-03');await editor.getByLabel('산출 범위').fill('최신 A 입력 유지');await editor.getByLabel('산출 기준').fill('최신 A 기준 유지');if(!baseline)await selectTwo(page);
      await page.evaluate(async()=>{const state=(window as any).cf197;state.pendingReads.slice(0,4).forEach((release:()=>void)=>release());await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});assert.equal(await page.evaluate(()=>(window as any).cf197.completedReads),6);
      assert.equal(await editor.getByLabel('시작일',{exact:true}).inputValue(),'2030-11-03');assert.equal(await editor.getByLabel('종료일',{exact:true}).inputValue(),'2030-11-04');assert.equal(await editor.getByLabel('산출 범위').inputValue(),'최신 A 입력 유지');assert.equal(await editor.getByLabel('산출 기준').inputValue(),'최신 A 기준 유지');if(!baseline)for(const member of members)assert.equal(await page.getByRole('checkbox',{name:member,exact:true}).isChecked(),true);assert.equal(await page.locator('#workflow-case').inputValue(),'19700000-0000-4000-8000-000000000001');assert.equal(await page.evaluate(()=>(window as any).cf197.requests.length),0);
    });
    const expectedScenarios=baseline?2:12;if(output)writeFileSync(resolve(output,'allocation-ui-result.json'),JSON.stringify({scope:'Actual localhost React; API mock UI evidence separate from Worker SQL tests; no employee or server writes',baseline,staleReadNegative,pass:results.length===expectedScenarios,expectedScenarios,passedScenarios:results.length,results},null,2),{flag:'wx'});
  }finally{await browser.close();await server.close();}
});
