import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import test from 'node:test';
import {chromium} from 'playwright-core';
import {unzipSync} from '../apps/web/node_modules/fflate';
import {createNativeHwp} from '../apps/web/src/documents/editable-hwp-export';
import {readQaNativeEngine,exportNativeWithReport,matchReferenceSources,assertQaOutputOutsideSources} from './cf183-template-source-gate.mjs';

const hash=(value:Uint8Array|string)=>createHash('sha256').update(value).digest('hex');
const same=(actual:unknown,expected:unknown,message:string)=>assert.ok(hash(JSON.stringify(actual))===hash(JSON.stringify(expected)),message);
type Plan={id:string;format:'hwp'|'hwpx';page:number;pages:number;fileId?:string;body?:{sec:number;para:number};cell?:{sec:number;parent:number;control:number;cell:number};targetReflow?:boolean;bodyTab?:boolean};
function expectedBodyText(original:string[][],body?:Plan['body']){const expected=structuredClone(original);if(body){assert.equal(typeof expected[body.sec]?.[body.para],'string','A body target must exist before UI editing');expected[body.sec][body.para]+=' QA';}return expected;}
function absoluteGlyphX(x:number,offset:number){for(const value of [x,offset])assert.ok(Number.isFinite(value)&&Math.abs(value*10-Math.round(value*10))<1e-6,'Approved glyph coordinates require their declared 0.1px precision');return(Math.round(x*10)+Math.round(offset*10))/10;}
function isTrailingWrapSpace(character:string,lastInRun:boolean,nextLine:boolean,underline:boolean,strikethrough:boolean){return character===' '&&lastInRun&&nextLine&&underline===false&&strikethrough===false;}
const serializedTabs=(bytes:Uint8Array)=>[...new TextDecoder().decode(bytes).matchAll(/<hp:tab\b[^>]*\/>/gu)].map(match=>match[0]);

test('CF195 soft-wrap whitespace exception cannot hide a clipped letter, interior space or painted underline',()=>{
  assert.equal(isTrailingWrapSpace(' ',true,true,false,false),true);for(const args of [['Q',true,true,false,false],[' ',false,true,false,false],[' ',true,false,false,false],[' ',true,true,true,false],[' ',true,true,false,true]] as const)assert.equal(isTrailingWrapSpace(args[0],args[1],args[2],args[3],args[4]),false);
});

test('CF195 exact decimal glyph sums remove arithmetic noise without hiding an actual coordinate change',()=>{
  assert.equal(absoluteGlyphX(184.2,5.5),189.7);assert.equal(absoluteGlyphX(189.70000000000002,0),189.7);assert.notEqual(absoluteGlyphX(184.3,5.5),189.7);assert.throws(()=>absoluteGlyphX(184.200001,5.5));
});

test('CF195 body expectations are immutable and reject absent input, another paragraph and stale cell-only output',()=>{
  const original=[['untouched','selected']],expected=expectedBodyText(original,{sec:0,para:1});same(expected,[['untouched','selected QA']],'The predetermined body must modify one literal target');same(original,[['untouched','selected']],'Building expectations must not edit the original');
  assert.throws(()=>same(original,expected,'No body input'));const wrong=structuredClone(original);wrong[0][0]+=' QA';assert.equal(wrong[0][0],'untouched QA');assert.throws(()=>same(wrong,expected,'Another paragraph input'));const cellOnly=expectedBodyText(original);same(cellOnly,original,'A cell-only stage has no body edit');assert.throws(()=>same(cellOnly,expected,'Stale cell-only export'));assert.throws(()=>expectedBodyText(original,{sec:0,para:2}));
});
function canonicalCellClips(svg:string){
  // Cell clip names use render-node ordinals, which can change when a text run is added.
  // Preserve every definition/attribute and exact reference topology; rename only proved cell clips.
  const ids=[...svg.matchAll(/<clipPath\b[^>]*\bid="(cell-clip-\d+(?:-[a-z]+)?)"/gu)].map(match=>match[1]);assert.equal(new Set(ids).size,ids.length,'Duplicate cell clip definitions');
  const names=new Map(ids.map((id,index)=>[id,id.replace(/^cell-clip-\d+/u,`CF194-cell-${index}`)]));
  for(const id of ids){assert.equal(svg.split(`id="${id}"`).length-1,1,'Cell clip must have one definition');assert.ok(svg.includes(`url(#${id})`),'Cell clip must have a live reference');}
  return svg.replace(/\b(id|clip-path)="([^"]+)"/gu,(full,key,value)=>{if(key==='id')return names.has(value)?`id="${names.get(value)}"`:full;const ref=/^url\(#(cell-clip-\d+(?:-[a-z]+)?)\)$/u.exec(value);if(!ref)return full;assert.ok(names.has(ref[1]),'Dangling cell clip reference');return `clip-path="url(#${names.get(ref[1])})"`;});
}

test('CF194 clip comparison preserves geometry and reference topology while ignoring render-node ordinals',()=>{
  const first='<svg><clipPath id="cell-clip-2"><rect x="1" width="20"/></clipPath><clipPath id="cell-clip-8"><rect x="30" width="40"/></clipPath><g clip-path="url(#cell-clip-2)"/><g clip-path="url(#cell-clip-8)"/></svg>',renamed=first.replaceAll('cell-clip-2','cell-clip-3').replaceAll('cell-clip-8','cell-clip-10');
  assert.equal(canonicalCellClips(first),canonicalCellClips(renamed));assert.notEqual(canonicalCellClips(first),canonicalCellClips(renamed.replace('width="20"','width="21"')));assert.notEqual(canonicalCellClips(first),canonicalCellClips(renamed.replace(/clip-path="url\(#(cell-clip-(?:3|10))\)"/gu,(_,id)=>`clip-path="url(#${id==='cell-clip-3'?'cell-clip-10':'cell-clip-3'})"`)));assert.notEqual(canonicalCellClips(first),canonicalCellClips(first.replaceAll('cell-clip-2','cell-clip-2-fill')));
  assert.throws(()=>canonicalCellClips(first.replace('clip-path="url(#cell-clip-8)"','clip-path="url(#cell-clip-99)"')));assert.throws(()=>canonicalCellClips(first.replace('id="cell-clip-8"','id="cell-clip-2"')));
});

test('CF194/195 actual native cell/body click, keyboard Undo/Redo, whole apply and same-format reopening',async(t)=>{
  const output=process.env.CF195_OUTPUT_ROOT??process.env.CF194_OUTPUT_ROOT,sourceRoot=process.env.CF195_SOURCE_ROOT??process.env.CF194_SOURCE_ROOT;if(output){assert.ok(existsSync(output),'Use a pre-created isolated QA output folder');assert.equal(existsSync(resolve(output,'native-table-result.json')),false,'Preserve previous QA results');if(sourceRoot)assertQaOutputOutsideSources(sourceRoot,output);}
  const results:unknown[]=[];
  const approved=readQaNativeEngine(),module=await import(pathToFileURL(resolve(approved.root,'rhwp.js')).href);
  await module.default({module_or_path:approved.wasm});const Engine=module.HwpDocument;
  const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5V8AAAAASUVORK5CYII=';
  const photo=Buffer.from(png,'base64');
  const contents=[
    {html:'<table><tr><td>Ⅰ.</td><td>자료 목록</td></tr></table><p>확정 금액 123,456원 · 보존 본문</p>',text:'Ⅰ.자료 목록확정 금액 123,456원 · 보존 본문',tables:1,tableCells:[[{row:0,col:0,rowSpan:1,colSpan:1,text:'Ⅰ.'},{row:0,col:1,rowSpan:1,colSpan:1,text:'자료 목록'}]],images:0},
    {html:`<table><tr><td rowspan="2">병합</td><td>120</td></tr><tr><td>145</td></tr></table><img src="data:image/png;base64,${png}" width="40" height="40">`,text:'병합120145',tables:1,tableCells:[[{row:0,col:0,rowSpan:2,colSpan:1,text:'병합'},{row:0,col:1,rowSpan:1,colSpan:1,text:'120'},{row:1,col:1,rowSpan:1,colSpan:1,text:'145'}]],images:1,pictures:[{bytes:photo,width:40,height:40}]},
  ].map(content=>({...content,width:794,height:1123,margins:{top:40,right:40,bottom:40,left:40}}));
  const fixture=new Engine(createNativeHwp(contents,Engine)),sources:Record<string,Uint8Array>={};
  try{for(const format of ['hwp','hwpx'] as const){const result=exportNativeWithReport(fixture,format);assert.equal(result.report.count,0);assert.equal(result.report.lossRecords,0);sources[format]=result.bytes;}}finally{fixture.free();}
  const cases:Plan[]=[{id:'hwp',format:'hwp',page:0,pages:2},{id:'hwpx',format:'hwpx',page:0,pages:2}],actualSources=new Map<string,string>();
  if(sourceRoot){const originals=matchReferenceSources(sourceRoot,JSON.parse(readFileSync('docs/templates/reference-inventory.json','utf8')));cases.push({id:'017',fileId:'TPL-REF-017',format:'hwpx',page:2,pages:47,cell:{sec:0,parent:46,control:0,cell:1}});
    if(process.env.CF195_SOURCE_ROOT)cases.push({id:'007-cell',fileId:'TPL-REF-007',format:'hwp',page:4,pages:17,cell:{sec:0,parent:123,control:0,cell:8},targetReflow:true},{id:'007-body',fileId:'TPL-REF-007',format:'hwp',page:6,pages:17,body:{sec:0,para:159}},{id:'005-body',fileId:'TPL-REF-005',format:'hwp',page:0,pages:9,body:{sec:0,para:3},bodyTab:true});
    for(const plan of cases.filter(plan=>plan.fileId)){const file=originals.find((file:any)=>file.fileId===plan.fileId);assert.ok(file&&file.extension==='.'+plan.format);actualSources.set(plan.id,file.source);sources[plan.id]=new Uint8Array(readFileSync(file.source));if(plan.format==='hwp')assert.equal(Buffer.from(sources[plan.id].slice(0,8)).toString('hex'),'d0cf11e0a1b11ae1','These actual HWP cases require HWP5 CFB, not legacy HWP3');}
  }
  const focusedCase=process.env.CF195_CASE?.trim()||undefined,selectedCases=focusedCase?cases.filter(plan=>plan.id===focusedCase):cases;if(focusedCase)assert.equal(selectedCases.length,1,'A focused diagnostic must name one existing case');
  const runtime=resolve('pinned-runtime/rhwp'),manifest=JSON.parse(readFileSync(resolve(runtime,'build-manifest.json'),'utf8'));
  const files=new Set(['index.html','build-manifest.json',...manifest.files.map((file:{path:string})=>file.path)]);
  const savedFiles=new Map<string,Uint8Array>(),saveRequests=new Map<string,number>();let failNextSave=false,failedSaves=0;
  const {createServer}=await import('../apps/web/qa/vite-server.js');
  const server=await createServer({root:resolve('apps/web'),...(process.env.CF149_CACHE_ROOT?{cacheDir:process.env.CF149_CACHE_ROOT}:{}),server:{host:'127.0.0.1',port:0,hmr:false},logLevel:'error',plugins:[{
    name:'cf194-native-table',
    configureServer(server){server.middlewares.use(async(req,res,next)=>{
      const pathname=(req.url??'').split('?')[0];
      if(pathname.startsWith('/rhwp/')){const name=pathname.slice(6)||'index.html';if(!files.has(name)){res.statusCode=404;res.end();return;}const file=resolve(runtime,name);assert.ok(file.startsWith(runtime+sep));
        res.setHeader('Content-Type',name.endsWith('.html')?'text/html':name.endsWith('.json')?'application/json':name.endsWith('.js')?'text/javascript':name.endsWith('.wasm')?'application/wasm':name.endsWith('.css')?'text/css':name.endsWith('.woff2')?'font/woff2':'application/octet-stream');res.end(readFileSync(file));return;}
      if(pathname.startsWith('/original.')){const format=pathname.slice(10);if(sources[format]){res.end(sources[format]);return;}}
      if(pathname==='/saved-native'&&req.method==='POST'){const id=new URL(req.url!,'http://localhost').searchParams.get('source');assert.ok(id&&sources[id]);saveRequests.set(id,(saveRequests.get(id)??0)+1);const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;assert.ok(size<50_000_000,'Local QA file limit');chunks.push(Buffer.from(chunk));}if(failNextSave){failNextSave=false;failedSaves++;res.statusCode=503;res.end('Synthetic QA save unavailable');return;}savedFiles.set(id,new Uint8Array(Buffer.concat(chunks)));res.end('Saved in isolated memory');return;}
      if(pathname!=='/table-qa.html')return next();res.setHeader('Content-Type','text/html');res.end(await server.transformIndexHtml(req.url!,'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="root"></div><script type="module" src="/table-entry.js"></script></body></html>'));
    });},
    resolveId:id=>id==='/table-entry.js'?'\0table-entry':undefined,
    load:id=>id==='\0table-entry'?`
      import React,{useState,useEffect}from'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{RhwpEditorDialog}from'/src/documents/RhwpEditorDialog.tsx';import'/src/documents/RhwpEditorDialog.css';
      window.__CLAIM_CENTER_RHWP_STUDIO_URL__=location.origin+'/rhwp/';window.cf194={applies:[],saved:null,attempts:0};
      function App(){const[file,setFile]=useState(null);const[open,setOpen]=useState(true);const[disabled,setDisabled]=useState(false);const format=new URLSearchParams(location.search).get('format');window.cf194.setDisabled=value=>flushSync(()=>setDisabled(value));
        useEffect(()=>{fetch('/original.'+new URLSearchParams(location.search).get('source')).then(r=>r.arrayBuffer()).then(bytes=>setFile(new File([bytes],'비공개 표 검수.'+format)));},[]);
        const hash=async data=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data))).map(n=>n.toString(16).padStart(2,'0')).join('');
        return file?React.createElement(React.Fragment,null,React.createElement('button',{onClick:()=>{setFile(window.cf194.saved);setOpen(true);}},'저장한 표 작업본 재열기'),React.createElement(RhwpEditorDialog,{isOpen:open,sourceFile:file,suggestedName:'합성 표',documentLabel:'합성 표 검수',preserveAppliedSource:true,applyDisabled:disabled,onClose:()=>setOpen(false),applyLabel:'표 작업본 검수 적용',onApplyPages:async(pages,edited,original)=>{window.cf194.attempts++;const pageHashes=[];for(const svg of pages)pageHashes.push(await hash(new TextEncoder().encode(svg)));const response=await fetch('/saved-native?source='+new URLSearchParams(location.search).get('source'),{method:'POST',body:edited});if(!response.ok)throw Error('Local QA save failed');window.cf194.applies.push({pageHashes,name:edited.name,originalName:original.name,originalHash:await hash(await original.arrayBuffer()),editedHash:await hash(await edited.arrayBuffer())});window.cf194.saved=edited;setOpen(false);}})):null;
      }createRoot(document.getElementById('root')).render(React.createElement(App));
    `:undefined,
  }]});await server.listen();
  const origin='http://127.0.0.1:'+(server.httpServer!.address() as {port:number}).port,executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].find(existsSync);assert.ok(executablePath);
  const browser=await chromium.launch({executablePath,headless:true});
  const ready=()=>{const button=document.querySelector<HTMLButtonElement>('.rhwp-action-hwp');return Boolean(button&&!button.disabled);};
  try{for(const plan of selectedCases){await t.test('actual SDK '+plan.id,async()=>{
    const {format}=plan,original=sources[plan.id],originalHash=hash(original),before=new Engine(original),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors:string[]=[];
    page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());
    try{
      assert.equal(before.pageCount(),plan.pages);assert.equal(before.getSourceFormat(),format);const isTarget=(run:any)=>plan.body?run.secIdx===plan.body.sec&&run.paraIdx===plan.body.para&&run.parentParaIdx===undefined&&run.cellPath===undefined:plan.cell?run.secIdx===plan.cell.sec&&run.parentParaIdx===plan.cell.parent&&run.controlIdx===plan.cell.control&&run.cellIdx===plan.cell.cell&&run.cellParaIdx===0:run.text==='자료 목록';
      const runs=JSON.parse(before.getPageTextLayout(plan.page)).runs,matches=runs.filter((run:any)=>isTarget(run)&&run.charStart===0);assert.equal(matches.length,1);const glyph=matches[0];if(!plan.body)assert.equal(glyph.cellPath.length,1);
      const atTarget=(run:any)=>plan.body?isTarget(run):run.secIdx===glyph.secIdx&&run.parentParaIdx===glyph.parentParaIdx&&run.controlIdx===glyph.controlIdx&&run.cellIdx===glyph.cellIdx&&run.cellParaIdx===glyph.cellParaIdx;
      console.log('CF194/195 '+plan.id+' baseline start');
      const readCells=(doc:any,baseline?:any[])=>JSON.parse(doc.getCursorModel()).lists.filter((list:any)=>list.isCell).map((cell:any)=>{assert.equal(cell.hostListId,0,'This explicit whole-cell probe excludes nested tables');const paths=Array.from({length:cell.paraCount},(_,cellParaIndex)=>JSON.stringify([{controlIndex:cell.controlIndex,cellIndex:cell.cellIndex,cellParaIndex}])),texts=paths.map(path=>doc.getTextInCellByPath(cell.sectionIndex,cell.hostPara,path,0,doc.getCellParagraphLengthByPath(cell.sectionIndex,cell.hostPara,path))),prior=baseline?.find(value=>value.sectionIndex===cell.sectionIndex&&value.hostPara===cell.hostPara&&value.controlIndex===cell.controlIndex&&value.cellIndex===cell.cellIndex);return{...cell,properties:JSON.parse(doc.getCellProperties(cell.sectionIndex,cell.hostPara,cell.controlIndex,cell.cellIndex)),paraProperties:paths.map((_,para)=>JSON.parse(doc.getCellParaPropertiesAt(cell.sectionIndex,cell.hostPara,cell.controlIndex,cell.cellIndex,para))),charShapes:paths.map((path,index)=>JSON.parse(doc.getCharShapeRunsInCellByPath(cell.sectionIndex,cell.hostPara,path,0,[...(prior?.texts[index]??texts[index])].length))),texts};});
      const originalCells=readCells(before),target=plan.body?-1:originalCells.findIndex((cell:any)=>cell.sectionIndex===glyph.secIdx&&cell.hostPara===glyph.parentParaIdx&&cell.controlIndex===glyph.controlIdx&&cell.cellIndex===glyph.cellIdx);if(!plan.body){assert.ok(target>=0);assert.equal(originalCells[target].paraCount,1);}
      if(!plan.fileId){assert.equal(originalCells.length,5);assert.equal(originalCells.filter((cell:any)=>cell.rowSpan===2).length,1);assert.equal(originalCells[target].col,1);}
      const rootText=(doc:any)=>Array.from({length:doc.getSectionCount()},(_,section)=>Array.from({length:doc.getParagraphCount(section)},(_,para)=>doc.getTextRange(section,para,0,doc.getParagraphLength(section,para))));
      const originalRoot=rootText(before),expectedRoot=expectedBodyText(originalRoot,plan.body);if(plan.body){assert.equal(JSON.parse(before.getControlTextPositions(plan.body.sec,plan.body.para)).length,0,'The selected body paragraph must be literal/control-free');assert.equal(JSON.parse(before.getFieldList()).length,0,'These selected body originals must be field-free');}
      const rootProperties=(doc:any)=>Array.from({length:doc.getSectionCount()},(_,sec)=>Array.from({length:doc.getParagraphCount(sec)},(_,para)=>({properties:JSON.parse(doc.getParaPropertiesAt(sec,para)),charShapes:JSON.parse(doc.getCharShapeRuns(sec,para,0,[...originalRoot[sec][para]].length))}))),originalRootProperties=rootProperties(before);
      const nonText=(doc:any)=>hash(canonicalCellClips(doc.renderPageSvgWithProfile(plan.page,'print').replace(/<text\b[^>]*>[\s\S]*?<\/text>/gu,'').replace(/>\s+</gu,'><'))),originalDrawing=nonText(before),originalLength=[...(plan.body?originalRoot[plan.body.sec][plan.body.para]:originalCells[target].texts[0])].length;
      assert.ok(!/[\r\n]/u.test(glyph.text));if(plan.bodyTab)assert.ok(plan.body&&glyph.text.includes('\t'),'The selected body case must genuinely preserve an existing tab');else assert.equal(glyph.text.includes('\t'),false);assert.equal([...glyph.text].length,originalLength,'End must target an entire single-line literal paragraph');
      same(glyph.text,plan.body?originalRoot[plan.body.sec][plan.body.para]:originalCells[target].texts[0],'Target glyph/source literal mismatch');
      const originalGlyphs=(doc:any)=>JSON.parse(doc.getPageTextLayout(plan.page)).runs.flatMap((run:any)=>{assert.ok(Array.isArray(run.charX)&&run.charX.length===[...run.text].length+1,'Glyph coordinates are required');const {text,charX,x,w,charStart,...style}=run;return[...text].flatMap((value,index)=>{const offset=charStart+index;if(atTarget(run)&&offset>=originalLength)return[];if(plan.targetReflow&&atTarget(run)){const{y,...unchangedStyle}=style;return[{value,offset,style:unchangedStyle}];}return[{value,offset,x:absoluteGlyphX(x,charX[index]),style}];});}),originalGlyphHash=hash(JSON.stringify(originalGlyphs(before)));
      const originalPages=Array.from({length:plan.pages},(_,p)=>hash(before.renderPageSvgWithProfile(p,'print'))),originalArchive=unzipSync(before.exportHwpx());assert.ok(Object.keys(originalArchive).filter(name=>name.startsWith('BinData/')).length>0,'The source must actually contain a preserved image');
      const originalTabCount=Object.entries(originalArchive).filter(([name])=>/^Contents\/section\d+\.xml$/u.test(name)).reduce((count,[,bytes])=>count+serializedTabs(bytes).length,0);if(plan.bodyTab)assert.ok(originalTabCount>0,'The real tab fixture must contain actual serialized tab records');
      const offset=[...glyph.text].length-1,cursor=JSON.parse(plan.body?before.getCursorRect(glyph.secIdx,glyph.paraIdx,offset):before.getCursorRectByPath(glyph.secIdx,glyph.parentParaIdx,JSON.stringify(glyph.cellPath),offset));assert.equal(cursor.pageIndex,plan.page);assert.ok(cursor.height>0&&Number.isFinite(cursor.x)&&Number.isFinite(cursor.y));assert.ok(Math.abs(cursor.x-(glyph.x+glyph.charX[offset]))<1);assert.ok(cursor.y<glyph.y+glyph.h&&glyph.y<cursor.y+cursor.height,'The glyph and caret must occupy the same visible line');
      const {width,height}=JSON.parse(before.getPageInfo(plan.page));assert.ok(width>0&&height>width);const size=/viewBox="0 0 ([\d.]+) ([\d.]+)"/u.exec(before.renderPageSvgWithProfile(plan.page,'print'));assert.ok(size&&Math.abs(width-Number(size[1]))<0.1&&Math.abs(height-Number(size[2]))<0.1,'Screen and print page sizes must agree');console.log('CF194/195 '+plan.id+' baseline ready');
      const originalClipBoxes=plan.targetReflow?[...before.renderPageSvgWithProfile(plan.page,'print').matchAll(/<clipPath\b[^>]*>[\s\S]*?<rect\b([^>]*)\/>[\s\S]*?<\/clipPath>/gu)].map(match=>Object.fromEntries(['x','y','width','height'].map(key=>[key,Number(new RegExp(key+'="([0-9.]+)"','u').exec(match[1])?.[1])]))).filter(rect=>Math.round(rect.x*10)/10===cursor.cellBounds.x&&Math.round(rect.y*10)/10===cursor.cellBounds.y&&Math.round(rect.width*10)/10===cursor.cellBounds.w&&Math.round(rect.height*10)/10===cursor.cellBounds.h):[];
      const checkTargetReflow=(doc:any)=>{if(!plan.targetReflow)return;const props=originalCells[target].paraProperties[0];assert.equal(props.alignment,'justify');assert.equal(props.lineSpacingType,'Percent');assert.equal(props.lineSpacing,160);assert.equal(originalCells[target].properties.verticalAlign,1);assert.equal(glyph.h,12);assert.ok(cursor.cellBounds&&cursor.cellOverflowed===false);assert.equal(originalClipBoxes.length,1,'The original SVG must prove one exact cell clip box');const clip=originalClipBoxes[0],bounds=cursor.cellBounds,expected=[...originalCells[target].texts[0]+' QA'],covered:Array<string|undefined>=Array(expected.length).fill(undefined),targetRuns=JSON.parse(doc.getPageTextLayout(plan.page)).runs.filter(atTarget),wrapBoundaries=new Map<number,number>();
        for(const run of targetRuns){const text=[...run.text] as string[];assert.equal(run.charX.length,text.length+1);assert.equal(run.h,glyph.h);assert.equal(run.fontSize,glyph.fontSize);assert.ok(run.y>=clip.y&&run.y+run.h<=clip.y+clip.height,'Reflowed glyph line must remain inside the full original SVG clip');for(let index=0;index<text.length;index++){const offset=run.charStart+index;assert.ok(Number.isSafeInteger(offset)&&offset>=0&&offset<expected.length&&covered[offset]===undefined,'Every source scalar must appear exactly once');covered[offset]=text[index];const left=absoluteGlyphX(run.x,run.charX[index]),right=absoluteGlyphX(run.x,run.charX[index+1]);assert.ok(left>=clip.x&&left<=clip.x+clip.width&&right>left,'Every glyph must start inside the original clip and have a positive advance');if(right>clip.x+clip.width){assert.equal(offset,originalLength,'Only the newly added separator can use this explicit wrap exception');assert.equal(isTrailingWrapSpace(text[index],index===text.length-1,targetRuns.some((next:any)=>next.charStart===offset+1&&next.y>run.y),run.underline,run.strikethrough),true,'Only unpainted trailing wrap whitespace may have a logical advance beyond its clip');wrapBoundaries.set(offset+1,run.y);}}}
        same(covered,expected,'The whole edited text must be visible, not just its original prefix');const ys=[...new Set<number>(targetRuns.map((run:any)=>run.y))].sort((a,b)=>a-b);assert.equal(ys.length,2);const step=glyph.h*props.lineSpacing/100;assert.equal(Math.round((ys[1]-ys[0])*10),Math.round(step*10));assert.equal(Math.round((ys[0]+ys[1])*5),Math.round(glyph.y*10));assert.equal(Math.round((ys[0]-glyph.y)*10),-Math.round(step*5));
        assert.equal(wrapBoundaries.size,1,'This explicit source has one retained soft-wrap separator');assert.equal(wrapBoundaries.has(originalLength+1),true);for(let offset=0;offset<=expected.length;offset++){const next=JSON.parse(doc.getCursorRectByPath(glyph.secIdx,glyph.parentParaIdx,JSON.stringify(glyph.cellPath),offset));assert.equal(next.pageIndex,plan.page);same(next.cellBounds,bounds,'The original cell bounds must not move');if(wrapBoundaries.has(offset)){assert.equal(next.cellOverflowed,true,'The source query reports its previous-line boundary correction explicitly');assert.equal(next.x,Math.round((clip.x+clip.width)*10)/10,'A corrected boundary must use the full original SVG geometry, not a sum of individually rounded bbox fields');assert.equal(next.y,wrapBoundaries.get(offset));}else assert.equal(next.cellOverflowed,false,'A non-boundary caret may not be clipped');assert.ok(next.x>=bounds.x&&next.x<=absoluteGlyphX(bounds.x,bounds.w)&&next.y>=bounds.y&&next.y+next.height<=absoluteGlyphX(bounds.y,bounds.h),'Every returned caret must remain inside the original cell');}
      };
      await page.goto(origin+'/table-qa.html?format='+format+'&source='+plan.id);await page.waitForFunction(ready);const frame=page.frameLocator('.rhwp-dialog iframe');
      if(plan.page){await frame.locator('#sb-page').click();const goto=frame.locator('.goto-dialog-body input[type="number"]');await goto.fill(String(plan.page+1));await goto.press('Enter');await goto.waitFor({state:'hidden'});}
      const canvases=frame.locator('#scroll-content .document-page-canvas');await canvases.first().waitFor();
      const selected=frame.locator(`#scroll-content .document-page-canvas[data-rhwp-surface-cache-lookup-key*="|page:${plan.page}|"]`);await selected.waitFor();assert.equal(await selected.count(),1);const box=await selected.boundingBox();assert.ok(box&&box.width>0&&box.height>0);
      // Only public DOM pointer/keyboard input. The point comes from the actual source glyph and page canvas.
      await selected.click({position:{x:(cursor.x+1)*box.width/width,y:(cursor.y+cursor.height/2)*box.height/height}});
      assert.equal(await frame.locator('textarea[aria-label="문서 편집 입력"]').evaluate(el=>el===document.activeElement),true,'A genuine glyph click must focus native editing');await frame.locator('.caret').waitFor({state:'visible'});await page.keyboard.press('End');await page.keyboard.type(' QA',{delay:30});
      const download=async(label:string,expectedBody=expectedRoot)=>{const promise=page.waitForEvent('download');await page.getByRole('button',{name:format.toUpperCase()+' 다운로드만',exact:true}).click();const file=await promise,location=await file.path();assert.ok(location);const data=new Uint8Array(readFileSync(location));const doc=new Engine(data);try{same(rootText(doc),expectedBody,`The ${label} export differs from the predetermined root-body text`);same(rootProperties(doc),originalRootProperties,'Root paragraph or original-prefix character format changed');return{cells:readCells(doc,originalCells),pages:Array.from({length:doc.pageCount()},(_,p)=>hash(doc.renderPageSvgWithProfile(p,'print')))};}finally{doc.free();}};
      const edited=await download('edited');if(plan.body)same(edited.cells,originalCells,'Body input must not change any cells');else same(edited.cells[target].texts,[originalCells[target].texts[0]+' QA'],'Only the selected title cell must acquire the keyboard text');assert.equal(await page.evaluate(()=>(window as any).cf194.applies.length),0);
      if(output&&plan.id==='hwp')await page.screenshot({path:resolve(output,'native-table-edited-1440.png')});
      await frame.locator('textarea[aria-label="문서 편집 입력"]').focus();await page.keyboard.press('Control+z');const undone=await download('undo',originalRoot);same(undone.cells,originalCells,'Undo must restore all cells');same(undone.pages,originalPages,'Undo must restore all print pages');
      await frame.locator('textarea[aria-label="문서 편집 입력"]').focus();await page.keyboard.press('Control+y');const redone=await download('redo');same(redone.cells,edited.cells,'Redo must restore the edited cells');same(redone.pages,edited.pages,'Redo must restore all edited pages');assert.equal(await page.evaluate(()=>(window as any).cf194.applies.length),0);
      if(plan.id==='hwp'){
        const apply=page.getByRole('button',{name:'표 작업본 검수 적용',exact:true});assert.equal(await apply.isDisabled(),false);assert.equal(await page.getByRole('alert').count(),0);
        await apply.evaluate(button=>{(button as HTMLButtonElement).click();(window as any).cf194.setDisabled(true);});await page.getByRole('alert').filter({hasText:/문서 또는 저장 권한·상태가 바뀌어/u}).waitFor();assert.equal(await apply.isDisabled(),true);assert.equal(saveRequests.get(plan.id)??0,0);same(await page.evaluate(()=>({applies:(window as any).cf194.applies.length,attempts:(window as any).cf194.attempts,saved:(window as any).cf194.saved})),{applies:0,attempts:0,saved:null},'Revoking permission must stop an actually started operation before any handoff');
        await page.evaluate(()=>(window as any).cf194.setDisabled(false));await page.waitForFunction(ready);failNextSave=true;await apply.click();await page.getByRole('alert').filter({hasText:'Local QA save failed'}).waitFor();assert.equal(saveRequests.get(plan.id),1);assert.equal(failedSaves,1);assert.equal(savedFiles.has(plan.id),false);same(await page.evaluate(()=>({applies:(window as any).cf194.applies.length,attempts:(window as any).cf194.attempts,saved:(window as any).cf194.saved})),{applies:0,attempts:1,saved:null},'A real 503 must leave the local draft unchanged');assert.equal(await page.getByRole('dialog').isVisible(),true);same((await download('failed-save')).cells,redone.cells,'A failed save must retain editable text');
      }
      await page.getByRole('button',{name:'표 작업본 검수 적용',exact:true}).evaluate(button=>{(button as HTMLButtonElement).click();(button as HTMLButtonElement).click();});await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(saveRequests.get(plan.id),plan.id==='hwp'?2:1,'Double clicks must not duplicate the native save');
      const applies=await page.evaluate(()=>(window as any).cf194.applies);assert.equal(applies.length,1);assert.equal(await page.evaluate(()=>(window as any).cf194.attempts),plan.id==='hwp'?2:1);const applied=applies[0];assert.equal(applied.originalHash,originalHash);assert.equal(applied.originalName,'비공개 표 검수.'+format);assert.ok(applied.name.endsWith('.'+format));assert.equal(applied.pageHashes.length,plan.pages);
      same(applied.pageHashes,redone.pages,'The whole callback must describe the actual edited source');const savedBytes=savedFiles.get(plan.id);assert.ok(savedBytes);assert.equal(hash(savedBytes),applied.editedHash);
      const saved=new Engine(savedBytes);try{
        assert.equal(saved.getSourceFormat(),format);const cells=readCells(saved,originalCells);if(plan.body)same(cells,originalCells,'Body application must retain all cells');else same(cells[target].texts,[originalCells[target].texts[0]+' QA'],'The applied title cell must retain the keyboard text');same(cells.map((cell:any)=>({...cell,texts:undefined})),originalCells.map((cell:any)=>({...cell,texts:undefined})),'All original cell geometry and structure must remain');
        same(rootText(saved),expectedRoot,'The applied source differs from the predetermined root-body text');same(rootProperties(saved),originalRootProperties,'The applied source changed root formatting');assert.equal(nonText(saved),originalDrawing,'Table borders or target-page images changed');same(saved.getControls(),before.getControls(),'Original control chains changed');same(saved.getFieldList(),before.getFieldList(),'Original fields changed');
        assert.ok(hash(JSON.stringify(originalGlyphs(saved)))===originalGlyphHash,'An original non-target glyph moved or target text changed its format');checkTargetReflow(saved);
        for(let index=0;index<cells.length;index++)if(index!==target)same(cells[index].texts,originalCells[index].texts,'A non-target cell changed');
        if(!plan.fileId)assert.match(saved.getTextFileText(),/123,456원/u);
        for(let p=0;p<plan.pages;p++){const current=hash(saved.renderPageSvgWithProfile(p,'print'));assert.ok(current===applied.pageHashes[p],`Callback/native page ${p+1} mismatch`);if(p!==plan.page)assert.ok(current===originalPages[p],`Unedited page ${p+1} changed`);}
        const savedArchive=unzipSync(saved.exportHwpx());assert.deepEqual(Object.keys(savedArchive).filter(name=>name.startsWith('BinData/')).sort(),Object.keys(originalArchive).filter(name=>name.startsWith('BinData/')).sort());for(const[name,value]of Object.entries(originalArchive)){if(name.startsWith('BinData/')||(/^Contents\/section\d+\.xml$/u.test(name)&&name!==`Contents/section${glyph.secIdx}.xml`)||name==='Contents/header.xml')assert.ok(hash(savedArchive[name])===hash(value),'Untouched native archive changed');if(/^Contents\/section\d+\.xml$/u.test(name))same(serializedTabs(savedArchive[name]),serializedTabs(value),'Serialized original tab attributes changed');}
        const exported=exportNativeWithReport(saved,format);assert.equal(exported.report.count,0);assert.equal(exported.report.lossRecords,0);const second=new Engine(exported.bytes);try{assert.equal(second.pageCount(),plan.pages);assert.equal(second.getSourceFormat(),format);same(second.getControls(),before.getControls(),'A second native save changed controls');same(second.getFieldList(),before.getFieldList(),'A second native save changed fields');same(rootText(second),expectedRoot,'A second native save changed body text');same(rootProperties(second),originalRootProperties,'A second native save changed root format');same(readCells(second,originalCells),cells,'A second native save changed the cells');checkTargetReflow(second);for(let p=0;p<plan.pages;p++)assert.ok(hash(second.renderPageSvgWithProfile(p,'print'))===applied.pageHashes[p],`Second native reopen page ${p+1} mismatch`);}finally{second.free();}
      }finally{saved.free();}
      await page.getByRole('button',{name:'저장한 표 작업본 재열기',exact:true}).click();await page.waitForFunction(ready);const reopened=await download('reopened');same(reopened.cells,redone.cells,'The new SDK instance must retain the saved cells');same(reopened.pages,applied.pageHashes,'The new SDK instance must retain all print pages');assert.equal(await page.evaluate(()=>(window as any).cf194.applies.length),1);
      assert.equal(hash(original),originalHash);if(plan.fileId)assert.equal(hash(readFileSync(actualSources.get(plan.id)!)),originalHash);assert.deepEqual(errors,[]);results.push({id:plan.id,provenance:plan.fileId?'Actual '+plan.fileId+' private memory clone':'Synthetic native document',target:plan.body?'body':'cell',format,pages:plan.pages,sourceSha256:originalHash,savedSha256:applied.editedHash,cellCount:originalCells.length,binDataCount:Object.keys(originalArchive).filter(name=>name.startsWith('BinData/')).length,unmodifiedPagesExact:plan.pages-1,originalNonTargetGlyphsAndCellPropertiesPreserved:true,targetGlyphs:plan.targetReflow?'VERIFIED_TWO_LINE_CENTERED_REFLOW_INSIDE_ORIGINAL_CELL':'ORIGINAL_POSITIONS_EXACT',caretQueryLimitation:plan.targetReflow?'One retained wrap separator boundary is explicitly reported as corrected to the original cell edge; not proof of UI caret affinity or font ink extent':'No target reflow exception',existingTabsPreserved:true,undoOriginalPagesExact:true,redoAndCallbackPagesExact:true,newSdkReopenExact:true,originalUnchanged:true,successfulLocalSaves:1,permissionRevocation:plan.id==='hwp'?'ACTUAL_OPERATION_ABORTED_BEFORE_HANDOFF':'Covered by shared handler synthetic HWP',failedLocalSave:plan.id==='hwp'?'ACTUAL_POST_503_DRAFT_UNCHANGED':'Covered by shared handler synthetic HWP',firstSdkContentLossReport:'UNAVAILABLE; separate original structure/text/picture/page checks performed',secondNativeExportReport:{count:0,lossRecords:0}});console.log('CF194/195 '+plan.id+' actual '+(plan.body?'body':'cell')+' input/Undo/Redo/apply/reopen PASS');
    }finally{before.free();await page.close();}
  });}if(output)writeFileSync(resolve(output,'native-table-result.json'),JSON.stringify({scope:'Local actual approved SDK plus same-parser native preservation; not PC Hancom, live D1/Drive save or A-Z acceptance',focusedDiagnostic:focusedCase??null,plannedCases:cases.length,expectedCases:selectedCases.length,passedCases:results.length,pass:results.length===selectedCases.length,engineSha256:approved.engineSha256,bindingSha256:approved.bindingSha256,results},null,2),{flag:'wx'});}finally{await browser.close();await server.close();}
});
