import assert from 'node:assert/strict';
import {existsSync,readFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import test from 'node:test';
import {chromium,type Page} from 'playwright-core';

test('CF209 actual project schedule preserves selected-project and unsaved-input boundaries',async t=>{
  const {createServer}=await import('../apps/web/qa/vite-server.js');
  const source=readFileSync('apps/web/src/workflow/ProjectWorkflowSchedule.tsx');
  console.log('CF209 product read point',createHash('sha256').update(source).digest('hex'));
  const beforeSource=process.env.CF209_BEFORE==='1'?execFileSync('git',['-c','safe.directory='+process.cwd().replaceAll('\\','/'),'show','e78cf5ed36d8d24c77903d821984d649fad08238:apps/web/src/workflow/ProjectWorkflowSchedule.tsx'],{encoding:'utf8'}):null;
  if(beforeSource)console.log('CF209 actual before source',createHash('sha256').update(beforeSource).digest('hex'));
  const server=await createServer({root:resolve('apps/web'),...(process.env.CF149_CACHE_ROOT?{cacheDir:process.env.CF149_CACHE_ROOT}:{}),server:{host:'127.0.0.1',port:0,hmr:false},logLevel:'error',plugins:[{
    name:'cf209-schedule-proof',enforce:'pre',
    transform:(_code,id)=>beforeSource&&id.replaceAll('\\','/').endsWith('/ProjectWorkflowSchedule.tsx')?beforeSource:undefined,
    resolveId:id=>id==='/cf209-entry.js'?'\0cf209-entry':undefined,
    load:id=>id==='\0cf209-entry'?`
      import React from 'react';import {createRoot} from 'react-dom/client';import {flushSync} from 'react-dom';
      import {ProjectWorkflowSchedule} from '/src/workflow/ProjectWorkflowSchedule.tsx';
      import {requestNavigation} from '/src/navigation-guard.ts';import {qaProjects} from '/qa/cf102-data.ts';
      import '/src/workflow/ProjectWorkflowSchedule.css';import '/src/preview-theme.css';import '/src/theme-system.css';
      const params=new URLSearchParams(location.search),copy=value=>JSON.parse(JSON.stringify(value));
      const projects=[1,2].map(number=>({...copy(qaProjects[0]),id:'project-'+number,caseId:'case-'+number,code:'CF209-00'+number,name:'CF209 합성 프로젝트 '+number,client:'합성 기술검수 발주처',profileVersion:1,responsiblePm:{id:'pm-1',name:'합성 PM 1'},stages:qaProjects[0].stages.map(stage=>({...copy(stage),scheduleStatus:'PLANNED',scheduleNote:'저장 원문 '+stage.stageCode,scheduleVersion:1}))}));
      const state={projects,gets:0,pmGets:0,puts:[],unexpected:[],navigation:[]};globalThis.cf209=state;
      const originalFetch=window.fetch.bind(window),response=(body,status=200)=>Response.json(copy(body),{status});
      window.fetch=async(input,init={})=>{
        const url=new URL(typeof input==='string'?input:input.url,location.origin),path=url.pathname,method=init.method||'GET';
        if(!path.startsWith('/api/'))return originalFetch(input,init);
        if(path==='/api/project-workflow/schedule'&&method==='GET'){state.gets++;if(params.has('refresh-fail')&&state.gets===2)return response({error:'CF209 합성 저장 후 조회 실패'},503);return response({projects,dataBasis:'CF209_SYNTHETIC_LOCAL_ONLY'});}
        if(path==='/api/project-workflow/pm-options'&&method==='GET'){state.pmGets++;if(params.has('pm-fail')&&state.pmGets===1)return response({error:'CF209 합성 PM 조회 실패'},503);return response({users:params.has('pm-empty')?[]:[{id:'pm-1',displayName:'합성 PM 1',email:'one@example.test'},{id:'pm-2',displayName:'합성 PM 2',email:'two@example.test'}]});}
        const parts=path.split('/'),supported=parts[1]==='api'&&parts[2]==='project-workflow'&&parts[3]==='projects'&&['case-1','case-2'].includes(parts[4]),profile=supported&&parts.length===6&&parts[5]==='profile'?{1:parts[4]}:null,stage=supported&&parts.length===7&&parts[5]==='stages'?{1:parts[4],2:parts[6]}:null;
        if(method==='PUT'&&(profile||stage)){const payload=JSON.parse(init.body),project=projects.find(project=>project.caseId===(profile||stage)[1]);state.puts.push({path,payload});const apply=()=>{if(params.has('save-fail'))return response({error:'CF209 합성 충돌: 최신 버전 확인 필요'},409);if(profile){project.responsiblePm={id:payload.responsiblePmId,name:payload.responsiblePmId==='pm-2'?'합성 PM 2':'합성 PM 1'};project.profileVersion++;return response({profile:{version:project.profileVersion}});}const record=project.stages.find(record=>record.stageCode===stage[2]);if(payload.expectedVersion!==record.scheduleVersion)return response({error:'CF209 합성 충돌: 최신 버전 확인 필요'},409);Object.assign(record,{startDate:payload.startDate,endDate:payload.endDate,scheduleStatus:payload.status,scheduleNote:payload.noteText,scheduleVersion:record.scheduleVersion+1});return response({schedule:{...record,version:record.scheduleVersion}});};if(params.has('pending-save'))return new Promise(resolve=>{state.releaseSave=()=>resolve(apply());});return apply();}
        state.unexpected.push({path,method});return response({error:'CF209 허용되지 않은 합성 요청'},500);
      };
      const root=createRoot(document.getElementById('root'));
      const navigate=path=>{const proceed=()=>{state.navigation.push(path);history.pushState(null,'',path);flushSync(()=>root.render(React.createElement(ProjectWorkflowSchedule,{routeId:'PROJ-01',onNavigate:navigate})));};if(!requestNavigation(path,proceed))proceed();};state.navigate=navigate;
      flushSync(()=>root.render(React.createElement(ProjectWorkflowSchedule,{routeId:'PROJ-01',onNavigate:navigate})));
    `:undefined
  }]});
  await server.listen();const origin='http://127.0.0.1:'+(server.httpServer!.address() as {port:number}).port;
  const executablePath=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].find(path=>path&&existsSync(path));assert.ok(executablePath);
  const browser=await chromium.launch({executablePath,headless:true});
  const errors:string[]=[],external:string[]=[];
  const open=async(query='projectId=project-1')=>{
    const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(5000);page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!==origin){external.push(url.origin);return route.abort();}if(url.pathname==='/cf209.html')return route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><div id="root"></div><script>window.__CLAIM_API_ORIGIN__=location.origin</script><script type="module" src="/cf209-entry.js"></script></body></html>'});return route.continue();});await page.goto(origin+'/cf209.html?'+query);await page.waitForFunction(()=>(globalThis as any).cf209?.gets===1);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));return page;
  };
  const row=(page:Page,index=0)=>page.locator('.project-stage-editor-list > article').nth(index);
  const notes=(page:Page,index=0)=>row(page,index).getByLabel('일정 메모',{exact:true});
  const pm=(page:Page)=>page.locator('.project-pm-control select');
  const dirty=async(page:Page)=>{await pm(page).selectOption('pm-2');await row(page).getByLabel('시작일',{exact:true}).fill('2026-09-03');await row(page).getByLabel('종료일',{exact:true}).fill('2026-09-18');await row(page).locator('.project-stage-fields select').selectOption('DELAYED');await notes(page).fill('CF209 미저장 원문 보존');};
  const assertDirty=async(page:Page)=>{assert.equal(await notes(page).inputValue(),'CF209 미저장 원문 보존');assert.equal(await pm(page).inputValue(),'pm-2');assert.equal(await row(page).getByLabel('시작일',{exact:true}).inputValue(),'2026-09-03');assert.equal(await row(page).getByLabel('종료일',{exact:true}).inputValue(),'2026-09-18');assert.equal(await row(page).locator('.project-stage-fields select').inputValue(),'DELAYED');};
  try{
    await t.test('missing projectId cannot open or edit the first different project',async()=>{const page=await open('projectId=missing-cf209');try{assert.equal(await page.locator('.project-detail-modal').count(),0);assert.equal(await page.locator('.project-schedule-manager').count(),0);assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),0);}finally{await page.close();}});
    for(const gesture of ['X','Escape','backdrop','confirm-close'] as const){
      await t.test(`${gesture} cancellation preserves every unsaved field; explicit discard does not save it`,async()=>{const page=await open();try{await pm(page).waitFor();await dirty(page);const act=async()=>{if(gesture==='X')await page.getByRole('button',{name:'프로젝트 상세 팝업 닫기',exact:true}).click();else if(gesture==='Escape')await page.keyboard.press('Escape');else if(gesture==='backdrop')await page.locator('.project-detail-modal-backdrop').click({position:{x:3,y:3}});else await page.getByRole('button',{name:'확인하고 닫기',exact:true}).click();};const dialogs:string[]=[];page.once('dialog',async dialog=>{dialogs.push(dialog.message());await dialog.dismiss();});await act();assert.equal(dialogs.length,1,'A dirty close must require an explicit confirmation');assert.equal(await page.locator('.project-detail-modal').count(),1);await assertDirty(page);if(gesture==='X'&&!beforeSource&&process.env.CF209_ARTIFACT_DIR){mkdirSync(process.env.CF209_ARTIFACT_DIR,{recursive:true});const proof=resolve(process.env.CF209_ARTIFACT_DIR,'screenshotguard-current.png');assert.equal(existsSync(proof),false,'Do not replace a previously captured proof');await page.locator('.project-detail-modal').screenshot({path:proof});console.log('CF209 cancelled-close screenshot',proof);}assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),0);page.once('dialog',dialog=>dialog.accept());await act();await page.waitForFunction(()=>!document.querySelector('.project-detail-modal'));await page.evaluate(()=>(globalThis as any).cf209.navigate('/projects/schedule?projectId=project-1'));await notes(page).waitFor();assert.equal(await notes(page).inputValue(),'저장 원문 KICKOFF');assert.equal(await pm(page).inputValue(),'pm-1');assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),0);}finally{await page.close();}});
    }
    await t.test('explicit reload cancellation preserves edits and does not requery; confirmed reload discards them',async()=>{const page=await open();try{await dirty(page);const prior=await page.evaluate(()=>(globalThis as any).cf209.gets),dialogs:string[]=[];page.once('dialog',async dialog=>{dialogs.push(dialog.message());await dialog.dismiss();});await page.getByRole('button',{name:'최신 일정 다시 불러오기',exact:true}).click();assert.equal(dialogs.length,1);await assertDirty(page);assert.equal(await page.evaluate(()=>(globalThis as any).cf209.gets),prior);page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'최신 일정 다시 불러오기',exact:true}).click();await page.waitForFunction(()=>(globalThis as any).cf209.gets===2);await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('.project-stage-note input')?.value==='저장 원문 KICKOFF');assert.equal(await pm(page).inputValue(),'pm-1');assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),0);}finally{await page.close();}});
    await t.test('saving one stage preserves another dirty stage and its original optimistic version',async()=>{const page=await open();try{await notes(page,0).fill('CF209 저장할 착수 원문');await notes(page,1).fill('CF209 미저장 현장 원문');await row(page,0).getByRole('button',{name:'수정 내용 저장',exact:true}).click();await page.waitForFunction(()=>(globalThis as any).cf209.gets===2);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await notes(page,0).inputValue(),'CF209 저장할 착수 원문');assert.equal(await notes(page,1).inputValue(),'CF209 미저장 현장 원문');const puts=await page.evaluate(()=>(globalThis as any).cf209.puts);assert.equal(puts.length,1);assert.equal(puts[0].payload.expectedVersion,1);assert.ok(puts[0].path.endsWith('/stages/KICKOFF'));await row(page,1).getByRole('button',{name:'수정 내용 저장',exact:true}).click();await page.waitForFunction(()=>(globalThis as any).cf209.gets===3);const last=await page.evaluate(()=>(globalThis as any).cf209.puts.at(-1));assert.ok(last.path.endsWith('/stages/SITE_SURVEY'));assert.equal(last.payload.noteText,'CF209 미저장 현장 원문');assert.equal(last.payload.expectedVersion,1);}finally{await page.close();}});
    await t.test('failed stage save refreshes once without losing dirty text or automatically retrying',async()=>{const page=await open('projectId=project-1&save-fail=1');try{await notes(page).fill('CF209 충돌 후 유지 원문');await row(page).getByRole('button',{name:'수정 내용 저장',exact:true}).click();await page.getByText('CF209 합성 충돌: 최신 버전 확인 필요',{exact:true}).waitFor();await page.waitForFunction(()=>(globalThis as any).cf209.gets===2);assert.equal(await notes(page).inputValue(),'CF209 충돌 후 유지 원문');assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),1);assert.equal(await page.locator('.project-schedule-manager > .notice-box[role="status"]').count(),0);}finally{await page.close();}});
    await t.test('a refreshed external version cannot silently overwrite a locally dirty stage',async()=>{const page=await open();try{await notes(page,1).fill('CF209 stale 버전 유지 원문');await page.evaluate(()=>{const stage=(globalThis as any).cf209.projects[0].stages.find((stage:any)=>stage.stageCode==='SITE_SURVEY');stage.scheduleVersion=2;stage.scheduleNote='CF209 외부 최신 원문';});await notes(page,0).fill('CF209 다른 단계 저장');await row(page,0).getByRole('button',{name:'수정 내용 저장',exact:true}).click();await page.waitForFunction(()=>(globalThis as any).cf209.gets===2);assert.equal(await notes(page,1).inputValue(),'CF209 stale 버전 유지 원문');await row(page,1).getByRole('button',{name:'수정 내용 저장',exact:true}).click();await page.getByText('CF209 합성 충돌: 최신 버전 확인 필요',{exact:true}).waitFor();await page.waitForFunction(()=>(globalThis as any).cf209.gets===3);const state=await page.evaluate(()=>(globalThis as any).cf209);assert.equal(state.puts.length,2);assert.equal(state.puts[1].payload.expectedVersion,1);assert.equal(state.projects[0].stages.find((stage:any)=>stage.stageCode==='SITE_SURVEY').scheduleNote,'CF209 외부 최신 원문');assert.equal(await notes(page,1).inputValue(),'CF209 stale 버전 유지 원문');}finally{await page.close();}});
    await t.test('PM lookup failure is actionable and its retry preserves unrelated schedule edits',async()=>{const page=await open('projectId=project-1&pm-fail=1');try{const retry=page.getByRole('button',{name:'PM 목록 다시 불러오기',exact:true});await retry.waitFor();assert.equal(await pm(page).isDisabled(),true);await notes(page).fill('CF209 PM 조회 재시도 중 보존 원문');await retry.click();await page.waitForFunction(()=>(globalThis as any).cf209.pmGets===2);await page.waitForFunction(()=>document.querySelector<HTMLSelectElement>('.project-pm-control select')?.disabled===false);assert.equal(await pm(page).inputValue(),'pm-1');assert.equal(await notes(page).inputValue(),'CF209 PM 조회 재시도 중 보존 원문');assert.equal(await page.getByRole('alert').count(),0);assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),0);assert.equal(await page.evaluate(()=>(globalThis as any).cf209.gets),1);}finally{await page.close();}});
    await t.test('an actual empty PM list is not mislabeled as a network error',async()=>{const page=await open('projectId=project-1&pm-empty=1');try{await page.getByText('현재 선택 가능한 담당 PM이 없습니다.',{exact:false}).waitFor();assert.equal(await page.getByRole('alert').count(),0);assert.equal(await page.getByRole('button',{name:'PM 목록 다시 불러오기',exact:true}).count(),0);assert.equal(await pm(page).locator('option').count(),1);assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),0);}finally{await page.close();}});
    await t.test('an in-flight save cannot be closed or submitted twice before its result is known',async()=>{const page=await open('projectId=project-1&pending-save=1');try{await notes(page).fill('CF209 저장 응답 대기 원문');await row(page).getByRole('button',{name:'수정 내용 저장',exact:true}).click();await page.waitForFunction(()=>typeof(globalThis as any).cf209.releaseSave==='function');await page.getByRole('button',{name:'프로젝트 상세 팝업 닫기',exact:true}).click();assert.equal(await page.locator('.project-detail-modal').count(),1);assert.equal(await notes(page).inputValue(),'CF209 저장 응답 대기 원문');assert.equal(await row(page).locator('.stage-schedule-save-button').isDisabled(),true);assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),1);await page.evaluate(()=>(globalThis as any).cf209.releaseSave());await page.waitForFunction(()=>(globalThis as any).cf209.gets===2);assert.equal(await notes(page).inputValue(),'CF209 저장 응답 대기 원문');}finally{await page.close();}});
    await t.test('write ACK followed by failed readback blocks resubmission until explicit latest-data recovery',async()=>{const page=await open('projectId=project-1&refresh-fail=1');try{await notes(page).fill('CF209 ACK 후 조회 실패 원문');await row(page).getByRole('button',{name:'수정 내용 저장',exact:true}).click();await page.getByText(/서버 저장 후 최신 일정 조회에 실패했습니다/u).waitFor();assert.equal(await notes(page).inputValue(),'CF209 ACK 후 조회 실패 원문');assert.equal(await row(page).locator('.stage-schedule-save-button').isDisabled(),true);assert.equal(await page.locator('.schedule-complete-button').isDisabled(),true);assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),1);assert.equal(await page.locator('.project-schedule-manager > .notice-box[role="status"]').count(),0);page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'최신 일정 다시 불러오기',exact:true}).click();await page.waitForFunction(()=>(globalThis as any).cf209.gets===3);await page.waitForFunction(()=>document.querySelector<HTMLButtonElement>('.stage-schedule-save-button')?.disabled===false);assert.equal(await notes(page).inputValue(),'CF209 ACK 후 조회 실패 원문');assert.match(await row(page).locator('header small').innerText(),/v2/u);assert.equal(await page.evaluate(()=>(globalThis as any).cf209.puts.length),1);}finally{await page.close();}});
    assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  }finally{await browser.close();await server.close();}
});
