import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {chromium} from 'playwright-core';
import {getDocumentProxy,extractImages} from 'unpdf';
import test from 'node:test';

test('CF208 actual React proposal keeps reviewed native flow, photograph alignment and PDF cover bands',async t=>{
  const {createServer}=await import('../apps/web/qa/vite-server.js');
  const server=await createServer({root:resolve('apps/web'),...(process.env.CF149_CACHE_ROOT?{cacheDir:process.env.CF149_CACHE_ROOT}:{}),server:{host:'127.0.0.1',port:0,hmr:false},logLevel:'error',plugins:[{
    name:'cf208-proposal-proof',enforce:'pre',
    transform(code,id){
      if(id.replaceAll('\\','/').endsWith('/ProposalView.tsx'))return code+'\nexport {ProposalFinalDocumentPreview};';
      if(id.replaceAll('\\','/').endsWith('/native-hwp-pages.ts')&&process.env.CF208_NEGATIVE==='collapse'){
        const condition='if(previous&&(ordinary||photo))';assert.ok(code.includes(condition));return code.replace(condition,'if(previous&&ordinary)');
      }
      if(id.replaceAll('\\','/').endsWith('/native-hwp-pages.ts')&&process.env.CF208_NEGATIVE==='paper-border'){
        const margin='margins={top:px(css.paddingTop)+px(css.borderTopWidth),right:px(css.paddingRight)+px(css.borderRightWidth),bottom:px(css.paddingBottom)+px(css.borderBottomWidth),left:px(css.paddingLeft)+px(css.borderLeftWidth)}';assert.ok(code.includes(margin));return code.replace(margin,margin.replace(/\+px\(css\.border(?:Top|Right|Bottom|Left)Width\)/gu,''));
      }
      if(id.replaceAll('\\','/').endsWith('/final-document-export.ts')&&process.env.CF208_NEGATIVE==='pdf-bands'){
        const start=code.indexOf("        clonedPage.querySelectorAll<HTMLElement>('.proposal-cover-heading > div').forEach"),end=code.indexOf('        await Promise.all',start);assert.ok(start>=0&&end>start);return code.slice(0,start)+code.slice(end);
      }
      if(id.replaceAll('\\','/').endsWith('/editable-hwp-export.ts')&&process.env.CF208_NEGATIVE==='table-cache'){
        const statement=code.match(/^\s*if\(geometry\.reflowCellLines\)changed=.*$/mu)?.[0];assert.ok(statement);return code.replace(statement,'');
      }
      if(process.env.CF208_LEGACY_FLOW==='1'&&id.replaceAll('\\','/').endsWith('/native-hwp-pages.ts')){
        const start=code.indexOf('// CF208 reviewed proposal header flow'),end=code.indexOf('    const css=style(node);',start);
        assert.ok(start>=0&&end>start);code=code.slice(0,start)+code.slice(end);
        const next="const next=node.nextElementSibling?.matches(reportToc?'.report-toc-entry':'.proposal-final-toc li')?node.nextElementSibling:null;";
        const advance='const advance=next?(next.getBoundingClientRect().top-rect.top)/pageScale:rect.height/pageScale+px(style(node).marginBottom);';
        assert.ok(code.includes(next)&&code.includes(advance));return code.replace(next,"const next=reportToc&&node.nextElementSibling?.matches('.report-toc-entry')?node.nextElementSibling:null;").replace(advance,'const advance=reportToc?(next?(next.getBoundingClientRect().top-rect.top)/pageScale:rect.height/pageScale+px(style(node).marginBottom)):undefined;').replace('alignment??css.textAlign','css.textAlign');
      }
    },
    resolveId:id=>id==='/cf208-entry.js'?'\0cf208-entry':id==='/cf208-zip.js'?'\0cf208-zip':undefined,
    load:id=>id==='\0cf208-zip'?"export {unzipSync,strFromU8} from 'fflate';":id==='\0cf208-entry'?`
      import React from 'react';import {createRoot} from 'react-dom/client';import {flushSync} from 'react-dom';
      import {ProposalFinalDocumentPreview} from '/src/proposals/ProposalView.tsx';
      import '/src/preview-theme.css';import '/src/theme-system.css';import '/src/documents/StructuredDocumentEditor.css';import '/src/documents/DocumentReviewWorkspace.css';
      const canvas=document.createElement('canvas');canvas.width=180;canvas.height=80;const ctx=canvas.getContext('2d');ctx.fillStyle='#c22';ctx.fillRect(0,0,180,80);const photo=canvas.toDataURL();
      const longCell='CF208 긴 한글 셀 금액 1,234,567원과 수량 12.50을 보존한다. '+('합성 기술검수 표 원문이 셀 너비 안에서 줄바꿈되어야 한다. '.repeat(5));
      const table='<table style="width:100%;table-layout:fixed;border-collapse:collapse"><colgroup><col style="width:30%"><col style="width:70%"></colgroup><tbody><tr><th style="padding:10px;border:1px solid #222">합성 항목</th><th style="padding:10px;border:1px solid #222">합성 내역</th></tr><tr><td style="padding:10px;border:1px solid #222">CF208 셀 경계</td><td style="padding:10px;border:1px solid #222">'+longCell+'</td></tr></tbody></table>';
      const chapters=Array.from({length:12},(_,i)=>({number:i+1,title:'CF208 원문 제목 '+String(i+1).padStart(2,'0')+' 끝',body:'<p>CF208 본문 '+(i+1)+' 금액 <strong>123,456원</strong> 원문 보존.</p>'+(i<2?'<p><img src="'+photo+'" width="180" height="80" style="display:block;margin-left:auto;margin-right:'+(i===0?'auto':'0px')+'"></p>':i===2?table:''),included:true}));
      const root=createRoot(document.getElementById('root'));globalThis.cf208={mount:coverOnly=>flushSync(()=>root.render(React.createElement(ProposalFinalDocumentPreview,{projectTitle:'CF208 합성 제안서',subtitle:'내부 기술 검수',clientName:'CF208 합성 제출처',submissionDate:'2026-10-08',chapters:coverOnly?[]:chapters,revision:coverOnly?'cf208-cover':'cf208-full'})))};globalThis.cf208.mount(false);
    `:undefined
  }]});
  await server.listen();const origin='http://127.0.0.1:'+(server.httpServer!.address() as {port:number}).port;
  const executablePath=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].find(path=>path&&existsSync(path));
  const browser=await chromium.launch({executablePath,headless:true}),page=await browser.newPage();
  const wasm=readFileSync('pinned-runtime/pkg/rhwp_bg.wasm'),binding=readFileSync('pinned-runtime/pkg/rhwp.js'),sha=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
  assert.equal(sha(wasm),'bcc40a79bcd9be813cb231c6d8a0376b803ab8a6c189a09bcccabb8a249f3c44');assert.equal(sha(binding),'ad01e939079e3518bc76c442bf395ab058a912991ccb54c8b0be7f5a9a760153');
  const errors:string[]=[],external:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  const manifest={wasm:sha(wasm),files:[{path:'assets/rhwp_bg-test.wasm',sha256:sha(wasm)},{path:'native/rhwp-ad01e939079e.js',sha256:sha(binding)}]};
  try{
    await page.route('**/*',route=>{
      const url=new URL(route.request().url());if(url.origin!==origin){external.push(url.origin);return route.abort();}
      if(url.pathname==='/cf208.html')return route.fulfill({contentType:'text/html',body:'<!doctype html><html><body><div id="root"></div><script type="module" src="/cf208-entry.js"></script></body></html>'});
      if(url.pathname==='/api/proposal-studio/assets/BRAND_LOGO')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="120" height="72"><rect width="120" height="72" fill="#e70"/></svg>'});
      if(url.pathname==='/rhwp/build-manifest.json')return route.fulfill({json:manifest});
      if(url.pathname==='/rhwp/assets/rhwp_bg-test.wasm')return route.fulfill({body:wasm,contentType:'application/wasm'});
      if(url.pathname==='/rhwp/native/rhwp-ad01e939079e.js')return route.fulfill({body:binding,contentType:'text/javascript'});
      return route.continue();
    });
    await page.goto(origin+'/cf208.html');await page.waitForFunction(()=>document.querySelectorAll('[data-export-page]').length===14&&!document.querySelector('[data-page-fit-overflow="true"]'));await page.evaluate('globalThis.__name=value=>value');
    await t.test('12 reviewed TOC rows and header gap survive actual native download and reopen without rule overlap',async()=>{
      const download=page.waitForEvent('download');
      const rendered=await page.evaluate(async()=>{
        const {collectNativeHwpPages}=await import('/src/documents/native-hwp-pages.ts' as string);
        const {downloadFinalDocument}=await import('/src/documents/final-document-export.ts' as string);
        const root=document.querySelector<HTMLElement>('.proposal-final-document')!,before=root.innerHTML,pages=await collectNativeHwpPages(root,'portrait');
        const headers=[...root.querySelectorAll<HTMLElement>('[data-export-page].proposal-final-chapter > header')].map(header=>{const css=getComputedStyle(header);return parseFloat(css.paddingBottom)+parseFloat(css.borderBottomWidth)+parseFloat(css.marginBottom);});
        const parsed=new DOMParser().parseFromString(pages[2].html,'text/html'),title=parsed.querySelectorAll('p')[1];
        const result=await downloadFinalDocument({root,format:'hwp',fileName:'CF208 synthetic proposal',orientation:'portrait',purpose:'ADMIN_QA'});
        return{pages:result.pageCount,sourceUnchanged:root.innerHTML===before,headers,titleAfter:parseFloat((title as HTMLElement).style.marginBottom),toc:pages[1].tableGeometry!.map((geometry:{advance?:number})=>geometry.advance),sourceRows:[...root.querySelectorAll<HTMLElement>('.proposal-final-toc li')].map(row=>({top:row.getBoundingClientRect().top,height:row.getBoundingClientRect().height,marginBottom:parseFloat(getComputedStyle(row).marginBottom)||0,line:getComputedStyle(row).lineHeight,font:getComputedStyle(row).fontSize}))};
      });
      const artifact=await download,path=await artifact.path();assert.ok(path);assert.equal(artifact.suggestedFilename(),'CF208 synthetic proposal.hwp');
      const actual=await page.evaluate(async bytes=>{
        const {loadNativeHwpEngine}=await import('/src/documents/native-hwp-runtime.ts' as string);const {collectNativeHwpPages}=await import('/src/documents/native-hwp-pages.ts' as string);const {verifyNativeHwpContent}=await import('/src/documents/editable-hwp-export.ts' as string);
        const root=document.querySelector<HTMLElement>('.proposal-final-document')!,before=root.innerHTML,pages=await collectNativeHwpPages(root,'portrait'),Engine=await loadNativeHwpEngine(),doc=new Engine(Uint8Array.from(bytes));
        try{verifyNativeHwpContent(doc.exportHwpx(),pages);const svgs=Array.from({length:doc.pageCount()},(_,i)=>doc.renderPageSvg(i));(globalThis as any).cf208Svgs=svgs;
          const {unzipSync,strFromU8}=await import('/cf208-zip.js' as string),archive=unzipSync(doc.exportHwpx()),parser=new DOMParser(),section=parser.parseFromString(strFromU8(archive['Contents/section2.xml']),'application/xml'),header=parser.parseFromString(strFromU8(archive['Contents/header.xml']),'application/xml');
          (globalThis as any).cf208NativeParagraphs=[...section.getElementsByTagName('hp:p')].filter(p=>p.textContent?.includes('CF208 본문 1')||p.getElementsByTagName('hp:pic').length).map(p=>{const definition=[...header.getElementsByTagName('hh:paraPr')].find(pr=>pr.getAttribute('id')===p.getAttribute('paraPrIDRef'));return{id:p.getAttribute('id'),paraPr:p.getAttribute('paraPrIDRef'),text:[...p.getElementsByTagName('hp:t')].map(n=>n.textContent).join(''),picture:!!p.getElementsByTagName('hp:pic').length,spacing:definition?[...definition.querySelectorAll('*')].filter(n=>['hh:lineSpacing','hc:prev','hc:next'].includes(n.tagName)).map(n=>({tag:n.tagName,attrs:Object.fromEntries([...n.attributes].map(a=>[a.name,a.value]))})):[],lineseg:[...p.getElementsByTagName('hp:lineseg')].map(n=>Object.fromEntries([...n.attributes].map(a=>[a.name,a.value])))};});
          const glyph=(host:HTMLElement,prefix:string)=>{const paper=host.querySelector('svg')!;const box=paper.getBoundingClientRect(),rows=new Map<number,{text:string;node:SVGTextContentElement}>();for(const node of paper.querySelectorAll<SVGTextContentElement>('text')){if(!node.getNumberOfChars())continue;const p=node.getStartPositionOfChar(0),y=new DOMPoint(p.x,p.y).matrixTransform(node.getScreenCTM()!).y-box.y,key=Math.round(y*10);const prior=rows.get(key);if(prior)prior.text+=node.textContent??'';else rows.set(key,{text:node.textContent??'',node});}const found=[...rows.values()].filter(row=>row.text.replace(/\s+/gu,'').startsWith(prefix.replace(/\s+/gu,'')));if(found.length!==1)throw Error('CF208 glyph row not unique: '+prefix);const rect=found[0].node.getExtentOfChar(0),point=new DOMPoint(rect.x,rect.y).matrixTransform(found[0].node.getScreenCTM()!);return point.y-box.y;};
          const sourceRows=[...root.querySelectorAll<HTMLElement>('.proposal-final-toc li > span')],tocPaper=root.querySelector<HTMLElement>('.proposal-final-toc')!.getBoundingClientRect();
          const sourceY=sourceRows.map(node=>{const walk=document.createTreeWalker(node,NodeFilter.SHOW_TEXT);walk.nextNode();const range=document.createRange();range.setStart(walk.currentNode,0);range.setEnd(walk.currentNode,1);return range.getBoundingClientRect().y-tocPaper.y;});
          const probe=document.createElement('div');probe.style.cssText='position:absolute;left:-5000px;top:0;width:794px;height:1123px';document.body.append(probe);
          try{probe.innerHTML=svgs[1];await document.fonts.ready;const nativeY=sourceRows.map(node=>glyph(probe,node.textContent!));const progression=nativeY.map((y,i)=>(y-nativeY[0])-(sourceY[i]-sourceY[0]));probe.innerHTML=svgs[2];await document.fonts.ready;const bodyY=glyph(probe,'CF208 본문 1 금액');const headerRule=pages[2].rules!.find((rule:{colors:string[]})=>rule.colors[0].toLowerCase()==='#1f9ec4')!;const section=root.querySelector<HTMLElement>('[data-export-page].proposal-final-chapter')!,body=section.querySelector('article p')!,walk=document.createTreeWalker(body,NodeFilter.SHOW_TEXT);walk.nextNode();const range=document.createRange();range.setStart(walk.currentNode,0);range.setEnd(walk.currentNode,1);const sourceBodyY=range.getBoundingClientRect().y-section.getBoundingClientRect().y;
            probe.innerHTML=svgs[4];await document.fonts.ready;const sourceTable=root.querySelectorAll<HTMLElement>('[data-export-page].proposal-final-chapter')[2],sourceBox=sourceTable.getBoundingClientRect(),paper=probe.querySelector('svg')!,paperBox=paper.getBoundingClientRect(),position=(node:SVGGraphicsElement)=>{const rect=node.getBBox(),point=new DOMPoint(rect.x,rect.y).matrixTransform(node.getScreenCTM()!);return{x:point.x-paperBox.x,y:point.y-paperBox.y,width:rect.width,height:rect.height};};
            const nativeCells=[...paper.querySelectorAll<SVGGElement>('g[clip-path]')].flatMap(group=>{const id=group.getAttribute('clip-path')?.match(/^url\(#([^)]*)\)$/u)?.[1],clip=[...paper.querySelectorAll('clipPath')].find(node=>node.id===id)?.querySelector<SVGRectElement>('rect'),glyphs=[...group.querySelectorAll<SVGTextContentElement>('text')].filter(node=>node.getNumberOfChars());if(!clip||!glyphs.length)return[];const frame=position(clip);if(!pages[4].tableGeometry![0].cells.some((cell:{width:number;height:number})=>Math.abs(cell.width-frame.width)<=.1&&Math.abs(cell.height-frame.height)<=.1))return[];return[{...frame,text:glyphs.map(node=>node.textContent).join(''),glyphs:glyphs.map(node=>({text:node.textContent!,...position(node)}))}];}).sort((a,b)=>a.y-b.y||a.x-b.x);
            const table={cells:[...sourceTable.querySelectorAll<HTMLElement>('td,th')].map(cell=>{const rect=cell.getBoundingClientRect(),css=getComputedStyle(cell);return{text:cell.textContent!,left:rect.left-sourceBox.left,top:rect.top-sourceBox.top,width:rect.width,height:rect.height,offsetWidth:cell.offsetWidth,offsetHeight:cell.offsetHeight,padding:[css.paddingTop,css.paddingRight,css.paddingBottom,css.paddingLeft],border:[css.borderTopWidth,css.borderRightWidth,css.borderBottomWidth,css.borderLeftWidth]};}),geometry:pages[4].tableGeometry,nativeCells};(globalThis as any).cf208Table=table;
            return{count:doc.pageCount(),sourceUnchanged:root.innerHTML===before,sourceY,nativeY,progression,firstOffset:nativeY[0]-sourceY[0],bodyY,sourceBodyY,bodyGlyphOffset:bodyY-sourceBodyY,headerBottom:headerRule.top+headerRule.height,table};}finally{probe.remove();}
        }finally{doc.free();}
      },[...readFileSync(path)]);
      console.log('CF208 native TOC/header measured',JSON.stringify(process.env.CF208_LOG_DETAIL==='1'?{rendered,actual}:{pages:actual.count,sourceUnchanged:actual.sourceUnchanged,headerGap:rendered.titleAfter,headerBottom:actual.headerBottom,bodyGlyphY:actual.bodyY,bodyGlyphOffset:actual.bodyGlyphOffset,maxTocProgression:Math.max(...actual.progression.map(Math.abs)),tocFirstGlyphOffset:actual.firstOffset}));
      assert.equal(rendered.pages,14);assert.equal(actual.count,14);assert.equal(rendered.sourceUnchanged,true);assert.equal(actual.sourceUnchanged,true);
      assert.ok(rendered.headers.every(gap=>gap===26));assert.equal(rendered.titleAfter,26);assert.equal(rendered.toc.length,12);assert.ok(rendered.toc.every((advance:number,i:number)=>Math.abs(advance-(i+1<rendered.sourceRows.length?rendered.sourceRows[i+1].top-rendered.sourceRows[i].top:rendered.sourceRows[i].height+rendered.sourceRows[i].marginBottom))<=.1),'Each native TOC advance must match its actual reviewed DOM row-top delta, not a hardcoded font-dependent height');
      assert.ok(actual.progression.every(delta=>Math.abs(delta)<=.1),'Reviewed TOC progression must retain the existing 0.1px geometry bound');assert.ok(actual.bodyY>actual.headerBottom,'Native header rule must not intersect the first body glyph');
      const normalize=(text:string)=>text.replace(/\s+/gu,'');assert.equal(actual.table.nativeCells.length,4,'Each native table text group must have an actual cell clip frame');assert.deepEqual(actual.table.nativeCells.map(cell=>normalize(cell.text)),actual.table.cells.map(cell=>normalize(cell.text)),'Native cell order and complete text must remain equal to the reviewed DOM');
      const outside=actual.table.nativeCells.flatMap((cell,index)=>{const source=actual.table.cells[index],padding=actual.table.geometry![0].cells[index].padding;assert.equal(cell.width,source.offsetWidth);assert.equal(cell.height,source.offsetHeight);return cell.glyphs.filter(glyph=>glyph.x<cell.x+padding.left-.1||glyph.x+glyph.width>cell.x+cell.width-padding.right+.1||glyph.y<cell.y+padding.top-.1||glyph.y+glyph.height>cell.y+cell.height-padding.bottom+.1).map(glyph=>({cell:index,text:glyph.text,x:glyph.x,right:glyph.x+glyph.width,y:glyph.y,bottom:glyph.y+glyph.height,leftBound:cell.x+padding.left,rightBound:cell.x+cell.width-padding.right,topBound:cell.y+padding.top,bottomBound:cell.y+cell.height-padding.bottom}));});
      console.log('CF208 actual native table padding',JSON.stringify({cells:actual.table.nativeCells.map((cell,index)=>({index,x:cell.x,y:cell.y,width:cell.width,height:cell.height,glyphCount:cell.glyphs.length,minGlyphX:Math.min(...cell.glyphs.map(g=>g.x)),maxGlyphX:Math.max(...cell.glyphs.map(g=>g.x+g.width)),minGlyphY:Math.min(...cell.glyphs.map(g=>g.y)),maxGlyphY:Math.max(...cell.glyphs.map(g=>g.y+g.height)),sourceWidth:actual.table.cells[index].width,sourceHeight:actual.table.cells[index].height})),outsideCount:outside.length,firstOutside:outside.slice(0,4)}));assert.deepEqual(outside,[],'Native table glyphs must stay inside the real reopened cell frame and all reviewed padding at the existing 0.1px bound');
    });
    await t.test('solitary centered and right block photographs retain reviewed X and Y positions',async()=>{
      const result=await page.evaluate(async()=>{
        const root=document.querySelector<HTMLElement>('.proposal-final-document')!,before=root.innerHTML,svgs=(globalThis as any).cf208Svgs as string[];if(!svgs)throw Error('Actual native download must be checked first.');
        const {collectNativeHwpPages}=await import('/src/documents/native-hwp-pages.ts' as string),pages=await collectNativeHwpPages(root,'portrait');
        const results=[];for(let index=0;index<2;index++){const source=root.querySelectorAll<HTMLElement>('[data-export-page].proposal-final-chapter')[index],img=source.querySelector<HTMLImageElement>('img')!,box=source.getBoundingClientRect(),image=img.getBoundingClientRect(),css=getComputedStyle(img),probe=document.createElement('div');probe.style.cssText='position:absolute;left:-5000px;top:0;width:794px;height:1123px';probe.innerHTML=svgs[index+2];document.body.append(probe);try{const paper=probe.querySelector('svg')!,paperBox=paper.getBoundingClientRect(),photo=paper.querySelector<SVGGraphicsElement>('image')!;if(!photo)throw Error('Native photograph image missing.');const rect=photo.getBBox(),point=new DOMPoint(rect.x,rect.y).matrixTransform(photo.getScreenCTM()!),photoP=img.parentElement!,priorP=photoP.previousElementSibling!,geometry=(node:Element)=>{const r=node.getBoundingClientRect(),s=getComputedStyle(node);return{top:r.top-box.top,bottom:r.bottom-box.top,height:r.height,mt:s.marginTop,mb:s.marginBottom,lineHeight:s.lineHeight,display:s.display,position:s.position,float:s.cssFloat,clear:s.clear,transform:s.transform,minHeight:s.minHeight,overflow:s.overflow,padding:[s.paddingTop,s.paddingRight,s.paddingBottom,s.paddingLeft],border:[s.borderTopWidth,s.borderRightWidth,s.borderBottomWidth,s.borderLeftWidth]};},parsed=new DOMParser().parseFromString(pages[index+2].html,'text/html');results.push({alignment:index?'right':'center',sourceX:image.x-box.x,nativeX:point.x-paperBox.x,sourceY:image.y-box.y,nativeY:point.y-paperBox.y,yOffset:point.y-paperBox.y-(image.y-box.y),width:image.width,nativeWidth:rect.width,nativeHeight:rect.height,height:image.height,marginLeft:css.marginLeft,marginRight:css.marginRight,paperBorder:parseFloat(getComputedStyle(source).borderRightWidth),flow:{parentDisplay:getComputedStyle(photoP.parentElement!).display,visibleChildren:[...photoP.childNodes].map(n=>({kind:n.nodeName,text:n.textContent?.trim()})),priorP:geometry(priorP),photoP:geometry(photoP),image:geometry(img),collected:[...parsed.body.children].map(n=>({tag:n.tagName,text:n.textContent,style:n.getAttribute('style'),first30:n.outerHTML.slice(0,30)}))}});}finally{probe.remove();}}
        return{results,nativeParagraphs:(globalThis as any).cf208NativeParagraphs,unchanged:root.innerHTML===before};
      });
      console.log('CF208 photograph positions',JSON.stringify(process.env.CF208_LOG_DETAIL==='1'?result:{results:result.results.map(({flow,...value})=>value),unchanged:result.unchanged}));assert.equal(result.unchanged,true);assert.ok(result.results[0].sourceX>100);assert.ok(result.results[1].sourceX>result.results[0].sourceX);
      assert.ok(result.results.every(item=>Math.abs(item.nativeWidth-item.width)<=.1&&Math.abs(item.nativeHeight-item.height)<=.1),'Native photograph dimensions must remain equal to the reviewed DOM');
      const drift=result.results.flatMap(item=>[...(Math.abs(item.nativeX-item.sourceX)>.1?[{alignment:item.alignment,axis:'X',delta:item.nativeX-item.sourceX}]:[]),...(Math.abs(item.nativeY-item.sourceY)>.1?[{alignment:item.alignment,axis:'Y',delta:item.nativeY-item.sourceY}]:[])]);
      assert.deepEqual(drift,[],'Photograph placement must retain the existing 0.1px geometry bound; paper border and carrier leading are not silently tolerated');
    });
    await t.test('actual PDF download retains both reviewed blue gradient bands without changing cover HTML',async()=>{
      await page.evaluate(()=>(globalThis as any).cf208.mount(true));await page.waitForFunction(()=>document.querySelectorAll('[data-export-page]').length===2&&!document.querySelector('[data-page-fit-overflow="true"]'));
      const download=page.waitForEvent('download'),measurement=await page.evaluate(async()=>{
        const {downloadFinalDocument}=await import('/src/documents/final-document-export.ts' as string);const root=document.querySelector<HTMLElement>('.proposal-final-document')!,cover=root.querySelector<HTMLElement>('.proposal-final-cover')!,band=cover.querySelector<HTMLElement>('.proposal-cover-heading > div')!,before=root.innerHTML,paper=cover.getBoundingClientRect(),box=band.getBoundingClientRect(),css=getComputedStyle(band);
        const bands=[{x:box.x-paper.x,y:box.y-paper.y,height:parseFloat(css.borderTopWidth),width:box.width},{x:box.x-paper.x,y:box.bottom-paper.y-parseFloat(css.borderBottomWidth),height:parseFloat(css.borderBottomWidth),width:box.width}];
        const result=await downloadFinalDocument({root,format:'pdf',fileName:'CF208 synthetic cover',orientation:'portrait',purpose:'ADMIN_QA'});return{pages:result.pageCount,unchanged:root.innerHTML===before,bands};
      });
      const artifact=await download,path=await artifact.path();assert.ok(path);assert.equal(artifact.suggestedFilename(),'CF208 synthetic cover.pdf');const bytes=readFileSync(path);assert.equal(bytes.subarray(0,5).toString(),'%PDF-');assert.equal(measurement.pages,2);assert.equal(measurement.unchanged,true);
      const pdf=await getDocumentProxy(new Uint8Array(bytes));try{assert.equal(pdf.numPages,2);const images=await extractImages(pdf,1);assert.equal(images.length,1);const raster=images[0],sample=(x:number,y:number)=>{const offset=(Math.floor(y*raster.height/1123)*raster.width+Math.floor(x*raster.width/794))*raster.channels;return [...raster.data.subarray(offset,offset+3)];};
        const colors=measurement.bands.map(band=>({left:sample(band.x+band.width*.2,band.y+band.height*.5),right:sample(band.x+band.width*.8,band.y+band.height*.5)}));console.log('CF208 actual PDF gradient pixels',JSON.stringify({colors,bands:measurement.bands,width:raster.width,height:raster.height}));for(const pair of colors){for(const rgb of [pair.left,pair.right])assert.ok(rgb[0]<80&&rgb[1]>100&&rgb[2]>150&&rgb[2]>rgb[0]+80,'Both authored bands must contain actual cyan/blue PDF pixels');assert.ok(pair.right[0]>pair.left[0]&&pair.right[1]>pair.left[1],'The authored left-to-right gradient must not become a solid bar');}
      }finally{await pdf.loadingTask.destroy();}
    });
    assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  }finally{await browser.close();await server.close();}
});
