import assert from 'node:assert/strict';
import {existsSync,mkdirSync,mkdtempSync,readFileSync,readdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {join,resolve} from 'node:path';
import test from 'node:test';
import {chromium,type Page} from 'playwright-core';
import {getDocumentProxy} from 'unpdf';

test('CF210 actual schedule language preserves source records, pagination and local A4 output',async t=>{
  const {createServer}=await import('../apps/web/qa/vite-server.js');
  const before=process.env.CF210_BEFORE==='1'?execFileSync('git',['-c','safe.directory='+process.cwd().replaceAll('\\','/'),'show','3cc821dca212b6048c24d5ce4ed88458fb80fc9f:apps/web/src/workflow/ProjectSchedulePrint.tsx'],{encoding:'utf8'}):null;
  const source=before??readFileSync('apps/web/src/workflow/ProjectSchedulePrint.tsx','utf8');console.log('CF210 actual source',JSON.stringify({before:!!before,sha256:createHash('sha256').update(source).digest('hex')}));
  const initialStyles=readFileSync('apps/web/index.html','utf8').match(/<style>[\s\S]*?<\/style>/gu)?.join('');assert.ok(initialStyles,'The fixture must retain the real app index stylesheet, including its body reset');
  let artifacts:string|undefined;if(!before&&process.env.CF210_ARTIFACT_DIR){mkdirSync(process.env.CF210_ARTIFACT_DIR,{recursive:true});artifacts=mkdtempSync(join(process.env.CF210_ARTIFACT_DIR,'proof-'));console.log('CF210 local synthetic artifacts',artifacts);}
  const server=await createServer({root:resolve('apps/web'),...(process.env.CF149_CACHE_ROOT?{cacheDir:process.env.CF149_CACHE_ROOT}:{}),server:{host:'127.0.0.1',port:0,hmr:false},logLevel:'error',plugins:[{
    name:'cf210-actual-print',enforce:'pre',transform:(_code,id)=>before&&id.replaceAll('\\','/').endsWith('/ProjectSchedulePrint.tsx')?before:undefined,
    resolveId:id=>id==='/cf210-entry.js'?'\0cf210-entry':undefined,
    load:id=>id==='\0cf210-entry'?`
      import React from 'react';import {createRoot} from 'react-dom/client';import {ProjectSchedulePrint} from '/src/workflow/ProjectSchedulePrint.tsx';import {qaProjects} from '/qa/cf102-data.ts';
      import '/src/workflow/ProjectSchedulePrint.css';import '/src/preview-theme.css';import '/src/theme-system.css';
      const copy=value=>JSON.parse(JSON.stringify(value)),types=['TYPE-01','TYPE-02','TYPE-03','TYPE-04','TYPE-05','TYPE-06','TYPE-01','TYPE-02','CF210_UNKNOWN_TYPE'];
      const projects=types.map((claimType,i)=>({...copy(qaProjects[0]),id:'cf210-'+(i+1),caseId:'cf210-case-'+(i+1),code:'RAW210-'+String(i+1).padStart(3,'0'),name:'CF210 원자료 '+(i+1)+' 한국어 제목',client:'CF210 원문 거래처',claimType,responsiblePm:i===7?null:{id:'raw-pm-'+i,name:i===0?'미지정 원문직원':'CF210 PM 원문 '+i},stages:i===8?[]:qaProjects[0].stages.map((stage,index)=>({...copy(stage),owner:'CF210 단계 담당 원문 '+index,scheduleNote:'CF210 메모: 1,234,567원 / 12.50 / 2026-09-02',scheduleExplicit:index!==4}))}));
      const state={projects,original:JSON.stringify(projects),gets:0,closed:0,printCalls:[],unexpected:[]};globalThis.cf210=state;
      const originalFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{const url=new URL(typeof input==='string'?input:input.url,location.origin);if(!url.pathname.startsWith('/api/'))return originalFetch(input,init);if(url.pathname==='/api/project-workflow/schedule'&&(init.method||'GET')==='GET'){state.gets++;return Response.json({projects:copy(projects),dataBasis:'CF210_SYNTHETIC_LOCAL_ONLY'});}state.unexpected.push({path:url.pathname,method:init.method});return Response.json({error:'CF210 unexpected local request'},{status:500});};
      window.print=()=>state.printCalls.push(document.querySelectorAll('.schedule-print-sheet').length);
      const query=new URLSearchParams(location.search);query.set('month','2026-09');if(query.get('view')==='detail')query.set('projectId','cf210-1');
      createRoot(document.getElementById('root')).render(React.createElement(ProjectSchedulePrint,{currentSearch:'?'+query,userName:'CF210 출력자 원문',onClose:()=>state.closed++}));
    `:undefined
  }]});await server.listen();const origin='http://127.0.0.1:'+(server.httpServer!.address() as {port:number}).port;
  const executablePath=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'].find(path=>path&&existsSync(path));assert.ok(executablePath);
  const browser=await chromium.launch({executablePath,headless:true}),errors:string[]=[],external:string[]=[];
  const open=async(query='')=>{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(5000);page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!==origin){external.push(url.origin);return route.abort();}if(url.pathname==='/cf210.html')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="ko" data-theme="light"><head>'+initialStyles+'</head><body><div id="root"></div><script>window.__name=value=>value;window.__CLAIM_API_ORIGIN__=location.origin</script><script type="module" src="/cf210-entry.js"></script></body></html>'});return route.continue();});await page.goto(origin+'/cf210.html?'+query);await page.locator('.schedule-print-sheet').first().waitFor();return page;};
  const snapshot=(page:Page)=>page.evaluate(()=>{
    const root=document.querySelector<HTMLElement>('.schedule-print-root')!,state=(globalThis as any).cf210,clone=root.cloneNode(true) as HTMLElement;clone.querySelectorAll('.schedule-print-sheet__header dl > div:first-child dd').forEach(node=>node.textContent='CURRENT_TIME');
    const strings=(selector:string)=>[...root.querySelectorAll(selector)].map(node=>node.textContent||'');
    return{raw:JSON.stringify(state.projects),original:state.original,gets:state.gets,unexpected:state.unexpected,html:clone.innerHTML,language:root.lang,color:root.className,rows:[...root.querySelectorAll('.schedule-print-sheet')].map(sheet=>sheet.querySelectorAll('.schedule-print-calendar__row').length),headings:strings('.schedule-print-sheet h1'),metadata:strings('.schedule-print-sheet__header dt'),weekday:strings('.schedule-print-calendar__days small'),numbers:strings('.schedule-print-calendar__days b'),dayClasses:[...root.querySelectorAll('.schedule-print-calendar__days > span')].map(node=>node.className),dayTitles:[...root.querySelectorAll('.schedule-print-calendar__days > span')].map(node=>node.getAttribute('title')),names:strings('.is-overview .schedule-print-project > strong,.schedule-print-identity h2'),people:strings('.is-overview .schedule-print-calendar__row .schedule-print-pm,.is-detail .schedule-print-project > span'),rowMetadata:strings('.schedule-print-project > span'),dates:strings('.is-detail .schedule-print-project > small'),stages:strings('.is-detail .schedule-print-project > strong'),barStyles:[...root.querySelectorAll('.schedule-print-range')].map(node=>node.getAttribute('style')),barTitles:[...root.querySelectorAll('.schedule-print-range')].map(node=>node.getAttribute('title')),legend:strings('.schedule-print-legends span'),footer:strings('.schedule-print-sheet__footer > p'),toolbar:strings('.schedule-print-toolbar__title strong,.schedule-print-toolbar__title small,.schedule-print-toolbar__controls button'),aria:[root.querySelector('.schedule-print-toolbar')?.getAttribute('aria-label'),root.querySelector('.schedule-print-pages')?.getAttribute('aria-label')],progress:strings('.schedule-print-range b'),writer:strings('.schedule-print-sheet__header dl div:nth-child(2) dd')};
  });
  const preserved=(ko:Awaited<ReturnType<typeof snapshot>>,vi:Awaited<ReturnType<typeof snapshot>>,detail=false)=>{for(const key of ['raw','original','rows','names','numbers','dayClasses','barStyles','progress','writer'] as const)assert.deepEqual(vi[key],ko[key],key+' must preserve reviewed source data');if(detail){assert.deepEqual(vi.people,ko.people);assert.deepEqual(vi.dates.filter(value=>value.includes('2026-')),ko.dates.filter(value=>value.includes('2026-')));}else assert.deepEqual(vi.people.map(value=>value==='Chưa phân công'?'미지정':value),ko.people);assert.equal(vi.raw,vi.original);assert.equal(vi.gets,1);assert.deepEqual(vi.unexpected,[]);};
  const translated=(value:Awaited<ReturnType<typeof snapshot>>,detail=false)=>{assert.equal(value.language,'vi');assert.ok(value.headings.every(title=>title.includes(detail?'Lịch chi tiết dự án':'Lịch tổng hợp dự án')));assert.deepEqual(value.metadata.slice(0,3),['Thời điểm in','Người in','Trang']);assert.ok(value.weekday.every(day=>['CN','T2','T3','T4','T5','T6','T7'].includes(day)));assert.deepEqual(value.legend.slice(0,5),['Thời gian dự án','Cuối tuần','Ngày lễ Hàn Quốc','Ngày lễ Việt Nam','Ngày lễ chung']);assert.ok(value.footer.every(text=>text.includes('Lịch in phản ánh lịch mới nhất')));assert.ok(value.toolbar.includes('Lưu PDF')&&value.toolbar.includes('In')&&value.toolbar.includes('Đóng'));assert.equal(value.aria[0],'Thiết lập in lịch');assert.ok(value.dayTitles.some(title=>title?.includes('Việt Nam Quốc khánh')));assert.ok(value.dayTitles.some(title=>title==='Ngày làm việc'));if(detail){assert.deepEqual(value.stages.slice(0,6),['1. Liên kết đề xuất','2. Đã nhận dự án','3. Họp khởi động','4. Khảo sát hiện trường','5. Bóc tách khối lượng · Lập BOQ','6. Soạn báo cáo']);assert.ok(value.barTitles.some(title=>title?.startsWith('Họp khởi động · CF210 단계 담당 원문 2 · 2026-09-02')));}else{for(const old of ['현장조사 및 수량산출 클레임','분석 보고서 작성 클레임','일반적인 클레임','재건축·재개발 공사비 협상','사감정보고서','물가변동'])assert.ok(!value.rowMetadata.some(row=>row.includes(old)),old+' must be localized');assert.ok(value.rowMetadata.some(row=>row.includes('CF210_UNKNOWN_TYPE')));}};
  const paper=async(page:Page)=>{await page.emulateMedia({media:'print'});assert.equal(await page.locator('.schedule-print-toolbar').isVisible(),false);const layout=await page.locator('.schedule-print-sheet').evaluateAll(nodes=>nodes.map(node=>({width:node.getBoundingClientRect().width,height:node.getBoundingClientRect().height,overflow:node.scrollHeight>node.clientHeight+1})));assert.ok(layout.every(box=>box.width>1120&&box.width<1125&&box.height>790&&box.height<797&&!box.overflow),JSON.stringify(layout));return layout;};
  const inspectPdf=async(bytes:Uint8Array,page:Page,path?:string)=>{const byteCount=bytes.length,fingerprint=createHash('sha256').update(bytes).digest('hex');assert.ok(byteCount>1000);assert.equal(new TextDecoder().decode(bytes.subarray(0,5)),'%PDF-');const pdf=await getDocumentProxy(new Uint8Array(bytes));try{const texts:string[]=[];for(let i=1;i<=pdf.numPages;i++){const paper=await pdf.getPage(i),viewport=paper.getViewport({scale:1});assert.ok(Math.abs(viewport.width-297*72/25.4)<1&&Math.abs(viewport.height-210*72/25.4)<1);const content=await paper.getTextContent();texts.push(content.items.map(item=>'str'in item?item.str:'').join(' ').normalize('NFC'));}console.log('CF210 PDF page readback',JSON.stringify({pages:pdf.numPages,pageCharacters:texts.map(text=>text.length),lastPage:texts.at(-1)?.slice(0,160),dom:await page.evaluate(()=>['body','#root','.schedule-print-root','.schedule-print-pages'].map(selector=>{const node=document.querySelector<HTMLElement>(selector)!,css=getComputedStyle(node),rect=node.getBoundingClientRect();return{selector,height:rect.height,top:rect.top,paddingTop:css.paddingTop,paddingBottom:css.paddingBottom,marginTop:css.marginTop,marginBottom:css.marginBottom,display:css.display,rowGap:css.rowGap};}))}));assert.equal(pdf.numPages,4);const text=texts.join('\n');for(const token of ['Lịch tổng hợp dự án','Thời điểm in','Người in','Ngày lễ Việt Nam','Thời gian dự án'])assert.ok(text.includes(token),token+' must be present with real accented Unicode in the PDF');assert.doesNotMatch(text,/\uFFFD/u);for(let i=1;i<=9;i++)assert.ok(text.replace(/\s+/gu,'').includes(('CF210 원자료 '+i+' 한국어 제목').replace(/\s+/gu,'')));assert.equal(bytes.length,byteCount);assert.equal(createHash('sha256').update(bytes).digest('hex'),fingerprint);if(path)assert.equal(createHash('sha256').update(readFileSync(path)).digest('hex'),fingerprint);console.log('CF210 actual local headless PDF',JSON.stringify({pages:pdf.numPages,bytes:byteCount,sha256:fingerprint,path,scope:'Synthetic local Chromium print-to-PDF with local font fallback, not the live server or an operating-system print dialog'}));}finally{await pdf.loadingTask.destroy();}};
  try{
    if(before&&process.env.CF210_BASELINE_PDF_ONLY==='1'){const page=await open();try{await paper(page);const bytes=await page.pdf({format:'A4',landscape:true,preferCSSPageSize:true,printBackground:true}),pdf=await getDocumentProxy(new Uint8Array(bytes));try{console.log('CF210 DIAGNOSTIC ONLY original KO PDF',JSON.stringify({pages:pdf.numPages,sourceSha256:createHash('sha256').update(source).digest('hex'),body:await page.evaluate(()=>({margin:getComputedStyle(document.body).margin,top:document.body.getBoundingClientRect().top})),scope:'Only original KO pagination diagnosis; VI acceptance gates are intentionally not run in this explicitly selected diagnostic mode'}));assert.equal(pdf.numPages,4);}finally{await pdf.loadingTask.destroy();}assert.deepEqual(errors,[]);assert.deepEqual(external,[]);}finally{await page.close();}return;}
    await t.test('nine real-source-shaped projects retain four all-period pages and KO→VI→KO exact source',async()=>{const page=await open();try{await page.getByRole('button',{name:'흑백',exact:true}).click();const ko=await snapshot(page);assert.deepEqual(ko.rows,[8,1,8,1]);assert.deepEqual(ko.headings,['2026년 9월 프로젝트 통합 일정표','2026년 9월 프로젝트 통합 일정표','2026년 10월 프로젝트 통합 일정표','2026년 10월 프로젝트 통합 일정표']);await page.getByRole('button',{name:'Tiếng Việt',exact:true}).click();const vi=await snapshot(page);preserved(ko,vi);translated(vi);assert.equal(vi.color,'schedule-print-root is-mono');await paper(page);if(artifacts)await page.locator('.schedule-print-sheet').first().screenshot({path:join(artifacts,'vi-overview.png')});await page.emulateMedia({media:'screen'});await page.getByRole('button',{name:'한국어',exact:true}).click();const restored=await snapshot(page);assert.equal(restored.html,ko.html);assert.equal(restored.raw,ko.raw);assert.deepEqual(restored.rows,ko.rows);}finally{await page.close();}});
    await t.test('single-month and six-stage detail preserve dates, people, monthly layout and localized empty states',async()=>{for(const detail of [false,true]){const page=await open(detail?'view=detail':'scope=month');try{const ko=await snapshot(page);assert.deepEqual(ko.rows,detail?[6,6]:[8,1]);await page.getByRole('button',{name:'Tiếng Việt',exact:true}).click();const vi=await snapshot(page);preserved(ko,vi,detail);translated(vi,detail);assert.equal(vi.color,'schedule-print-root is-color');if(detail){assert.ok(await page.getByText('Chưa có lịch đã lưu',{exact:true}).count()>0);assert.ok(await page.getByText('Không có lịch trong tháng này',{exact:true}).count()>0);}else{assert.equal(await page.getByLabel('Tháng in',{exact:true}).inputValue(),'2026-09');assert.ok(new URL(page.url()).searchParams.get('scope')==='month');}await paper(page);if(artifacts&&detail)await page.locator('.schedule-print-sheet').first().screenshot({path:join(artifacts,'vi-detail.png')});await page.emulateMedia({media:'screen'});await page.getByRole('button',{name:'한국어',exact:true}).click();assert.equal((await snapshot(page)).html,ko.html);}finally{await page.close();}}});
    await t.test('localized print/PDF actions keep four pages and a real local A4 PDF retains Vietnamese accents',async()=>{const page=await open();try{await page.getByRole('button',{name:'Tiếng Việt',exact:true}).click();translated(await snapshot(page));await page.getByRole('button',{name:'Lưu PDF',exact:true}).click();await page.waitForFunction(()=>(globalThis as any).cf210.printCalls.length===1);assert.ok((await page.locator('.schedule-print-pdf-guide').innerText()).includes('Trong cửa sổ in'));await page.getByRole('button',{name:'Xác nhận',exact:true}).click();await page.getByRole('button',{name:'In',exact:true}).click();await page.waitForFunction(()=>(globalThis as any).cf210.printCalls.length===2);assert.deepEqual(await page.evaluate(()=>(globalThis as any).cf210.printCalls),[4,4]);await paper(page);const path=artifacts?join(artifacts,'CF210-local-synthetic-vi.pdf'):undefined,bytes=await page.pdf({...(path?{path}:{}),format:'A4',landscape:true,preferCSSPageSize:true,printBackground:true});if(path&&artifacts)execFileSync(process.env.CF210_PDFTOPPM??'pdftoppm',['-png','-r','100',path,join(artifacts,'vi-pdf')],{stdio:'pipe'});await inspectPdf(new Uint8Array(bytes),page,path);if(artifacts)assert.equal(readdirSync(artifacts).filter(name=>/^vi-pdf-\d+\.png$/u.test(name)).length,4);await page.emulateMedia({media:'screen'});await page.getByRole('button',{name:'Đóng',exact:true}).click();assert.equal(await page.evaluate(()=>(globalThis as any).cf210.closed),1);assert.equal((await snapshot(page)).raw,(await snapshot(page)).original);}finally{await page.close();}});
    assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  }finally{await browser.close();await server.close();}
});
