import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import initSqlJs, { type Database } from 'sql.js';
import worker, { type CloudflareEnv } from '../apps/cloudflare/src/index.js';

const ADMIN_ID='00000000-0000-4000-8000-000000000001';
const PM_ID='00000000-0000-4000-8000-000000000002';
const CEO_ID='00000000-0000-4000-8000-000000000003';
const REVIEWER_ID='00000000-0000-4000-8000-000000000004';
const DEMO_CASE='40000000-0000-4000-8000-000000000010';
const PM_TOKEN='cf36-pm-session-token'; const CEO_TOKEN='cf36-ceo-session-token'; const REVIEWER_TOKEN='cf36-reviewer-session-token';
const migrations=['0001_cf_foundation.sql','0001_cf02_preview_drafts.sql','0002_cf03_preview_evidence.sql','0003_cf04_preview_auth.sql','0004_cf05_google_drive.sql','0005_cf06_case_operations.sql','0006_cf07_report_studio_drafts.sql','0007_cf08_report_review_approval.sql','0008_cf09_final_output.sql','0009_cf09_output_actor_scope.sql','0010_cf10_product_experience.sql','0011_cf11_project_workflow.sql','0012_cf12_report_ai_prompts.sql','0013_cf13_litigation_records.sql','0014_cf14_proposal_award_workflow.sql','0015_cf15_case_evidence_library.sql','0016_cf18_report_outline_evidence.sql','0017_cf19_multi_provider_ai.sql','0018_cf26_ai_credentials.sql','0019_cf27_proposal_authoring.sql','0020_cf28_workspace_settings.sql','0021_cf29_report_memory_learning.sql','0022_cf30_settings_template_preview.sql','0023_cf31_google_oauth_app_settings.sql','0024_cf32_source_template_library.sql','0025_cf33_type_authoring_guidelines.sql','0026_cf34_hermes_memory_architecture.sql','0027_cf35_guided_workspace.sql','0028_cf36_workflow_integrity_tutorial_approval_intake.sql'];
const migration=(name:string)=>readFileSync(join(process.cwd(),'apps','cloudflare','migrations',name),'utf8');
async function sha(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}

class SqlStatement { private values:unknown[]=[]; constructor(private db:Database,private sql:string){} bind(...values:unknown[]){this.values=values;return this;} async first<T>(){const s=this.db.prepare(this.sql);try{s.bind(this.values as any[]);return s.step()?s.getAsObject() as T:null;}finally{s.free();}} async all<T>(){const s=this.db.prepare(this.sql);const results:T[]=[];try{s.bind(this.values as any[]);while(s.step())results.push(s.getAsObject() as T);return{results};}finally{s.free();}} async run(){this.db.run(this.sql,this.values as any[]);const last=this.db.exec('SELECT last_insert_rowid()')[0]?.values[0]?.[0]??0;return{success:true,meta:{changes:this.db.getRowsModified(),last_row_id:Number(last)}};} }
class SqlD1 { constructor(private db:Database){} prepare(sql:string){return new SqlStatement(this.db,sql);} async batch(statements:SqlStatement[]){this.db.run('BEGIN IMMEDIATE');try{const results=[];for(const statement of statements)results.push(await statement.run());this.db.run('COMMIT');return results;}catch(error){this.db.run('ROLLBACK');throw error;}} }

const request=(path:string,token='',init:RequestInit={})=>{const headers=new Headers(init.headers);if(token)headers.set('X-Session-Token',token);if(init.body&&!(init.body instanceof FormData))headers.set('Content-Type','application/json');return new Request(`https://preview.example${path}`,{...init,headers});};
async function setup(){const SQL=await initSqlJs();const db=new SQL.Database();db.run('PRAGMA foreign_keys=ON');for(const name of migrations){db.exec(migration(name));if(name==='0009_cf09_output_actor_scope.sql'){const now='2026-08-20T00:00:00.000Z';const add=(id:string,login:string,nameText:string,roles:string)=>db.run('INSERT INTO preview_users (id,login_id,password_salt,password_hash,password_iterations,display_name,email,roles_json,is_active,created_at) VALUES (?,?,?,?,?,?,?,?,1,?)',[id,login,'1'.repeat(32),'2'.repeat(64),100000,nameText,`${login}@example.invalid`,roles,now]);add(ADMIN_ID,'admin','관리자','["admin"]');add(PM_ID,'pm','프로젝트 PM','["pm"]');add(CEO_ID,'ceo','현동명 대표','["ceo"]');add(REVIEWER_ID,'reviewer','검토자','["reviewer"]');}}
  const now='2026-08-20T01:00:00.000Z';for(const[token,id]of[[PM_TOKEN,PM_ID],[CEO_TOKEN,CEO_ID],[REVIEWER_TOKEN,REVIEWER_ID]] as const)db.run('INSERT INTO preview_sessions VALUES (?,?,?,?)',[await sha(token),id,now,'2099-01-01T00:00:00.000Z']);return{db,env:{DB:new SqlD1(db) as unknown as NonNullable<CloudflareEnv['DB']>}};}

test('CF36 schedule is projected from accepted D1 projects only, not static sample arrays',async()=>{const{db,env}=await setup();let response=await worker.fetch(request('/api/project-workflow/schedule',PM_TOKEN),env);assert.equal(response.status,200);let body=await response.json() as any;assert.equal(body.dataBasis,'REAL_D1_WORKFLOW_RECORDS');assert.equal(body.projects.some((row:any)=>row.caseId===DEMO_CASE),false);const caseRow=db.exec('SELECT version,updated_at FROM preview_cases WHERE id=?',[DEMO_CASE])[0].values[0];const nextUpdatedAt=new Date(Date.parse(String(caseRow[1]))+1).toISOString();db.run("UPDATE preview_cases SET status='CONTRACT',version=version+1,updated_at=? WHERE id=? AND version=?",[nextUpdatedAt,DEMO_CASE,Number(caseRow[0])]);db.run("INSERT INTO preview_proposal_links (id,organization_id,case_id,proposal_number,proposal_title,revision_label,client_name,sent_at,proposed_amount_krw,verification_status,award_status,award_decided_at,award_decided_by,contract_amount_krw,project_start_on,project_end_on,version,request_key,request_fingerprint,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",['40000000-0000-4000-8000-000000000036','concost',DEMO_CASE,'PROP-CF36-WON','수주 확정 일정표 검증','V1','합성 발주처','2026-08-20T02:00:00.000Z',null,'UNVERIFIED','WON','2026-08-20T02:00:00.000Z',PM_ID,1,'2026-08-20','2026-08-20',2,'cf36-won-project-seed','a'.repeat(64),PM_ID,'2026-08-20T02:00:00.000Z','2026-08-20T02:00:00.000Z']);response=await worker.fetch(request('/api/project-workflow/schedule',PM_TOKEN),env);body=await response.json() as any;const project=body.projects.find((row:any)=>row.caseId===DEMO_CASE);assert.ok(project);assert.equal(project.stages.length,6);assert.deepEqual(project.stages.map((row:any)=>row.stageId),[1,2,3,4,5,6]);assert.ok(project.stages.every((row:any)=>typeof row.detail==='string'&&row.detail.length>0));const source=readFileSync('apps/web/src/workflow/ProjectWorkflowSchedule.tsx','utf8');assert.doesNotMatch(source,/WORKFLOW_PROJECTS/u);assert.match(source,/\/api\/project-workflow\/schedule/u);db.close();});

test('CF36 first-login guide records a one-time skip/completion decision per user',async()=>{const{db,env}=await setup();const initial=await worker.fetch(request('/api/settings/tutorial',PM_TOKEN),env);assert.equal(initial.status,200);const initialBody=await initial.json() as any;assert.equal(initialBody.currentTutorialVersion,'CF36_V1');assert.equal(initialBody.tutorial.completionAction,null);const skipped=await worker.fetch(request('/api/settings/tutorial',PM_TOKEN,{method:'PUT',body:JSON.stringify({tutorialVersion:'CF36_V1',expectedVersion:0,action:'SKIPPED'})}),env);assert.equal(skipped.status,200);assert.equal((await skipped.json() as any).tutorial.completionAction,'SKIPPED');assert.equal(db.exec("SELECT completion_action FROM preview_user_tutorial_history WHERE user_id='00000000-0000-4000-8000-000000000002'")[0].values[0][0],'SKIPPED');assert.throws(()=>db.run("UPDATE preview_user_tutorial_history SET completion_action='COMPLETED'"),/append-only/u);db.close();});

test('CF36 only CEO/Director can finally approve and approval atomically creates PM app notification plus email outbox',async()=>{const{db,env}=await setup();const now='2026-08-20T02:00:00.000Z';const revision='70000000-0000-4000-8000-000000000001';db.run('INSERT INTO preview_report_drafts (case_id,organization_id,title,content,version,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,?,1,?,?,?,?)',[DEMO_CASE,'concost','최종 보고서','근거가 포함된 최종 보고서 본문',PM_ID,PM_ID,now,now]);db.run('INSERT INTO preview_report_revisions (id,case_id,version,title,content,content_sha256,saved_by,saved_at) VALUES (?,?,1,?,?,?,?,?)',[revision,DEMO_CASE,'최종 보고서','근거가 포함된 최종 보고서 본문','a'.repeat(64),PM_ID,now]);const submitted=await worker.fetch(request('/api/report-reviews',PM_TOKEN,{method:'POST',headers:{'Idempotency-Key':'cf36-review-request-1'},body:JSON.stringify({caseId:DEMO_CASE,expectedVersion:1,note:'최종 결재 요청'})}),env);assert.equal(submitted.status,201);const review=(await submitted.json() as any).reviews[0];const decisionBody=JSON.stringify({decision:'APPROVED',note:'납품 승인',expectedStatus:'PENDING'});const reviewerDenied=await worker.fetch(request(`/api/report-reviews/${review.id}/decision`,REVIEWER_TOKEN,{method:'POST',body:decisionBody}),env);assert.equal(reviewerDenied.status,403);assert.equal((await reviewerDenied.json() as any).code,'FINAL_APPROVER_REQUIRED');const approved=await worker.fetch(request(`/api/report-reviews/${review.id}/decision`,CEO_TOKEN,{method:'POST',body:decisionBody}),env);assert.equal(approved.status,200);const approvedReview=(await approved.json() as any).reviews[0];assert.equal(approvedReview.status,'APPROVED');assert.equal(approvedReview.deliveryNotification.emailStatus,'CONFIG_REQUIRED');assert.equal(db.exec('SELECT COUNT(*) FROM preview_notifications')[0].values[0][0],1);assert.equal(db.exec("SELECT status FROM preview_email_outbox")[0].values[0][0],'CONFIG_REQUIRED');const inbox=await worker.fetch(request('/api/notifications',PM_TOKEN),env);assert.equal(inbox.status,200);assert.match((await inbox.text()),/납품 필요/u);assert.throws(()=>db.run("UPDATE preview_report_reviews SET reviewed_by='00000000-0000-4000-8000-000000000004' WHERE id=?",[review.id]),/identity|decision|append|terminal|review|CEO|Director/u);db.close();});

test('CF36 client perspective and intake sources are mandatory report-grounding inputs',async()=>{const{db,env}=await setup();db.run("UPDATE preview_cases SET client_legal_position='SUSPECT',client_position_detail='피고 시공사 입장에서 사실관계와 방어 논리를 작성',version=version+1,updated_at='2098-01-01T00:00:00.000Z' WHERE id=?",[DEMO_CASE]);const caseResponse=await worker.fetch(request(`/api/cases/${DEMO_CASE}`,PM_TOKEN),env);assert.equal(caseResponse.status,200);const caseBody=await caseResponse.json() as any;assert.equal(caseBody.case.clientLegalPosition,'SUSPECT');assert.equal(caseBody.case.clientPositionDetail,'피고 시공사 입장에서 사실관계와 방어 논리를 작성');const workerSource=readFileSync('apps/cloudflare/src/index.ts','utf8');for(const marker of ['clientPerspective','intakeSourceSummaries','mandatoryRule','INTAKE_SOURCE','inline_data'])assert.match(workerSource,new RegExp(marker));db.close();});

test('CF36 court dashboard remains an internal verified-source D1 system and creates project court schedules only from verified records',()=>{const source=readFileSync('apps/cloudflare/src/index.ts','utf8');for(const marker of ['preview_litigation_cases','preview_litigation_events','official_source_url','verification_status','createCourtSchedule'])assert.match(source,new RegExp(marker));assert.doesNotMatch(source,/court\.go\.kr.*fetch|fetch.*court\.go\.kr/u);});
