import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import initSqlJs, { type Database } from 'sql.js';
import worker, { type CloudflareEnv } from '../apps/cloudflare/src/index.js';
import { proposalStudioWorkbook, readProposalDocx, readProposalStudioWorkbook, type ProposalStudioExcelValues } from '../apps/web/src/proposals/proposal-excel.js';

const read=(path:string)=>readFileSync(join(process.cwd(),path),'utf8');
const ADMIN='00000000-0000-4000-8000-000000000042'; const REVIEWER='00000000-0000-4000-8000-000000000043'; const ADMIN_TOKEN='cf42-admin-session-token'; const REVIEW_TOKEN='cf42-review-session-token';
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join('');}
class SqlStatement{private values:unknown[]=[];constructor(private readonly db:Database,private readonly sql:string){}bind(...values:unknown[]){this.values=values;return this;}async first<T>():Promise<T|null>{const statement=this.db.prepare(this.sql);try{statement.bind(this.values as any[]);return statement.step()?statement.getAsObject() as T:null;}finally{statement.free();}}async all<T>():Promise<{results:T[]}>{const statement=this.db.prepare(this.sql);const results:T[]=[];try{statement.bind(this.values as any[]);while(statement.step())results.push(statement.getAsObject() as T);return{results};}finally{statement.free();}}async run(){this.db.run(this.sql,this.values as any[]);const row=this.db.exec('SELECT last_insert_rowid() AS id')[0]?.values[0]?.[0];return{success:true,meta:{changes:this.db.getRowsModified(),last_row_id:Number(row??0)}};}}
class SqlD1{constructor(readonly database:Database){}prepare(sql:string){return new SqlStatement(this.database,sql);}async batch(statements:SqlStatement[]){this.database.run('BEGIN IMMEDIATE');try{const results=[];for(const statement of statements)results.push(await statement.run());this.database.run('COMMIT');return results;}catch(reason){this.database.run('ROLLBACK');throw reason;}}}
const request=(path:string,token=ADMIN_TOKEN,init:RequestInit={})=>{const headers=new Headers(init.headers);headers.set('X-Session-Token',token);if(init.body)headers.set('Content-Type','application/json');return new Request(`https://preview.example${path}`,{...init,headers});};
async function setup(){const SQL=await initSqlJs();const sql=new SQL.Database();sql.run('PRAGMA foreign_keys=ON');for(const name of ['0001_cf_foundation.sql','0001_cf02_preview_drafts.sql','0002_cf03_preview_evidence.sql','0003_cf04_preview_auth.sql','0004_cf05_google_drive.sql','0005_cf06_case_operations.sql','0019_cf27_proposal_authoring.sql','0033_cf42_proposal_studio.sql','0034_cf42_proposal_template_catalog.sql','0036_cf44_proposal_pdf_template_source.sql'])sql.exec(read(`apps/cloudflare/migrations/${name}`));const now=new Date().toISOString();for(const [id,login,name,roles] of [[ADMIN,'admin@example.invalid','CF42 Admin','["admin"]'],[REVIEWER,'reviewer@example.invalid','CF42 Reviewer','["reviewer"]']] as const)sql.run('INSERT INTO preview_users VALUES (?,?,?,?,?,?,?,?,1,?)',[id,login,'1'.repeat(32),'2'.repeat(64),100000,name,login,roles,now]);sql.run('INSERT INTO preview_sessions VALUES (?,?,?,?)',[await sha256(ADMIN_TOKEN),ADMIN,now,new Date(Date.now()+3_600_000).toISOString()]);sql.run('INSERT INTO preview_sessions VALUES (?,?,?,?)',[await sha256(REVIEW_TOKEN),REVIEWER,now,new Date(Date.now()+3_600_000).toISOString()]);return{sql,env:{DB:new SqlD1(sql) as unknown as NonNullable<CloudflareEnv['DB']>} as CloudflareEnv};}

test('CF44 stores the exact source template, masks costs, approves, and exports DOCX/PDF/Markdown',async()=>{
  const {sql,env}=await setup();
  const createdCase=await worker.fetch(request('/api/cases',ADMIN_TOKEN,{method:'POST',headers:{'Idempotency-Key':'cf42-case-create-0001'},body:JSON.stringify({title:'평택 세교 기술용역',claimType:'TYPE-03',description:'예상 용역대가 123,000,000원 검토',category:{major:'건설 클레임',middle:'TYPE-03',minor:'제안'}})}),env);assert.equal(createdCase.status,201,await createdCase.clone().text());const caseId=(await createdCase.json() as {case:{id:string}}).case.id;sql.run('INSERT INTO preview_case_assignments VALUES (?,?,?,?)',[caseId,REVIEWER,ADMIN,new Date().toISOString()]);
  const configResponse=await worker.fetch(request('/api/proposal-studio/config'),env);assert.equal(configResponse.status,200);const config=await configResponse.json() as {modules:Array<{code:string}>;sources:Array<{id:string;sourceName:string;isDefault:boolean}>};assert.equal(config.modules.length,8);assert.equal(config.sources.length,23);const defaultSource=config.sources.find((source)=>source.isDefault);assert.equal(defaultSource?.id,'CF42-SRC-260728');assert.equal(defaultSource?.sourceName,'260728 평택 세교1구역 리츠 HUG 대응 전력 용역제안서.hwp');
  const created=await worker.fetch(request(`/api/cases/${caseId}/proposals`,ADMIN_TOKEN,{method:'POST',body:JSON.stringify({templateId:'CF27-TYPE-03',sourceId:'CF42-SRC-260728'})}),env);assert.equal(created.status,201);let proposal=(await created.json() as {proposal:{id:string;version:number;currentVersionId:string;versions:Array<{structuredInputsJson:string;bodyText:string}>}}).proposal;const initial=JSON.parse(proposal.versions[0].structuredInputsJson) as {chapters:Array<{number:number}>;templateSourceId:string;templateSourceName:string};assert.equal(initial.chapters.length,12);assert.equal(initial.templateSourceId,'CF42-SRC-260728');assert.equal(initial.templateSourceName,defaultSource?.sourceName);assert.doesNotMatch(proposal.versions[0].bodyText,/123,000,000원/u);assert.match(proposal.versions[0].bodyText,/비공개 협의금액/u);
  const chapters=initial.chapters.map((chapter)=>({number:chapter.number,title:`제${chapter.number}장`,kind:chapter.number>=4&&chapter.number<=11?'FIXED':'VARIABLE',body:chapter.number===2?'제안금액: 98,000,000원 · 계약 쟁점':'사실에 근거한 충분한 제안서 본문입니다. 확인이 필요한 항목은 확인 필요로 표시합니다.'}));
  const saved=await worker.fetch(request(`/api/cases/${caseId}/proposals/${proposal.id}/versions`,ADMIN_TOKEN,{method:'POST',body:JSON.stringify({clientName:'세교1구역 조합',projectTitle:'평택 세교 기술용역 제안서',subtitle:'공사비 검증 및 협상 지원',submissionDate:'2026-08-21',keyIssues:'제안금액 98,000,000원과 단가조정',objective:'클라이언트 권익 보호',planNotes:'Fact Finding부터 협상 지원까지 수행',exclusions:'법률의견 제외',chapters,includedModuleCodes:config.modules.map((module)=>module.code),templateSourceId:'CF42-SRC-260728',generationMode:'MANUAL',sourceDocumentVersionIds:[],version:proposal.version})}),env);assert.equal(saved.status,200);proposal=(await saved.json() as {proposal:typeof proposal}).proposal;const savedInputs=JSON.parse(proposal.versions[0].structuredInputsJson) as {templateSourceId:string;templateSourceName:string};assert.equal(savedInputs.templateSourceId,'CF42-SRC-260728');assert.equal(savedInputs.templateSourceName,defaultSource?.sourceName);assert.doesNotMatch(proposal.versions[0].bodyText,/98,000,000원/u);assert.match(proposal.versions[0].bodyText,/비공개 협의금액/u);
  const review=await worker.fetch(request(`/api/cases/${caseId}/proposals/${proposal.id}/reviews`,ADMIN_TOKEN,{method:'POST',body:JSON.stringify({action:'REQUEST_REVIEW',comment:'검토 요청',versionId:proposal.currentVersionId,version:proposal.version})}),env);assert.equal(review.status,200);proposal=(await (await worker.fetch(request(`/api/cases/${caseId}/proposals/${proposal.id}`),env)).json() as {proposal:typeof proposal}).proposal;
  const approved=await worker.fetch(request(`/api/cases/${caseId}/proposals/${proposal.id}/reviews`,REVIEW_TOKEN,{method:'POST',body:JSON.stringify({action:'APPROVE',comment:'최종 승인',versionId:proposal.currentVersionId,version:proposal.version})}),env);assert.equal(approved.status,200);proposal=(await (await worker.fetch(request(`/api/cases/${caseId}/proposals/${proposal.id}`),env)).json() as {proposal:typeof proposal}).proposal;
  for(const format of ['docx','pdf','md'] as const){const exported=await worker.fetch(request(`/api/cases/${caseId}/proposals/${proposal.id}/render`,ADMIN_TOKEN,{method:'POST',body:JSON.stringify({format,versionId:proposal.currentVersionId,version:proposal.version})}),env);assert.equal(exported.status,200,await exported.clone().text());assert.match(exported.headers.get('content-disposition')??'',/attachment;.*filename\*=UTF-8''/iu);assert.match(exported.headers.get('content-type')??'',format==='docx'?/officedocument\.wordprocessingml\.document/iu:format==='pdf'?/application\/pdf/iu:/text\/markdown/iu);const bytes=new Uint8Array(await exported.arrayBuffer());assert.ok(bytes.byteLength>500,`${format} 승인본은 실제 파일 내용을 포함해야 합니다.`);const decoded=new TextDecoder().decode(bytes);if(format==='docx'){assert.deepEqual([...bytes.slice(0,4)],[0x50,0x4b,0x03,0x04]);assert.match(decoded,/\[Content_Types\]\.xml/u);assert.match(decoded,/word\/document\.xml/u);assert.match(decoded,/word\/styles\.xml/u);const docxBuffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;const imported=await readProposalDocx(new File([docxBuffer],'approved-proposal.docx'));assert.equal(imported.length,12);assert.match(imported[0].body,/사실에 근거한 충분한 제안서 본문/u);}else if(format==='pdf'){assert.deepEqual(new TextDecoder().decode(bytes.slice(0,8)),'%PDF-1.7');assert.match(decoded,/%CONCOST-PROPOSAL/u);assert.match(decoded,/%%EOF$/u);}else assert.match(decoded,/12\. 맺음말/u);assert.doesNotMatch(decoded,/98,000,000원/u);}
  assert.equal(sql.exec('SELECT COUNT(*) FROM preview_proposal_exports')[0].values[0][0],3);
  assert.equal(sql.exec("SELECT COUNT(*) FROM preview_proposal_exports WHERE export_format='PDF'")[0].values[0][0],1);
  assert.throws(()=>sql.run(`INSERT INTO preview_proposal_versions VALUES ('forged','${proposal.id}','${caseId}',99,'계약금액 1억원','{}','MANUAL',NULL,NULL,'${'a'.repeat(64)}','[]','[]','${'b'.repeat(64)}',0,'${ADMIN}','2026-08-21')`),/cost data must be masked/u);
  sql.close();
});

test('CF42 Excel input round-trips all standard proposal fields and UI exposes the real 4-step editor',async()=>{
  const source:ProposalStudioExcelValues={clientName:'세교1구역 조합',projectTitle:'공사비 검증 제안서',subtitle:'협상 지원 용역',submissionDate:'2026-08-21',keyIssues:'물가변동 기준일',objective:'조합 권익 보호',planNotes:'4단계 수행',exclusions:'법률의견 제외'};
  const bytes=proposalStudioWorkbook(source,'CC-2026-042 · 세교1구역','TYPE-03 12챕터');const buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;assert.deepEqual(await readProposalStudioWorkbook(new File([buffer],'proposal.xlsx')),source);
  const ui=read('apps/web/src/proposals/ProposalView.tsx');assert.match(ui,/Gemini가 가변 1·2·3·12장/u);assert.match(ui,/proposal-editor-grid/u);assert.match(ui,/Excel 양식 내보내기/u);assert.match(ui,/작성 Excel 가져오기/u);assert.match(ui,/Word DOCX 가져오기/u);assert.match(ui,/Word DOCX 내려받기/u);assert.match(ui,/관리자 · 회사 공통 고정 모듈 DB 편집/u);assert.match(ui,/내보내기 DB 이력/u);
  assert.match(ui,/템플릿 가져오기 · 원본 양식/u);assert.match(ui,/PDF 내려받기/u);assert.match(ui,/activeProposal\.status!==['"]DRAFT['"]/u);assert.match(ui,/기존 검토·승인본은 보존/u);
  assert.match(ui,/AiGenerationProgressModal/u);assert.match(ui,/setAiGeneration\(\{status:'running'\}\)/u);assert.match(ui,/회사 공통 모듈 최신본 일괄 적용/u);assert.match(ui,/applyLatestCompanyModules/u);assert.match(ui,/triggerBrowserDownload\(result\)/u);
  assert.match(ui,/독립 승인 대기 중/u);assert.match(ui,/다른 Reviewer·Director·CEO/u);assert.match(ui,/승인본 다운로드 준비 완료/u);
  const report=read('apps/web/src/routes/PreviewReportStudio.tsx');assert.match(report,/AiGenerationProgressModal/u);assert.match(report,/kind: 'outline', status: 'running'/u);assert.match(report,/kind: 'chapter', status: 'running'/u);assert.match(report,/kind: 'improve', status: 'running'/u);assert.match(report,/triggerBrowserDownload\(result\)/u);
  const modal=read('apps/web/src/components/AiGenerationProgressModal.tsx');assert.match(modal,/role="progressbar"/u);assert.match(modal,/setProgress\(100\)/u);assert.match(modal,/✓ \{confirmLabel\}/u);assert.match(modal,/Math\.min\(92/u);
  const company=read('apps/cloudflare/src/proposal-company-content.ts');assert.match(company,/우동3구역 주택재개발/u);assert.match(company,/수원고등법원 2025나12266/u);assert.match(company,/\| 담당 \| 성명 \| 학력/u);assert.match(company,/\[비공개 협의금액\]/u);
  const docx=read('apps/cloudflare/src/proposal-docx.ts');assert.match(docx,/function markdownTable/u);assert.match(docx,/<w:tbl>/u);assert.match(ui,/ProposalRichContent/u);assert.match(ui,/완제품 구조 미리보기/u);assert.match(ui,/AI 자동 작성 · Gemini/u);
  const api=read('apps/web/src/api.ts');assert.match(api,/document\.body\.appendChild\(anchor\)/u);assert.match(api,/anchor\.remove\(\)/u);assert.match(api,/10_000/u);
  const shell=read('apps/web/src/layout/AppShell.tsx');const theme=read('apps/web/src/theme-system.css');assert.match(shell,/sidebar-resize-handle/u);assert.match(shell,/claim-center-sidebar-width/u);assert.match(shell,/if \(stored === null\) return SIDEBAR_DEFAULT_WIDTH/u);assert.match(theme,/\.sidebar \{ width: 352px/u);assert.match(theme,/\.case-create-page \{ width: 100%; max-width: 1480px/u);
});
