import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Button, Card, Dialog, Input, Select, StatusBadge, type StatusType } from '@claim-studio/ui';
import { apiDownloadPost, apiRequest } from '../api';
import {
  proposalStudioWorkbook as proposalWorkbook,
  readProposalDocx,
  readProposalStudioWorkbook as readProposalWorkbook,
} from './proposal-excel';

export interface ProposalViewProps { routeId:string; roles:readonly string[]; onNavigate:(path:string)=>void }
interface CaseItem { id:string; caseNumber:string; title:string; description?:string|null; claimType:string; status:string }
interface ProposalTemplate { id:string; name:string; claimType:string; description:string; bodyTemplate:string; placeholdersJson:string }
interface ProposalChapter { number:number; title:string; kind:'VARIABLE'|'FIXED'; moduleCode?:string; body:string }
interface CompanyModule { code:string; chapterNumber:number; title:string; category:string; bodyMarkdown:string; isActive:boolean; version:number; updatedAt:string }
interface TemplateSource { id:string; sourceName:string; sourceFormat:string; sourceDate:string; isDefault:boolean; analysisStatus:string; chapterMapJson:string; version:number }
interface ProposalVersion { id:string; versionNumber:number; bodyText:string; structuredInputsJson:string; generationMode:string; providerId:string|null; modelId:string|null; inputSha256:string; sourceDocumentVersionIdsJson:string|null; sha256:string; isApproved:boolean; createdAt:string; createdBy?:{id:string;name:string} }
interface ProposalReview { id:string; action:string; comment:string|null; createdAt:string; reviewer:{id:string;name:string} }
interface ProposalExport { id:string;versionId:string;format:string;fileName:string;sha256:string;sanitizationCount:number;createdAt:string }
interface Proposal { id:string;caseId:string;templateId:string;title:string;status:string;currentVersionId:string|null;approvedVersionId:string|null;version:number;template?:ProposalTemplate;versions?:ProposalVersion[];reviews?:ProposalReview[];exports?:ProposalExport[] }
interface StudioInputs { clientName:string;projectTitle:string;subtitle:string;submissionDate:string;keyIssues:string;objective:string;planNotes:string;exclusions:string;chapters:ProposalChapter[];includedModuleCodes:string[];templateSourceId?:string;templateSourceName?:string }

const chapterTitles=['제안(용역)의 목적','당 현장의 핵심 쟁점 분석','업무 수행 내용 및 추진 계획','전문가 현황','당사의 강점','조직도 및 업무 영역','도시정비사업 공사비검증 실적','한국부동산원 공사비검증 실적','건설 클레임·소송·기술감정 실적','자격 증명자료','용역 조건 및 제안 범위','맺음말'];
const blankChapters=():ProposalChapter[]=>chapterTitles.map((title,index)=>({number:index+1,title,kind:index>=3&&index<=10?'FIXED':'VARIABLE',body:'[작성 필요]'}));
const parseArray=(value:string|null|undefined):string[]=>{try{const parsed:unknown=JSON.parse(value??'[]');return Array.isArray(parsed)&&parsed.every((item)=>typeof item==='string')?parsed:[];}catch{return[];}};
const statusBadge=(status:string):StatusType=>['draft','in_review','approved','rejected'].includes(status.toLowerCase())?status.toLowerCase() as StatusType:'unwritten';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

export const ProposalView:React.FC<ProposalViewProps>=({routeId,roles,onNavigate})=>{
  const requestedCaseId=new URLSearchParams(window.location.search).get('caseId')??'';
  const fromIntake=new URLSearchParams(window.location.search).get('from')==='intake';
  const [cases,setCases]=useState<CaseItem[]>([]); const [selectedCaseId,setSelectedCaseId]=useState(requestedCaseId);
  const [templates,setTemplates]=useState<ProposalTemplate[]>([]); const [selectedTemplateId,setSelectedTemplateId]=useState('');
  const [proposals,setProposals]=useState<Proposal[]>([]); const [activeProposal,setActiveProposal]=useState<Proposal|null>(null);
  const [modules,setModules]=useState<CompanyModule[]>([]); const [sources,setSources]=useState<TemplateSource[]>([]);
  const [selectedTemplateSourceId,setSelectedTemplateSourceId]=useState('');
  const [step,setStep]=useState(1); const [selectedChapter,setSelectedChapter]=useState(1); const [templatePreview,setTemplatePreview]=useState(false);
  const [clientName,setClientName]=useState(''); const [projectTitle,setProjectTitle]=useState(''); const [subtitle,setSubtitle]=useState('건설 클레임 전문용역 제안'); const [submissionDate,setSubmissionDate]=useState(today());
  const [keyIssues,setKeyIssues]=useState(''); const [objective,setObjective]=useState(''); const [planNotes,setPlanNotes]=useState(''); const [exclusions,setExclusions]=useState('해당 없음');
  const [chapters,setChapters]=useState<ProposalChapter[]>(blankChapters); const [includedModuleCodes,setIncludedModuleCodes]=useState<string[]>([]); const [sourceDocumentVersionIds,setSourceDocumentVersionIds]=useState('');
  const [reviewComment,setReviewComment]=useState(''); const [errorMessage,setErrorMessage]=useState<string|null>(null); const [successMessage,setSuccessMessage]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const [selectedModuleCode,setSelectedModuleCode]=useState(''); const [moduleTitle,setModuleTitle]=useState(''); const [moduleBody,setModuleBody]=useState(''); const [moduleActive,setModuleActive]=useState(true);
  const excelInputRef=useRef<HTMLInputElement>(null); const docxInputRef=useRef<HTMLInputElement>(null);
  const canEdit=roles.some((role)=>['ceo','director','pm','admin'].includes(role)); const canApprove=roles.some((role)=>['reviewer','director','ceo','admin'].includes(role)); const canManageModules=roles.includes('admin');

  const applyVersion=useCallback((version:ProposalVersion|undefined,caseRow?:CaseItem)=>{
    if(!version){setChapters(blankChapters());return;}
    try{
      const parsed=JSON.parse(version.structuredInputsJson) as Partial<StudioInputs>&Record<string,unknown>;
      if(Array.isArray(parsed.chapters)&&parsed.chapters.length===12){
        setClientName(String(parsed.clientName??''));setProjectTitle(String(parsed.projectTitle??caseRow?.title??''));setSubtitle(String(parsed.subtitle??'건설 클레임 전문용역 제안'));setSubmissionDate(String(parsed.submissionDate??today()));
        setKeyIssues(String(parsed.keyIssues??''));setObjective(String(parsed.objective??''));setPlanNotes(String(parsed.planNotes??''));setExclusions(String(parsed.exclusions??'해당 없음'));
        setChapters(parsed.chapters as ProposalChapter[]);setIncludedModuleCodes(Array.isArray(parsed.includedModuleCodes)?parsed.includedModuleCodes.filter((item):item is string=>typeof item==='string'):[]);if(typeof parsed.templateSourceId==='string')setSelectedTemplateSourceId(parsed.templateSourceId);
      }else{
        const next=blankChapters();next[0].body=`${String(parsed.background??'')}\n\n${String(parsed.objective??'')}`.trim();next[2].body=String(parsed.method??'');next[11].body=`${String(parsed.expectedOutcome??'')}\n\n제외사항: ${String(parsed.exclusions??'')}`;
        setClientName('');setProjectTitle(`${caseRow?.title??'프로젝트'} 기술용역 제안서`);setObjective(String(parsed.objective??''));setPlanNotes(String(parsed.method??''));setExclusions(String(parsed.exclusions??'해당 없음'));setChapters(next);
      }
      setSourceDocumentVersionIds(parseArray(version.sourceDocumentVersionIdsJson).join(', '));
    }catch{setChapters(blankChapters());}
  },[]);

  const loadProposalDetail=useCallback(async(cId:string,pId:string)=>{const response=await apiRequest<{proposal:Proposal}>(`/api/cases/${cId}/proposals/${pId}`);setActiveProposal(response.proposal);applyVersion(response.proposal.versions?.[0],cases.find((item)=>item.id===cId));},[applyVersion,cases]);
  const loadCaseData=useCallback(async(cId:string)=>{if(!cId)return;const caseRow=cases.find((item)=>item.id===cId);const query=caseRow?`?claimType=${caseRow.claimType}`:'';try{const [templateResult,proposalResult]=await Promise.all([apiRequest<{templates:ProposalTemplate[]}>(`/api/proposal-templates${query}`),apiRequest<{proposals:Proposal[]}>(`/api/cases/${cId}/proposals`)]);setTemplates(templateResult.templates??[]);setSelectedTemplateId(templateResult.templates?.[0]?.id??'');setProposals(proposalResult.proposals??[]);if(proposalResult.proposals?.length)await loadProposalDetail(cId,proposalResult.proposals[0].id);else{setActiveProposal(null);setProjectTitle(`${caseRow?.title??''} 기술용역 제안서`);setObjective(caseRow?.description??'');setChapters(blankChapters());setStep(1);}}catch(reason){setErrorMessage(reason instanceof Error?reason.message:'제안서 데이터를 불러오지 못했습니다.');}},[cases,loadProposalDetail]);
  useEffect(()=>{void Promise.all([apiRequest<{cases:CaseItem[]}>('/api/cases'),apiRequest<{modules:CompanyModule[];sources:TemplateSource[]}>('/api/proposal-studio/config')]).then(([res,config])=>{setCases(res.cases??[]);setModules(config.modules??[]);setSources(config.sources??[]);setSelectedTemplateSourceId((current)=>current||config.sources?.find((source)=>source.isDefault)?.id||config.sources?.[0]?.id||'');setIncludedModuleCodes((config.modules??[]).filter((module)=>module.isActive).map((module)=>module.code));setSelectedCaseId((current)=>{const preferred=current||requestedCaseId;return res.cases.some((item) => item.id === preferred)?preferred:res.cases?.[0]?.id??'';});}).catch((reason:Error)=>setErrorMessage(reason.message));},[]);
  useEffect(()=>{if(selectedCaseId)void loadCaseData(selectedCaseId);},[selectedCaseId,loadCaseData]);
  useEffect(()=>{const selected=modules.find((module)=>module.code===selectedModuleCode)??modules[0];if(!selected)return;if(selected.code!==selectedModuleCode)setSelectedModuleCode(selected.code);setModuleTitle(selected.title);setModuleBody(selected.bodyMarkdown);setModuleActive(selected.isActive);},[modules,selectedModuleCode]);

  const createProposal=async()=>{if(!selectedCaseId||!selectedTemplateId||!selectedTemplateSourceId)return;setBusy(true);setErrorMessage(null);try{const result=await apiRequest<{proposal:Proposal}>(`/api/cases/${selectedCaseId}/proposals`,{method:'POST',body:JSON.stringify({templateId:selectedTemplateId,sourceId:selectedTemplateSourceId})});await loadCaseData(selectedCaseId);await loadProposalDetail(selectedCaseId,result.proposal.id);setStep(1);setSuccessMessage('선택한 실무 템플릿으로 12개 챕터 제안서 작업공간을 만들었습니다. 1단계 입력부터 진행하세요.');onNavigate(`/proposals/editor?caseId=${encodeURIComponent(selectedCaseId)}`);}catch(reason){setErrorMessage(reason instanceof Error?reason.message:'제안서를 만들지 못했습니다.');}finally{setBusy(false);}};
  const preparedChapters=()=>chapters.map((chapter)=>chapter.number===1?{...chapter,body:objective}:chapter.number===2?{...chapter,body:keyIssues}:chapter.number===3?{...chapter,body:planNotes}:chapter);
  const saveVersion=async(generationMode:'MANUAL'|'AI')=>{
    if(!activeProposal||!selectedCaseId)return;
    if(![clientName,projectTitle,subtitle,submissionDate,keyIssues,objective,planNotes,exclusions].every((value)=>value.trim())){setErrorMessage('1단계의 클라이언트·프로젝트 정보와 핵심 쟁점·목적·수행 메모를 모두 입력하세요.');return;}
    setBusy(true);setErrorMessage(null);
    try{
      let target=activeProposal;
      let forked=false;
      if(activeProposal.status!=='DRAFT'){
        const created=await apiRequest<{proposal:Proposal}>(`/api/cases/${selectedCaseId}/proposals`,{method:'POST',body:JSON.stringify({templateId:activeProposal.templateId,sourceId:selectedTemplateSourceId})});
        target=created.proposal;forked=true;
      }
      await apiRequest(`/api/cases/${selectedCaseId}/proposals/${target.id}/versions`,{method:'POST',body:JSON.stringify({clientName,projectTitle,subtitle,submissionDate,keyIssues,objective,planNotes,exclusions,chapters:preparedChapters(),includedModuleCodes,templateSourceId:selectedTemplateSourceId,generationMode,sourceDocumentVersionIds:sourceDocumentVersionIds.split(',').map((item)=>item.trim()).filter(Boolean),version:target.version})});
      await loadCaseData(selectedCaseId);await loadProposalDetail(selectedCaseId,target.id);setStep(generationMode==='AI'?3:4);
      setSuccessMessage(`${forked?'기존 검토·승인본은 보존하고 편집용 새 초안을 만들었습니다. ':''}${generationMode==='AI'?'Gemini가 가변 1·2·3·12장 초안을 만들고 회사 DB 모듈을 병합했습니다.':'사람 검수본을 새 버전으로 저장했습니다.'}`);
    }catch(reason){setErrorMessage(reason instanceof Error?reason.message:'제안서 버전을 저장하지 못했습니다.');}finally{setBusy(false);}
  };
  const workflow=async(action:'REQUEST_REVIEW'|'APPROVE'|'REJECT')=>{if(!activeProposal||!selectedCaseId)return;setBusy(true);try{await apiRequest(`/api/cases/${selectedCaseId}/proposals/${activeProposal.id}/reviews`,{method:'POST',body:JSON.stringify({action,comment:reviewComment,versionId:activeProposal.currentVersionId,version:activeProposal.version})});await loadProposalDetail(selectedCaseId,activeProposal.id);setReviewComment('');setSuccessMessage('제안서 검토 상태를 갱신했습니다.');}catch(reason){setErrorMessage(reason instanceof Error?reason.message:'검토 상태를 바꾸지 못했습니다.');}finally{setBusy(false);}};
  const download=async(format:'docx'|'md'|'pdf')=>{if(!activeProposal||!selectedCaseId)return;setBusy(true);try{const result=await apiDownloadPost(`/api/cases/${selectedCaseId}/proposals/${activeProposal.id}/render`,{format,versionId:activeProposal.approvedVersionId,version:activeProposal.version});const url=URL.createObjectURL(result.blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=result.filename;anchor.click();URL.revokeObjectURL(url);await loadProposalDetail(selectedCaseId,activeProposal.id);setSuccessMessage(`${format.toUpperCase()} 승인본과 내보내기 해시를 DB 이력에 기록했습니다.`);}catch(reason){setErrorMessage(reason instanceof Error?reason.message:'제안서를 내려받지 못했습니다.');}finally{setBusy(false);}};
  const exportExcel=()=>{const selected=cases.find((item)=>item.id===selectedCaseId);const bytes=proposalWorkbook({clientName,projectTitle,subtitle,submissionDate,keyIssues,objective,planNotes,exclusions},`${selected?.caseNumber??''} · ${selected?.title??''}`,templates.find((item)=>item.id===selectedTemplateId)?.name??'컨코스트 12챕터');const payload=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;const url=URL.createObjectURL(new Blob([payload],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`${selected?.caseNumber??'PROJECT'}_제안서_입력양식.xlsx`;anchor.click();URL.revokeObjectURL(url);setSuccessMessage('Excel 양식을 내보냈습니다. C열 작성 후 다시 가져오면 1단계에 반영됩니다.');};
  const importExcel=async(file?:File)=>{if(!file)return;setBusy(true);try{const values=await readProposalWorkbook(file);setClientName(values.clientName);setProjectTitle(values.projectTitle);setSubtitle(values.subtitle);setSubmissionDate(values.submissionDate);setKeyIssues(values.keyIssues);setObjective(values.objective);setPlanNotes(values.planNotes);setExclusions(values.exclusions);setStep(1);setSuccessMessage('작성 Excel 가져오기 완료. 화면 확인 후 Gemini 초안 생성을 진행하세요.');}catch(reason){setErrorMessage(reason instanceof Error?reason.message:'Excel을 읽지 못했습니다.');}finally{setBusy(false);if(excelInputRef.current)excelInputRef.current.value='';}};
  const importDocx=async(file?:File)=>{if(!file)return;setBusy(true);try{const imported=await readProposalDocx(file);const body=(number:number)=>imported.find((chapter)=>chapter.number===number)?.body;setChapters((current)=>current.map((item)=>item.kind==='VARIABLE'&&body(item.number)?{...item,body:body(item.number)??item.body}:item));if(body(1))setObjective(body(1)??'');if(body(2))setKeyIssues(body(2)??'');if(body(3))setPlanNotes(body(3)??'');setSelectedChapter(1);setStep(3);setSuccessMessage(`Word 제안서에서 ${imported.length}개 챕터를 인식했습니다. 가변 1·2·3·12장만 가져왔으며 회사 고정 장은 승인 DB 원문을 유지합니다.`);}catch(reason){setErrorMessage(reason instanceof Error?reason.message:'Word 제안서를 읽지 못했습니다.');}finally{setBusy(false);if(docxInputRef.current)docxInputRef.current.value='';}};
  const saveCompanyModule=async()=>{const selected=modules.find((module)=>module.code===selectedModuleCode);if(!selected||!canManageModules)return;setBusy(true);setErrorMessage(null);try{const response=await apiRequest<{module:CompanyModule;sanitizationCount:number}>(`/api/proposal-studio/modules/${selected.code}`,{method:'PUT',body:JSON.stringify({title:moduleTitle,bodyMarkdown:moduleBody,isActive:moduleActive,version:selected.version})});setModules((current)=>current.map((module)=>module.code===response.module.code?response.module:module));setChapters((current)=>current.map((item)=>item.moduleCode===response.module.code?{...item,title:response.module.title,body:response.module.bodyMarkdown}:item));setSuccessMessage(`관리자 회사 DB 모듈 v${response.module.version} 저장 완료${response.sanitizationCount?` · 금액 ${response.sanitizationCount}건 비공개 처리`:''}.`);}catch(reason){setErrorMessage(reason instanceof Error?reason.message:'회사 DB 모듈을 저장하지 못했습니다.');}finally{setBusy(false);}};

  const selectedCase=cases.find((item)=>item.id===selectedCaseId);const currentVersion=activeProposal?.versions?.[0];const chapter=chapters[selectedChapter-1]??chapters[0];const selectedTemplateSource=sources.find((source)=>source.id===selectedTemplateSourceId);
  return <div className="proposal-view-container proposal-studio-v2">
    {errorMessage&&<Dialog isOpen title="제안서 작업 확인" onClose={()=>setErrorMessage(null)}><p className="error-text">{errorMessage}</p></Dialog>}
    {templatePreview&&<Dialog isOpen title="선택한 제안서 템플릿 구조" onClose={()=>setTemplatePreview(false)}><div className="proposal-template-dialog"><p><b>{selectedTemplateSource?.sourceName??'컨코스트 표준 템플릿'}</b><br/>원본의 개인정보와 금액은 공개하지 않고, 구조 분석본을 안전하게 적용합니다. 1·2·3·12장은 프로젝트에 맞춰 작성하고 4~11장은 승인된 회사 고정 원문을 병합합니다.</p><ol>{chapterTitles.map((title,index)=><li key={title}><b>{index+1}. {title}</b><span>{index<3||index===11?'Gemini 가변 작성':'관리자 승인 회사 DB 자동 병합'}</span></li>)}</ol><h4>등록된 원본 템플릿 카탈로그</h4><ul>{sources.map((source)=><li key={source.id}><button type="button" className={source.id===selectedTemplateSourceId?'is-selected':''} onClick={()=>setSelectedTemplateSourceId(source.id)}>{source.sourceName} · {source.sourceFormat}{source.isDefault?' · 기본·최신':''} · {source.analysisStatus==='ANALYZED'?'구조 분석 완료':'참조 등록'}</button></li>)}</ul></div></Dialog>}
    {successMessage&&<div className="proposal-success" role="status"><b>완료</b><span>{successMessage}</span><button type="button" onClick={()=>setSuccessMessage(null)}>닫기</button></div>}
    <Card title="현재 프로젝트 · 제안서 연결"><div className="proposal-project-bar"><Select label="프로젝트" value={selectedCaseId} onChange={(event)=>setSelectedCaseId(event.target.value)} options={cases.map((item)=>({value:item.id,label:`${item.caseNumber} · ${item.title}`}))}/>{proposals.length>0&&<Select label="저장된 제안서" value={activeProposal?.id??''} onChange={(event)=>void loadProposalDetail(selectedCaseId,event.target.value)} options={proposals.map((item)=>({value:item.id,label:`${item.title} · ${item.status} · 편집 v${item.version}`}))}/>}</div>{selectedCase&&<div className="proposal-project-context"><b>{fromIntake?'방금 등록한 프로젝트':'선택 프로젝트'}</b><strong>{selectedCase.caseNumber} · {selectedCase.title}</strong><span>{selectedCase.claimType} · {selectedCase.status}</span></div>}</Card>
    {(routeId==='PROP-01'||(!activeProposal && selectedCaseId))&&<Card title={routeId==='PROP-01'?'제안서 템플릿 선택':'제안서 작성 1단계 · 유형별 템플릿 선택'}><div className="proposal-template-pick"><Select label="프로젝트 유형 승인 템플릿" value={selectedTemplateId} onChange={(event)=>setSelectedTemplateId(event.target.value)} options={templates.map((item)=>({value:item.id,label:item.name}))}/><Select label="템플릿 가져오기 · 원본 양식" value={selectedTemplateSourceId} onChange={(event)=>setSelectedTemplateSourceId(event.target.value)} options={sources.map((source)=>({value:source.id,label:`${source.isDefault?'[기본·최신] ':''}${source.sourceName}`}))}/><Button variant="secondary" onClick={()=>setTemplatePreview(true)}>선택 템플릿 완제품 보기</Button><Button onClick={()=>void createProposal()} disabled={!canEdit||busy||!selectedTemplateId||!selectedTemplateSourceId}>선택 양식으로 제안서 시작</Button></div><p className="muted">기본값은 260728 평택 세교1구역 리츠 HUG 대응 전력 용역제안서입니다. 가변 장만 Gemini가 작성하고 전문가 현황부터 용역조건까지는 회사 고정 DB를 유지합니다.</p></Card>}
    {activeProposal&&<Card title={`${activeProposal.title} · 4단계 제안서 스튜디오`} className="proposal-step-card">
      <div className="proposal-status-row"><StatusBadge status={statusBadge(activeProposal.status)}/><span>저장 버전 v{currentVersion?.versionNumber??1}</span><span>DB 편집 버전 {activeProposal.version}</span>{currentVersion?.generationMode==='AI'&&<StatusBadge status="ai_draft"/>}</div>
      <nav className="proposal-four-steps" aria-label="제안서 4단계">{[['01','입력','클라이언트·쟁점'],['02','AI 초안','Gemini+회사 DB'],['03','사람 검수','12챕터 편집'],['04','승인·보관','DOCX·MD·DB']].map((item,index)=><button key={item[0]} className={`proposal-step-button ${step===index+1?'active':''}`} onClick={()=>setStep(index+1)}><b>{item[0]}</b><span>{item[1]}</span><small>{item[2]}</small></button>)}</nav>
      <section className="proposal-template-import"><div><b>템플릿 가져오기</b><span>실무 원본 양식을 선택하면 다음 초안과 Gemini 작성 기준에 적용됩니다.</span></div><Select label="적용할 원본 템플릿" value={selectedTemplateSourceId} onChange={(event)=>setSelectedTemplateSourceId(event.target.value)} options={sources.map((source)=>({value:source.id,label:`${source.isDefault?'[기본·최신] ':''}${source.sourceName}`}))}/><Button variant="secondary" onClick={()=>setTemplatePreview(true)}>구조·고정구간 확인</Button></section><section className="proposal-excel-workflow"><div><b>현장 작성·기존 문서 가져오기</b><span>Excel 입력 양식과 Word 12챕터 본문을 가져옵니다. 금액은 서버에서 다시 마스킹합니다.</span></div><div className="action-row"><Button variant="secondary" onClick={exportExcel}>Excel 양식 내보내기</Button><input ref={excelInputRef} hidden type="file" accept=".xlsx" onChange={(event)=>void importExcel(event.target.files?.[0])}/><Button variant="secondary" onClick={()=>excelInputRef.current?.click()} disabled={busy}>작성 Excel 가져오기</Button><input ref={docxInputRef} hidden type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event)=>void importDocx(event.target.files?.[0])}/><Button variant="secondary" onClick={()=>docxInputRef.current?.click()} disabled={busy}>Word DOCX 가져오기</Button></div></section>
      {step===1&&<div className="proposal-stage proposal-stage-input"><header><b>STEP 1</b><h3>클라이언트와 프로젝트 사실을 입력하세요.</h3><p>이 내용이 갑지와 Gemini 초안의 기준입니다. 모르면 추측하지 말고 ‘확인 필요’라고 적으세요.</p></header><div className="proposal-input-grid"><Input label="클라이언트명" value={clientName} onChange={(event)=>setClientName(event.target.value)}/><Input label="프로젝트 제목" value={projectTitle} onChange={(event)=>setProjectTitle(event.target.value)}/><Input label="제안서 부제" value={subtitle} onChange={(event)=>setSubtitle(event.target.value)}/><Input label="제출일" type="date" value={submissionDate} onChange={(event)=>setSubmissionDate(event.target.value)}/><label className="proposal-field wide"><span>핵심 쟁점 3~5개</span><textarea value={keyIssues} onChange={(event)=>setKeyIssues(event.target.value)} placeholder="계약조건, 물가변동 기준일, 단가조정 등 확인된 사실"/></label><label className="proposal-field"><span>제안 목적·의뢰 배경</span><textarea value={objective} onChange={(event)=>setObjective(event.target.value)}/></label><label className="proposal-field"><span>수행 계획 메모</span><textarea value={planNotes} onChange={(event)=>setPlanNotes(event.target.value)}/></label><label className="proposal-field wide"><span>제외·추가 확인 사항</span><textarea value={exclusions} onChange={(event)=>setExclusions(event.target.value)}/></label></div><div className="proposal-next"><Button onClick={()=>setStep(2)}>입력 완료 · AI 초안 단계 →</Button></div></div>}
      {step===2&&<div className="proposal-stage proposal-ai-stage"><header><b>STEP 2</b><h3>Gemini가 가변 챕터를 쓰고 회사 DB를 병합합니다.</h3><p>1·2·3·12장은 프로젝트 사실로 생성하고, 4~11장은 아래 승인 모듈을 그대로 사용합니다.</p></header><div className="proposal-ai-map"><div><b>Gemini 가변 작성</b><strong>01 · 02 · 03 · 12장</strong><span>목적, 핵심 쟁점, 수행계획, 맺음말</span></div><div><b>회사 DB 자동 병합</b><strong>04 ~ 11장</strong><span>전문가, 강점, 조직, 실적, 자격, 용역조건</span></div><div><b>보안 필터</b><strong>금액 3중 마스킹</strong><span>AI 응답 → 서버 → D1 Trigger</span></div></div><label className="proposal-field"><span>근거 DocumentVersion ID (선택, 쉼표 구분)</span><textarea value={sourceDocumentVersionIds} onChange={(event)=>setSourceDocumentVersionIds(event.target.value)} placeholder="DOCVER-..."/></label><div className="proposal-next"><Button variant="secondary" onClick={()=>setStep(1)}>← 입력 수정</Button><Button onClick={()=>void saveVersion('AI')} disabled={busy||!canEdit}>Gemini 12챕터 초안 생성</Button></div></div>}
      {step===3&&<div className="proposal-stage proposal-editor-stage"><header><b>STEP 3</b><h3>목차를 눌러 한 챕터씩 사람 검수하세요.</h3><p>가변 장은 직접 수정합니다. 회사 고정 장은 오른쪽에서 포함 여부만 선택합니다.</p></header><div className="proposal-editor-grid"><aside className="proposal-toc" aria-label="12개 챕터 목차">{chapters.map((item)=><button key={item.number} className={selectedChapter===item.number?'active':''} onClick={()=>setSelectedChapter(item.number)}><b>{String(item.number).padStart(2,'0')}</b><span>{item.title}</span><small>{item.kind==='FIXED'?'회사 DB':'프로젝트 작성'}</small></button>)}</aside><main className="proposal-chapter-editor"><div><span>{chapter.kind==='FIXED'?'ADMIN APPROVED MODULE':'HUMAN REVIEW'}</span><h3>{chapter.number}. {chapter.title}</h3></div><textarea aria-label={`${chapter.title} 본문`} value={chapter.body} readOnly={chapter.kind==='FIXED'} onChange={(event)=>setChapters((current)=>current.map((item)=>item.number===chapter.number?{...item,body:event.target.value}:item))}/>{chapter.kind==='FIXED'&&<p>회사 고정 장은 관리자 승인 DB에서만 수정됩니다. 이 프로젝트 제안서에서는 원문 위조를 막기 위해 읽기 전용입니다.</p>}</main><aside className="proposal-module-panel"><h4>회사 실적 모듈</h4><p>프로젝트에 필요한 모듈만 켜세요.</p>{modules.map((module)=><label key={module.code}><input type="checkbox" checked={includedModuleCodes.includes(module.code)} onChange={(event)=>setIncludedModuleCodes((current)=>event.target.checked?[...new Set([...current,module.code])]:current.filter((code)=>code!==module.code))}/><span><b>{module.chapterNumber}. {module.title}</b><small>승인 DB v{module.version}</small></span></label>)}</aside></div>{canManageModules&&<section className="proposal-admin-module-editor"><div><b>관리자 · 회사 고정 모듈 DB 편집</b><span>저장하면 모든 신규 제안서의 4~11장에 적용됩니다. 금액은 자동 비공개 처리됩니다.</span></div><Select label="편집할 고정 챕터" value={selectedModuleCode} onChange={(event)=>setSelectedModuleCode(event.target.value)} options={modules.map((module)=>({value:module.code,label:`${module.chapterNumber}. ${module.title} · v${module.version}`}))}/><Input label="챕터 제목" value={moduleTitle} onChange={(event)=>setModuleTitle(event.target.value)}/><label className="proposal-field wide"><span>관리자 승인 본문</span><textarea value={moduleBody} onChange={(event)=>setModuleBody(event.target.value)}/></label><label className="proposal-module-active"><input type="checkbox" checked={moduleActive} onChange={(event)=>setModuleActive(event.target.checked)}/><span>신규 제안서에 이 모듈 사용</span></label><Button onClick={()=>void saveCompanyModule()} disabled={busy||!moduleTitle.trim()||!moduleBody.trim()}>관리자 회사 DB 버전 저장</Button></section>}<div className="proposal-next"><Button variant="secondary" onClick={()=>setStep(2)}>← AI 단계</Button><Button onClick={()=>void saveVersion('MANUAL')} disabled={busy||!canEdit}>사람 검수본 저장 · 승인 단계 →</Button></div></div>}
      {step===4&&<div className="proposal-stage proposal-approval-stage"><header><b>STEP 4</b><h3>검토·승인 후 안전한 문서로 내보냅니다.</h3><p>승인 전에는 DOCX·PDF·Markdown을 내보낼 수 없습니다. 모든 출력은 SHA-256과 마스킹 횟수를 DB에 남깁니다.</p></header><div className="proposal-final-preview"><h3>{projectTitle}</h3><p>{subtitle}</p><span>{clientName} · {submissionDate}</span><ol>{chapters.map((item)=><li key={item.number}>{item.number}. {item.title}</li>)}</ol></div><Input label="검토·반려 의견" value={reviewComment} onChange={(event)=>setReviewComment(event.target.value)}/><div className="action-row"><Button variant="secondary" onClick={()=>void workflow('REQUEST_REVIEW')} disabled={busy||!canEdit||activeProposal.status!=='DRAFT'}>검토 요청</Button><Button onClick={()=>void workflow('APPROVE')} disabled={busy||!canApprove||activeProposal.status!=='IN_REVIEW'}>최종 승인</Button><Button variant="danger" onClick={()=>void workflow('REJECT')} disabled={busy||!canApprove||activeProposal.status!=='IN_REVIEW'}>반려</Button></div><div className="proposal-export-row"><Button onClick={()=>void download('docx')} disabled={busy||activeProposal.status!=='APPROVED'}>Word DOCX 내려받기</Button><Button onClick={()=>void download('pdf')} disabled={busy||activeProposal.status!=='APPROVED'}>PDF 내려받기</Button><Button variant="secondary" onClick={()=>void download('md')} disabled={busy||activeProposal.status!=='APPROVED'}>Markdown 내려받기</Button></div><div className="proposal-history"><section><h4>버전·근거 이력</h4><ul>{(activeProposal.versions??[]).map((version)=><li key={version.id}>v{version.versionNumber} · {version.generationMode}{version.isApproved?' · 승인본':''} · SHA {version.sha256.slice(0,12)}… · 근거 {parseArray(version.sourceDocumentVersionIdsJson).length}건</li>)}</ul></section><section><h4>내보내기 DB 이력</h4><ul>{(activeProposal.exports??[]).map((item)=><li key={item.id}>{item.format} · {item.fileName} · 마스킹 {item.sanitizationCount}건</li>)}</ul></section></div></div>}
    </Card>}
  </div>;
};
